"""CP2K mixed-CDFT inputs and output parsing for charge-transfer couplings."""

from __future__ import annotations

import math
import re
from typing import Any

from soft_dft.config import CP2KSettings, HARTREE_TO_EV
from soft_dft.cp2k import (
    CDFT_MODE_FIXED_LAMBDA,
    COMPLEX_ROLE,
    render_molecular_subsys,
    render_qs_force_eval,
)


def _project_name(value: object) -> str:
    project = re.sub(r"[^A-Za-z0-9_-]", "_", str(value))[:100]
    if not project:
        raise ValueError("Task ID produced an empty CP2K project name.")
    return project


def render_mixed_cdft_input(
    task: dict[str, Any],
    settings: CP2KSettings,
    *,
    entrance_wavefunction: str,
    product_wavefunction: str,
    entrance_strength: float,
    product_strength: float,
) -> str:
    """Render a two-state coupling from explicit preconverged CDFT state data."""

    coordinates = task["coordinates_angstrom"]
    total_charge = int(task["total_charge"])
    total_multiplicity = int(task["total_multiplicity"])
    if total_multiplicity < 1:
        raise ValueError("The conserved total multiplicity must be positive.")
    entrance_electrons = int(task["entrance_electrons_on_projectile"])
    product_electrons = int(task["product_electrons_on_projectile"])
    if product_electrons != entrance_electrons + 1:
        raise ValueError("Single capture must add exactly one projectile electron.")

    common = {
        "role": COMPLEX_ROLE,
        "charge": total_charge,
        "multiplicity": total_multiplicity,
        "coordinates_angstrom": coordinates,
    }
    entrance = render_qs_force_eval(
        {**common, "electrons_on_projectile": entrance_electrons},
        settings,
        cdft_strength=entrance_strength,
        cdft_mode=CDFT_MODE_FIXED_LAMBDA,
        cdft_output_prefix="./entrance_cdft",
        wavefunction_restart=entrance_wavefunction,
        force_output_prefix="./entrance_forces",
    )
    product = render_qs_force_eval(
        {**common, "electrons_on_projectile": product_electrons},
        settings,
        cdft_strength=product_strength,
        cdft_mode=CDFT_MODE_FIXED_LAMBDA,
        cdft_output_prefix="./product_cdft",
        wavefunction_restart=product_wavefunction,
        force_output_prefix="./product_forces",
    )
    mixed_subsys = render_molecular_subsys(
        coordinates, settings, role=COMPLEX_ROLE
    )
    project = _project_name(task["task_id"])
    return f"""# Generated by low_energy_charge_exchange; validation-pending pilot.
&GLOBAL
  PROJECT {project}
  RUN_TYPE ENERGY_FORCE
  PRINT_LEVEL MEDIUM
&END GLOBAL

&FORCE_EVAL
  METHOD MIXED
  &MIXED
    MIXING_TYPE MIXED_CDFT
    NGROUPS 1
    &MIXED_CDFT
      COUPLING 1
      FORCE_STATES 1 2
      LAMBDA 1.0
      LOWDIN TRUE
      NONORTHOGONAL_COUPLING TRUE
      METRIC TRUE
      CI FALSE
      &PRINT
        &PROGRAM_RUN_INFO ON
        &END PROGRAM_RUN_INFO
      &END PRINT
    &END MIXED_CDFT
  &END MIXED
{mixed_subsys}
&END FORCE_EVAL

# Entrance: projectile charge q, neutral H2O.
{entrance}

# Product: projectile charge q-1, H2O+; total charge and spin are unchanged.
{product}
"""


_FLOAT = r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[EeDd][-+]?\d+)?"


def _last_float(pattern: str, text: str) -> float | None:
    matches = re.findall(pattern, text, flags=re.IGNORECASE)
    if not matches:
        return None
    return float(str(matches[-1]).replace("D", "E").replace("d", "e"))


def parse_mixed_cdft_output(text: str) -> dict[str, Any]:
    """Extract the diabatic gap, overlap, and coupling needed by Landau--Zener."""

    gap_hartree = _last_float(
        rf"Charge transfer energy\s*\(J-I\)\s*\(Hartree\)\s*:\s*({_FLOAT})",
        text,
    )
    overlap = _last_float(
        rf"Overlap between states I and J\s*:\s*({_FLOAT})", text
    )
    rotation_mhartree = _last_float(
        rf"Diabatic electronic coupling\s*\(rotation,\s*mHartree\)\s*:\s*({_FLOAT})",
        text,
    )
    lowdin_mhartree = _last_float(
        rf"Diabatic electronic coupling\s*\(Lowdin,\s*mHartree\)\s*:\s*({_FLOAT})",
        text,
    )
    nonorthogonal_hartree = _last_float(
        rf"Nonorthogonal diabatic electronic coupling[^:]*:\s*({_FLOAT})", text
    )
    values = (gap_hartree, overlap, lowdin_mhartree)
    valid_values = all(value is not None and math.isfinite(value) for value in values)
    result = {
        "charge_transfer_energy_hartree": gap_hartree,
        "charge_transfer_energy_ev": (
            None if gap_hartree is None else gap_hartree * HARTREE_TO_EV
        ),
        "state_overlap": overlap,
        "coupling_rotation_mhartree": rotation_mhartree,
        "coupling_lowdin_mhartree": lowdin_mhartree,
        "coupling_lowdin_ev": (
            None
            if lowdin_mhartree is None
            else lowdin_mhartree * 1.0e-3 * HARTREE_TO_EV
        ),
        "coupling_nonorthogonal_hartree": nonorthogonal_hartree,
        "mixed_cdft_active": "MIXED_CDFT| Activating mixed CDFT calculation" in text,
        "cdft_state_convergence_count": text.count("CDFT SCF loop converged"),
        "program_ended": "PROGRAM ENDED AT" in text,
    }
    result["valid_completion"] = bool(
        valid_values
        and result["mixed_cdft_active"]
        and result["cdft_state_convergence_count"] >= 2
        and result["program_ended"]
    )
    return result
