from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pytest

PHYSICS_ICE_DIR = Path(__file__).resolve().parents[1] / "python_scripts" / "physics_ice"
if str(PHYSICS_ICE_DIR) not in sys.path:
    sys.path.insert(0, str(PHYSICS_ICE_DIR))

import barkas_dcs
import emfietzoglou_model_finite_q as model
import generate_ice_cross_sections_ion as ion_generator


def test_barkas_constants():
    assert np.isclose(barkas_dcs.RE_CLASSICAL_CM, 2.8179403205e-13)
    assert np.isclose(barkas_dcs.ALPHA_FINE, 7.2973525643e-3)
    assert np.isclose(barkas_dcs.MEC2_EV, 510998.95069)
    assert barkas_dcs.H2O_Z_MOL == 10.0
    assert np.isclose(barkas_dcs.H2O_CB, 1.0)
    assert np.isclose(barkas_dcs.mass_u_to_electron_mass(1.0), 1822.888486217313)


def test_arbi_matches_official_sbethe_reference_values():
    # Reference values generated by compiling the official SBETHE sbethe.f
    # ARBI1/ARBI2 routines from DOI: 10.17632/7zw25f428t.2.
    ref = np.array(
        [
            [0.0, np.inf, 2.1775899999999999e00],
            [9.9999999600419720e-13, 1.2558607047877673e02, 2.1775899999999999e00],
            [1.0000000133514320e-10, 1.0388471715978355e02, 2.1775899999999999e00],
            [9.9999999392252903e-09, 8.2183364014463805e01, 2.1775899999997574e00],
            [9.9999999747524271e-07, 6.0482011464113427e01, 2.1775899986847258e00],
            [9.9999997473787516e-05, 3.8781235101290051e01, 2.1775842971254549e00],
            [1.0000000474974513e-03, 2.7938170277590213e01, 2.1772708513691539e00],
            [9.9999997764825821e-03, 1.7116567627499776e01, 2.1633086621027440e00],
            [1.0000000149011612e-01, 6.4898623680613570e00, 1.7952687188761858e00],
            [2.5000000000000000e-01, 2.8748596808689566e00, 1.1697993423876067e00],
            [5.0000000000000000e-01, 9.9716379918202336e-01, 5.3608519128440202e-01],
            [1.0000000000000000e00, 1.6164090000000808e-01, 1.1060472786493629e-01],
            [2.0000000000000000e00, 6.8948259560347039e-03, 5.6699112649801339e-03],
            [5.0000000000000000e00, 3.2562894033100325e-06, 3.0483975756942004e-06],
            [1.0000000000000000e01, 4.8297184344001185e-11, 4.6898587069464902e-11],
            [1.5000000000000000e01, 1.1682588000944730e-15, 1.1472010379882018e-15],
            [2.0000000000000000e01, 3.5733134403075505e-20, 3.5249562325204367e-20],
            [5.0000000000000000e01, 2.4966287273467979e-41, 2.4757820174394742e-41],
            [1.0000000000000000e02, 0.0, 0.0],
        ],
        dtype=float,
    )
    x = ref[:, 0]
    assert np.isinf(barkas_dcs.arbi1(0.0))
    assert np.allclose(barkas_dcs.arbi1(x[1:]), ref[1:, 1], rtol=2e-7, atol=1e-13)
    assert np.allclose(barkas_dcs.arbi2(x), ref[:, 2], rtol=2e-7, atol=1e-13)


def test_barkas_zeff_formula():
    T = np.array([1.0e6, 1.0e8])
    Z = 8.0
    mass_au = 29156.9469
    beta, _ = barkas_dcs.projectile_beta_gamma(T, mass_au)
    expected = Z * (1.0 - np.exp(-125.0 * beta * Z ** (-2.0 / 3.0)))
    assert np.allclose(barkas_dcs.barkas_effective_charge(T, Z, mass_au), expected)


def test_projectile_mass_convention_uses_electron_mass_units():
    proton_mass_me = 1836.152673
    beta, gamma = barkas_dcs.projectile_beta_gamma(1.0e6, proton_mass_me)
    expected_gamma = 1.0 + 1.0e6 / (proton_mass_me * barkas_dcs.MEC2_EV)
    assert np.isclose(gamma, expected_gamma)
    assert np.isclose(beta, np.sqrt(1.0 - 1.0 / expected_gamma**2))
    assert np.isclose(barkas_dcs.mass_number_to_electron_mass(16.0), 16.0 * barkas_dcs.U_TO_ELECTRON_MASS)
    assert np.isclose(barkas_dcs.mass_number_to_electron_mass(32.0), 32.0 * barkas_dcs.U_TO_ELECTRON_MASS)


def test_wmax_for_proton_and_oxygen_uses_mass_ratio():
    proton_mass_me = 1836.152673
    oxygen_mass_me = 29156.9469
    for mass_me in (proton_mass_me, oxygen_mass_me):
        beta, gamma = barkas_dcs.projectile_beta_gamma(1.0e6, mass_me)
        expected = (
            2.0
            * beta**2
            * gamma**2
            * barkas_dcs.MEC2_EV
            / (1.0 + 2.0 * gamma / mass_me + 1.0 / mass_me**2)
        )
        assert np.isclose(barkas_dcs.wmax_eV(1.0e6, mass_me), expected)


def test_total_and_per_u_conversion_equivalence():
    mass_number = 16.0
    mass_me = 29156.9469
    T_per_u = 1.0e6
    T_total = mass_number * T_per_u
    beta_total, gamma_total = barkas_dcs.projectile_beta_gamma(T_total, mass_me)
    beta_converted, gamma_converted = barkas_dcs.projectile_beta_gamma(mass_number * T_per_u, mass_me)
    assert np.isclose(beta_total, beta_converted)
    assert np.isclose(gamma_total, gamma_converted)


def test_barkas_xi_formula():
    T = 1.0e6
    W = np.array([10.0, 100.0])
    mass_au = 1836.152673
    beta, gamma = barkas_dcs.projectile_beta_gamma(T, mass_au)
    expected = 0.5616 * W / (gamma * beta**2 * barkas_dcs.MEC2_EV)
    assert np.allclose(barkas_dcs.barkas_xi(W, T, mass_au), expected)


def test_barkas_kernel_formula_and_units():
    T = np.array([1.0e6, 2.0e6])
    W = np.array([20.0, 80.0])
    df_dW = np.array([0.2, 0.05])
    z_int = np.array([1.0, 2.5])
    mass_me = 1836.152673

    beta, gamma = barkas_dcs.projectile_beta_gamma(T, mass_me)
    xi = 0.5616 * barkas_dcs.H2O_CB * W / (gamma * beta**2 * barkas_dcs.MEC2_EV)
    expected_cm2 = (
        4.0
        * np.pi
        * barkas_dcs.RE_CLASSICAL_CM**2
        * barkas_dcs.ALPHA_FINE
        / (gamma**2 * beta**5)
        * df_dW
        * (barkas_dcs.arbi1(xi) + barkas_dcs.arbi2(xi) / gamma**2)
    )
    assert np.allclose(
        barkas_dcs.barkas_unit_dcs_cm2_per_eV(T, W, mass_me, df_dW),
        expected_cm2,
    )
    assert np.allclose(
        barkas_dcs.barkas_dcs_m2_per_eV(T, W, z_int, mass_me, df_dW),
        barkas_dcs.CM2_TO_M2 * z_int**3 * expected_cm2,
    )


def test_oos_normalization_per_h2o():
    s = model.epsilon_optical("amorphous")
    W = np.geomspace(1.0e-3, 1.0e6, 1000)
    oos = barkas_dcs.oos_density(W, s, material="amorphous", include_kshell=True)
    assert np.isclose(oos.valence_integral_raw * oos.valence_norm, 8.0, rtol=1e-12)
    assert np.isclose(oos.ok_integral_raw * oos.ok_norm, 2.0, rtol=1e-12)
    assert np.isclose(oos.total_integral_norm_grid, 10.0, rtol=1e-5)
    assert np.isfinite(oos.total_integral_unique_grid)
    assert oos.df_dW_total_unique.size == np.unique(W).size


def test_oos_normalization_is_separate_from_finite_q_kshell_fsum():
    s = model.epsilon_optical("amorphous")
    W = np.geomspace(1.0e-6, 1.0e8, 5000)
    oos = barkas_dcs.oos_density(W, s, material="amorphous", include_kshell=True)
    assert np.isclose(oos.valence_integral_raw * oos.valence_norm, 8.0, rtol=1e-12)
    assert np.isclose(oos.ok_integral_raw * oos.ok_norm, 2.0, rtol=1e-12)
    assert np.isclose(oos.total_integral_norm_grid, 10.0, rtol=1e-12)

    kshell_fsum = model.oxygen_K_hydrogenic_gos_fsum(
        B_K_eV=model.OXYGEN_K_B_EV,
        Zeff=model.OXYGEN_K_ZEFF,
        normalize_fsum=True,
        fsum_target=model.OXYGEN_K_FSUM_TARGET,
    )
    assert np.isclose(kshell_fsum, model.OXYGEN_K_FSUM_TARGET, rtol=1e-4)
    assert not np.isclose(2.0, model.OXYGEN_K_FSUM_TARGET)


def test_born_reference_charge_scaling_modes():
    z_int = np.array([2.0, 4.0])
    scale, q_ref = barkas_dcs.born_reference_scale(z_int, 8.0, "bare_Z")
    assert q_ref == 8.0
    assert np.allclose(scale, (z_int / 8.0) ** 2)
    scale, q_ref = barkas_dcs.born_reference_scale(z_int, 8.0, "unit_charge")
    assert q_ref == 1.0
    assert np.allclose(scale, z_int**2)
    scale, q_ref = barkas_dcs.born_reference_scale(z_int, 8.0, "explicit_q", q_reference=2.0)
    assert q_ref == 2.0
    assert np.allclose(scale, (z_int / 2.0) ** 2)
    try:
        barkas_dcs.born_reference_scale(z_int, 8.0, None)
    except ValueError:
        pass
    else:
        raise AssertionError("missing born_reference_charge should fail")


def test_barkas_rejects_nonpositive_w():
    try:
        barkas_dcs.barkas_unit_dcs_cm2_per_eV(
            np.array([1.0e6]),
            np.array([0.0]),
            1836.152673,
            np.array([1.0]),
        )
    except ValueError:
        pass
    else:
        raise AssertionError("nonpositive W should fail")


def test_barkas_dcs_total_integrates_to_tcs_total():
    s = model.epsilon_optical("amorphous")
    T = 1.0e6
    W = np.array([10.0, 20.0, 40.0, 80.0, 160.0])
    dcs_data = {
        "T_line": np.full(W.size, T),
        "E_line": W,
        "exc_vals": np.full((W.size, 1), 1.0e-6),
        "ion_vals": np.full((W.size, 1), 2.0e-6),
    }
    corrected, diag = barkas_dcs.apply_barkas_correction_to_dcs_data(
        dcs_data,
        s,
        material="amorphous",
        projectile_mass_me=1836.152673,
        nuclear_charge=1.0,
        charge_mode="bare",
        include_barkas_dcs=True,
        include_kshell=True,
        dcs_scale_m2=1.0,
        born_reference_charge="bare_Z",
    )
    total_file = np.sum(corrected["exc_vals"], axis=1) + np.sum(corrected["ion_vals"], axis=1)
    expected = np.trapezoid(total_file, W)
    assert np.allclose(diag.TCS_T_eV, np.array([T]))
    assert np.isclose(diag.TCS_total_m2[0], expected)
    assert np.isclose(diag.S_Barkas_check_eV_m2[0], np.trapezoid(W * diag.DCS_Barkas_m2_per_eV, W))
    assert diag.negative_or_unstable_T_eV.size == 0
    assert np.all(np.isfinite(diag.DCS_total_m2_per_eV))
    assert np.all(diag.DCS_total_m2_per_eV >= 0.0)
    assert diag.barkas_channel_distribution == "bookkeeping_weighted_across_existing_channels"


def test_same_interaction_charge_scales_born_and_barkas_terms():
    s = model.epsilon_optical("amorphous")
    T = 1.0e6
    W = np.array([10.0, 20.0, 40.0, 80.0, 160.0])
    exc = np.full((W.size, 1), 1.0e-6)
    ion = np.full((W.size, 1), 2.0e-6)
    z_int = 3.0
    dcs_scale_m2 = 2.0e-22
    dcs_data = {
        "T_line": np.full(W.size, T),
        "E_line": W,
        "exc_vals": exc,
        "ion_vals": ion,
    }
    corrected, diag = barkas_dcs.apply_barkas_correction_to_dcs_data(
        dcs_data,
        s,
        material="amorphous",
        projectile_mass_me=1836.152673,
        nuclear_charge=8.0,
        charge_mode="explicit",
        explicit_charge=z_int,
        include_barkas_dcs=True,
        include_kshell=True,
        dcs_scale_m2=dcs_scale_m2,
        born_reference_charge="unit_charge",
    )

    raw_born_m2 = dcs_scale_m2 * np.sum(np.hstack([exc, ion]), axis=1)
    oos = barkas_dcs.oos_density(W, s, material="amorphous", include_kshell=True)
    expected_barkas = barkas_dcs.barkas_dcs_m2_per_eV(
        np.full(W.size, T),
        W,
        z_int=np.full(W.size, z_int),
        projectile_mass_me=1836.152673,
        df_dW=oos.df_dW_total,
    )

    assert np.allclose(diag.z_int, z_int)
    assert np.allclose(diag.DCS_Born_m2_per_eV, z_int**2 * raw_born_m2)
    assert np.allclose(diag.DCS_Barkas_m2_per_eV, expected_barkas)
    assert np.allclose(
        diag.DCS_total_m2_per_eV,
        dcs_scale_m2 * (np.sum(corrected["exc_vals"], axis=1) + np.sum(corrected["ion_vals"], axis=1)),
    )


def test_bloch_dcs_cannot_be_enabled_silently():
    old_argv = sys.argv[:]
    try:
        sys.argv = ["generate_ice_cross_sections_ion.py", "--include-bloch-dcs"]
        with pytest.raises(ValueError, match="Bloch corrections"):
            ion_generator._include_bloch_dcs_from_argv(default=False)
        sys.argv = ["generate_ice_cross_sections_ion.py", "--include-bloch-dcs=true"]
        with pytest.raises(ValueError, match="Bloch corrections"):
            ion_generator._include_bloch_dcs_from_argv(default=False)
    finally:
        sys.argv = old_argv


def test_energy_unit_per_u_converts_to_total_before_kinematics():
    previous = ion_generator.PROJECTILE_KEY
    try:
        ion_generator.set_projectile("oxygen")
        assert ion_generator.PROJECTILE_MASS_NUMBER == 16.0
        assert ion_generator._energy_range_to_total_eV(1.0e6, 2.0e6, "total") == (1.0e6, 2.0e6)
        assert ion_generator._energy_range_to_total_eV(1.0e6, 2.0e6, "per_u") == (16.0e6, 32.0e6)
    finally:
        ion_generator.set_projectile(previous)
