#!/usr/bin/env python3
"""
Generate C(q+) + H2O charge-changing cross sections for Geant4.

Physics basis
-------------
This is an independent-water-molecule, three-body CTMC implementation of the
framework in:

    T. Liamsuwan and H. Nikjoo, Phys. Med. Biol. 58 (2013) 641-672
    https://doi.org/10.1088/0031-9155/58/3/641

The code implements:

* the Garvey screened-core potential (paper equations 6-9);
* microcanonical initial electron sampling (equations 3-5);
* the paper's 12 relative-coordinate equations with a Numba-compiled
  adaptive DOP853 integrator (SciPy DOP853 remains as a reference backend);
* the modified IEVM and IPM channel construction (equations 13-19);
* impact-parameter integration (equation 20).

The generated microscopic cross sections are per H2O molecule. Ice density is
therefore NOT applied here. Geant4 must form the macroscopic cross section as

    Sigma(E, q) = n_H2O * sigma(E, q).

Important terminology
---------------------
The q used here is the discrete carbon charge state, q = 0, ..., 6. It is not
the momentum-transfer variable used in dielectric/ELF integrations. Hence
dq = 1 physically. Charge exchange is not generated by a dE dq ELF integral.

Outputs
-------
carbon_charge_exchange_h2o.dat
    Geant4-oriented text table:
    E_keV_u q SC TI SL LI decrease increase  [cross sections in cm2/H2O]

carbon_charge_exchange_h2o.csv
    The same table with named CSV columns.

carbon_charge_exchange_probabilities.npz
    One-electron probabilities on the impact-parameter grid, useful for
    convergence checks and restart.

carbon_charge_exchange_metadata.json
    Full numerical configuration and provenance.

The publication settings used by the paper are expensive: more than 10,000
trajectories for every impact parameter. Use small --trajectories and
--impact-points only for software smoke tests, never for production physics.
The scheduler evaluates shorter high-energy trajectories first, keeps only a
bounded number of futures in memory, and checkpoints completed probability
points. Parent-owned tqdm bars report both attempted trajectories and completed
grid points; workers update the trajectory counter in low-overhead chunks.
These optimizations do not reduce the requested Monte Carlo statistics.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import multiprocessing
import os
import sys
import threading
from concurrent.futures import FIRST_COMPLETED, ProcessPoolExecutor, wait
from dataclasses import asdict, dataclass
from functools import lru_cache
from pathlib import Path
from typing import Iterable, Sequence

# Each process evaluates scalar trajectories. Prevent NumPy/SciPy libraries
# from creating nested thread pools inside the process pool.
os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
os.environ.setdefault("NUMEXPR_NUM_THREADS", "1")

import numpy as np
from scipy.integrate import cumulative_trapezoid, solve_ivp
from scipy.optimize import brentq
from tqdm import tqdm

from constants import (
    ATOMIC_MASS_UNIT_MASS_AU,
    CARBON_12_BARE_MASS_AU,
    CARBON_CHARGE_EXCHANGE_DIR,
    CARBON_CTMC_BACKEND,
    CARBON_CTMC_CHARGE_STEP,
    CARBON_CTMC_CHARGES,
    CARBON_CTMC_ENERGY_MAX_KEV_U,
    CARBON_CTMC_ENERGY_MIN_KEV_U,
    CARBON_CTMC_ENERGY_POINTS,
    CARBON_CTMC_ENERGY_SPACING,
    CARBON_CTMC_IMPACT_POINTS,
    CARBON_CTMC_LOSS_BMAX_AU,
    CARBON_CTMC_MAXIMUM_INTEGRATION_STEPS,
    CARBON_CTMC_PROGRESS_INTERVAL,
    CARBON_CTMC_RADIAL_GRID_POINTS,
    CARBON_CTMC_SEED,
    CARBON_CTMC_TARGET_BMAX_AU,
    CARBON_CTMC_TRAJECTORIES,
    CARBON_CTMC_WORKERS,
    EH,
    EV_TO_HA,
    H2O_MOLECULE_MASS_AU,
    a0,
)

try:
    from ctmc_numba_backend import (
        integrate_relative_dop853,
        warm_up_numba_backend,
    )
except ImportError as exc:  # pragma: no cover - exercised without Numba.
    integrate_relative_dop853 = None
    warm_up_numba_backend = None
    _NUMBA_IMPORT_ERROR: ImportError | None = exc
else:
    _NUMBA_IMPORT_ERROR = None


# ---------------------------------------------------------------------------
# Atomic units and paper data
# ---------------------------------------------------------------------------

EV_PER_HARTREE = EH
KEV_TO_HARTREE = 1000.0 * EV_TO_HA
U_TO_ELECTRON_MASS = ATOMIC_MASS_UNIT_MASS_AU
BOHR_CM = a0 * 100.0
BOHR2_CM2 = BOHR_CM * BOHR_CM

ELECTRON_MASS_AU = 1.0
CARBON_MASS_AU = CARBON_12_BARE_MASS_AU
WATER_MASS_AU = H2O_MOLECULE_MASS_AU

CARBON_NUCLEAR_CHARGE = 6
WATER_PSEUDO_NUCLEAR_CHARGE = 10


@dataclass(frozen=True)
class ScreeningParameters:
    zeta0: float
    zeta1: float
    eta0: float
    eta1: float


# Table 2 of Liamsuwan and Nikjoo (2013).
SCREENING_BY_SPECTATORS: dict[int, ScreeningParameters] = {
    0: ScreeningParameters(1.000, 0.0000, 0.000, 0.0000),
    1: ScreeningParameters(2.625, 1.2996, 1.770, 1.1402),
    2: ScreeningParameters(2.164, 0.9764, 1.750, 0.6821),
    3: ScreeningParameters(1.300, 0.6465, 1.880, 0.5547),
    4: ScreeningParameters(1.031, 0.4924, 2.000, 0.4939),
    5: ScreeningParameters(1.065, 0.4800, 2.130, 0.4434),
    6: ScreeningParameters(1.179, 0.4677, 2.270, 0.4143),
    9: ScreeningParameters(1.792, 0.4515, 2.710, 0.3671),
    10: ScreeningParameters(1.712, 0.3923, 2.850, 0.3469),
}


@dataclass(frozen=True)
class Orbital:
    label: str
    binding_eV: float
    active_electrons: int


# Table 1. The paper orders these outermost to innermost.
WATER_ORBITALS: tuple[Orbital, ...] = (
    Orbital("1b1", 12.62, 2),
    Orbital("3a1", 14.75, 2),
    Orbital("1b2", 18.51, 2),
    Orbital("2a1", 32.40, 2),
    Orbital("1a1", 539.70, 2),
)

# First ionization energy and number of electrons in the outermost occupied
# carbon shell, from Table 1. C6+ has no bound electron to lose.
CARBON_OUTER_ORBITAL: dict[int, Orbital] = {
    0: Orbital("C0_outer", 11.26, 2),
    1: Orbital("C1_outer", 24.39, 1),
    2: Orbital("C2_outer", 47.90, 2),
    3: Orbital("C3_outer", 64.50, 1),
    4: Orbital("C4_outer", 392.14, 2),
    5: Orbital("C5_outer", 490.06, 1),
}


@dataclass(frozen=True)
class CorePotential:
    nuclear_charge: int
    spectators: int
    eta: float
    zeta: float

    @classmethod
    def from_zn(cls, nuclear_charge: int, spectators: int) -> "CorePotential":
        try:
            p = SCREENING_BY_SPECTATORS[int(spectators)]
        except KeyError as exc:
            raise ValueError(
                f"No Garvey screening parameters for N={spectators}"
            ) from exc
        charge_offset = nuclear_charge - spectators - 1
        eta = p.eta0 + p.eta1 * charge_offset
        zeta = p.zeta0 + p.zeta1 * charge_offset
        if spectators == 0:
            # eta and zeta do not affect an unscreened core, but finite values
            # keep the generic implementation numerically well defined.
            eta = 0.0
            zeta = 1.0
        if zeta <= 0.0:
            raise ValueError(
                f"Non-positive Garvey zeta for Z={nuclear_charge}, N={spectators}"
            )
        return cls(
            nuclear_charge=int(nuclear_charge),
            spectators=int(spectators),
            eta=float(eta),
            zeta=float(zeta),
        )


@dataclass(frozen=True)
class CTMCConfig:
    backend: str
    trajectories: int
    target_bmax_au: tuple[float, ...]
    loss_bmax_au: float
    radial_grid_points: int
    start_separation_au: float | None
    rtol: float
    atol: float
    max_step_au: float
    minimum_radius_au: float
    max_failure_fraction: float
    maximum_integration_steps: int
    seed: int


_WORKER_CONFIG: CTMCConfig | None = None
_WORKER_PROGRESS_COUNTER = None
_WORKER_PROGRESS_INTERVAL = CARBON_CTMC_PROGRESS_INTERVAL


# ---------------------------------------------------------------------------
# Garvey screened potential and three-body equations of motion
# ---------------------------------------------------------------------------


def effective_charge_and_derivative(
    core: CorePotential, radius_au: float
) -> tuple[float, float]:
    """Return Z_eff(r) and dZ_eff/dr for equations (6)-(9)."""
    r = max(float(radius_au), np.finfo(float).tiny)
    z = float(core.nuclear_charge)
    n = float(core.spectators)
    if core.spectators == 0:
        return z, 0.0

    exponent = core.zeta * r
    if exponent > 700.0:
        return z - n, 0.0

    exp_term = math.exp(exponent)
    ratio = core.eta / core.zeta
    denominator = 1.0 + ratio * (exp_term - 1.0)
    omega = 1.0 / denominator
    domega_dr = -core.eta * exp_term / (denominator * denominator)
    return z - n + n * omega, n * domega_dr


def potential_magnitude(core: CorePotential, radius_au: float) -> float:
    """Positive Z_eff(r)/r used in the electron binding potential."""
    r = max(float(radius_au), np.finfo(float).tiny)
    zeff, _ = effective_charge_and_derivative(core, r)
    return zeff / r


def _pair_force_on_first(
    displacement: np.ndarray,
    charge_first: float,
    derivative_first: float,
    charge_second: float,
    derivative_second: float,
    minimum_radius_au: float,
) -> np.ndarray:
    """
    Force on particle one for U(r) = Q1(r) Q2(r) / r.

    displacement is r1-r2. The opposite force acts on particle two.
    """
    radius = max(float(np.linalg.norm(displacement)), minimum_radius_au)
    unit = displacement / radius
    product = charge_first * charge_second
    dpotential_dr = (
        derivative_first * charge_second
        + charge_first * derivative_second
    ) / radius - product / (radius * radius)
    return -dpotential_dr * unit


def _three_body_rhs(
    _: float,
    state: np.ndarray,
    target_core: CorePotential,
    projectile_core: CorePotential,
    minimum_radius_au: float,
) -> np.ndarray:
    positions = state[:9].reshape(3, 3)
    velocities = state[9:].reshape(3, 3)
    forces = np.zeros((3, 3), dtype=float)

    # Particle order: target core, projectile core, active electron.
    target_position, projectile_position, electron_position = positions

    # Target-projectile interaction.
    d_tp = target_position - projectile_position
    r_tp = max(float(np.linalg.norm(d_tp)), minimum_radius_au)
    zt, dzt = effective_charge_and_derivative(target_core, r_tp)
    zp, dzp = effective_charge_and_derivative(projectile_core, r_tp)
    force = _pair_force_on_first(
        d_tp, zt, dzt, zp, dzp, minimum_radius_au
    )
    forces[0] += force
    forces[1] -= force

    # Target-electron interaction.
    d_te = target_position - electron_position
    r_te = max(float(np.linalg.norm(d_te)), minimum_radius_au)
    zt, dzt = effective_charge_and_derivative(target_core, r_te)
    force = _pair_force_on_first(
        d_te, zt, dzt, -1.0, 0.0, minimum_radius_au
    )
    forces[0] += force
    forces[2] -= force

    # Projectile-electron interaction.
    d_pe = projectile_position - electron_position
    r_pe = max(float(np.linalg.norm(d_pe)), minimum_radius_au)
    zp, dzp = effective_charge_and_derivative(projectile_core, r_pe)
    force = _pair_force_on_first(
        d_pe, zp, dzp, -1.0, 0.0, minimum_radius_au
    )
    forces[1] += force
    forces[2] -= force

    accelerations = forces / np.array(
        [WATER_MASS_AU, CARBON_MASS_AU, ELECTRON_MASS_AU],
        dtype=float,
    )[:, None]

    derivative = np.empty_like(state)
    derivative[:9] = velocities.reshape(-1)
    derivative[9:] = accelerations.reshape(-1)
    return derivative


def _pair_potential_energy(
    displacement: np.ndarray,
    first: CorePotential | None,
    second: CorePotential | None,
    minimum_radius_au: float,
) -> float:
    radius = max(float(np.linalg.norm(displacement)), minimum_radius_au)
    if first is None:
        q_first = -1.0
    else:
        q_first, _ = effective_charge_and_derivative(first, radius)
    if second is None:
        q_second = -1.0
    else:
        q_second, _ = effective_charge_and_derivative(second, radius)
    return q_first * q_second / radius


def total_three_body_energy(
    state: np.ndarray,
    target_core: CorePotential,
    projectile_core: CorePotential,
    minimum_radius_au: float,
) -> float:
    positions = state[:9].reshape(3, 3)
    velocities = state[9:].reshape(3, 3)
    masses = np.array(
        [WATER_MASS_AU, CARBON_MASS_AU, ELECTRON_MASS_AU],
        dtype=float,
    )
    kinetic = 0.5 * np.sum(masses[:, None] * velocities * velocities)
    potential = _pair_potential_energy(
        positions[0] - positions[1],
        target_core,
        projectile_core,
        minimum_radius_au,
    )
    potential += _pair_potential_energy(
        positions[0] - positions[2],
        target_core,
        None,
        minimum_radius_au,
    )
    potential += _pair_potential_energy(
        positions[1] - positions[2],
        projectile_core,
        None,
        minimum_radius_au,
    )
    return float(kinetic + potential)


def _state_to_relative_coordinates(state: np.ndarray) -> np.ndarray:
    """Convert the 18 Cartesian variables to the paper's 12 relative ones."""
    positions = state[:9].reshape(3, 3)
    velocities = state[9:].reshape(3, 3)
    relative = np.empty(12, dtype=float)
    relative[:3] = positions[1] - positions[0]
    relative[3:6] = positions[2] - positions[0]
    relative[6:9] = velocities[1] - velocities[0]
    relative[9:12] = velocities[2] - velocities[0]
    return relative


def _relative_to_state(relative: np.ndarray) -> np.ndarray:
    """Construct an equivalent Cartesian state in the instantaneous target frame."""
    state = np.zeros(18, dtype=float)
    state[3:6] = relative[:3]
    state[6:9] = relative[3:6]
    state[12:15] = relative[6:9]
    state[15:18] = relative[9:12]
    return state


def relative_three_body_energy(
    relative: np.ndarray,
    target_core: CorePotential,
    projectile_core: CorePotential,
    minimum_radius_au: float,
) -> float:
    """Internal energy computed from relative coordinates with COM removed."""
    r_projectile = relative[:3]
    r_electron = relative[3:6]
    v_projectile = relative[6:9]
    v_electron = relative[9:12]

    total_mass = WATER_MASS_AU + CARBON_MASS_AU + ELECTRON_MASS_AU
    center_of_mass_velocity = (
        CARBON_MASS_AU * v_projectile
        + ELECTRON_MASS_AU * v_electron
    ) / total_mass
    target_velocity_com = -center_of_mass_velocity
    projectile_velocity_com = v_projectile - center_of_mass_velocity
    electron_velocity_com = v_electron - center_of_mass_velocity
    kinetic = 0.5 * (
        WATER_MASS_AU * np.dot(target_velocity_com, target_velocity_com)
        + CARBON_MASS_AU
        * np.dot(projectile_velocity_com, projectile_velocity_com)
        + ELECTRON_MASS_AU
        * np.dot(electron_velocity_com, electron_velocity_com)
    )

    potential = _pair_potential_energy(
        -r_projectile,
        target_core,
        projectile_core,
        minimum_radius_au,
    )
    potential += _pair_potential_energy(
        -r_electron,
        target_core,
        None,
        minimum_radius_au,
    )
    potential += _pair_potential_energy(
        r_projectile - r_electron,
        projectile_core,
        None,
        minimum_radius_au,
    )
    return float(kinetic + potential)


def _core_parameters(core: CorePotential) -> np.ndarray:
    return np.array(
        [
            core.nuclear_charge,
            core.spectators,
            core.eta,
            core.zeta,
        ],
        dtype=np.float64,
    )


# ---------------------------------------------------------------------------
# Microcanonical initial state, equations (3)-(5)
# ---------------------------------------------------------------------------


@lru_cache(maxsize=64)
def _microcanonical_radius_cdf(
    nuclear_charge: int,
    spectators: int,
    binding_eV_rounded: float,
    radial_grid_points: int,
) -> tuple[np.ndarray, np.ndarray]:
    core = CorePotential.from_zn(nuclear_charge, spectators)
    binding_ha = binding_eV_rounded / EV_PER_HARTREE

    def turning_point_function(radius: float) -> float:
        return potential_magnitude(core, radius) - binding_ha

    lower = 1.0e-12
    upper = max(2.0 * nuclear_charge / binding_ha, 1.0)
    while turning_point_function(upper) > 0.0:
        upper *= 2.0
        if upper > 1.0e8:
            raise RuntimeError("Could not bracket microcanonical turning point")
    rmax = brentq(turning_point_function, lower, upper, xtol=1.0e-13)

    positive_grid = np.geomspace(
        max(rmax * 1.0e-10, 1.0e-12),
        rmax * (1.0 - 1.0e-12),
        int(radial_grid_points) - 1,
    )
    radii = np.concatenate(([0.0], positive_grid, [rmax]))
    integrand = np.zeros_like(radii)
    for index in range(1, radii.size - 1):
        radius = float(radii[index])
        available = potential_magnitude(core, radius) - binding_ha
        integrand[index] = (
            radius
            * radius
            * math.sqrt(max(2.0 * available, 0.0))
        )
    cumulative = cumulative_trapezoid(integrand, radii, initial=0.0)
    if cumulative[-1] <= 0.0 or not np.isfinite(cumulative[-1]):
        raise RuntimeError("Invalid microcanonical radial distribution")
    cumulative /= cumulative[-1]
    return radii, cumulative


def _random_unit_vector(rng: np.random.Generator) -> np.ndarray:
    z = rng.uniform(-1.0, 1.0)
    phi = rng.uniform(0.0, 2.0 * math.pi)
    transverse = math.sqrt(max(1.0 - z * z, 0.0))
    return np.array(
        [transverse * math.cos(phi), transverse * math.sin(phi), z],
        dtype=float,
    )


def sample_bound_electron(
    core: CorePotential,
    core_mass_au: float,
    binding_eV: float,
    core_position: np.ndarray,
    core_velocity: np.ndarray,
    radial_grid_points: int,
    rng: np.random.Generator,
) -> tuple[np.ndarray, np.ndarray]:
    radii, cumulative = _microcanonical_radius_cdf(
        core.nuclear_charge,
        core.spectators,
        round(float(binding_eV), 10),
        int(radial_grid_points),
    )
    radius = float(np.interp(rng.random(), cumulative, radii))
    radius = max(radius, 1.0e-12)
    relative_position = radius * _random_unit_vector(rng)

    reduced_mass = (
        ELECTRON_MASS_AU
        * core_mass_au
        / (ELECTRON_MASS_AU + core_mass_au)
    )
    binding_ha = binding_eV / EV_PER_HARTREE
    kinetic_ha = potential_magnitude(core, radius) - binding_ha
    momentum = math.sqrt(max(2.0 * reduced_mass * kinetic_ha, 0.0))
    relative_velocity = (
        momentum / reduced_mass
    ) * _random_unit_vector(rng)

    return (
        np.asarray(core_position, dtype=float) + relative_position,
        np.asarray(core_velocity, dtype=float) + relative_velocity,
    )


# ---------------------------------------------------------------------------
# One-electron trajectories and classification
# ---------------------------------------------------------------------------


def projectile_velocity_au(energy_keV_u: float) -> float:
    energy_ha_per_u = float(energy_keV_u) * KEV_TO_HARTREE
    return math.sqrt(2.0 * energy_ha_per_u / U_TO_ELECTRON_MASS)


def automatic_start_separation_au(energy_keV_u: float) -> float:
    """
    Interpolate the paper's stated 10^4-to-10^3 a.u. separation range.

    The precise per-energy values were not tabulated. This smooth rule reaches
    10,000 a.u. at 1 keV/u and 1,000 a.u. at 10^4 keV/u. Convergence must be
    checked by rerunning with --start-separation-au.
    """
    energy = max(float(energy_keV_u), 1.0)
    separation = 1.0e4 * energy ** (-0.25)
    return float(np.clip(separation, 1.0e3, 1.0e4))


def _electron_core_energy(
    final_state: np.ndarray,
    core_index: int,
    core: CorePotential,
    core_mass_au: float,
    minimum_radius_au: float,
) -> float:
    positions = final_state[:9].reshape(3, 3)
    velocities = final_state[9:].reshape(3, 3)
    relative_position = positions[2] - positions[core_index]
    relative_velocity = velocities[2] - velocities[core_index]
    radius = max(float(np.linalg.norm(relative_position)), minimum_radius_au)
    reduced_mass = (
        ELECTRON_MASS_AU
        * core_mass_au
        / (ELECTRON_MASS_AU + core_mass_au)
    )
    return float(
        0.5 * reduced_mass * np.dot(relative_velocity, relative_velocity)
        - potential_magnitude(core, radius)
    )


def _build_initial_state(
    *,
    energy_keV_u: float,
    impact_parameter_au: float,
    separation_au: float,
    bound_to: str,
    binding_eV: float,
    target_core: CorePotential,
    projectile_core: CorePotential,
    radial_grid_points: int,
    rng: np.random.Generator,
) -> np.ndarray:
    velocity = projectile_velocity_au(energy_keV_u)
    target_position = np.zeros(3, dtype=float)
    projectile_position = np.array(
        [impact_parameter_au, 0.0, -separation_au],
        dtype=float,
    )
    target_velocity = np.zeros(3, dtype=float)
    projectile_velocity = np.array([0.0, 0.0, velocity], dtype=float)

    if bound_to == "target":
        electron_position, electron_velocity = sample_bound_electron(
            target_core,
            WATER_MASS_AU,
            binding_eV,
            target_position,
            target_velocity,
            radial_grid_points,
            rng,
        )
    elif bound_to == "projectile":
        electron_position, electron_velocity = sample_bound_electron(
            projectile_core,
            CARBON_MASS_AU,
            binding_eV,
            projectile_position,
            projectile_velocity,
            radial_grid_points,
            rng,
        )
    else:
        raise ValueError("bound_to must be 'target' or 'projectile'")

    state = np.empty(18, dtype=float)
    state[:9] = np.vstack(
        (target_position, projectile_position, electron_position)
    ).reshape(-1)
    state[9:] = np.vstack(
        (target_velocity, projectile_velocity, electron_velocity)
    ).reshape(-1)
    return state


def simulate_one_trajectory(
    *,
    energy_keV_u: float,
    charge_state: int,
    impact_parameter_au: float,
    bound_to: str,
    binding_eV: float,
    config: CTMCConfig,
    rng: np.random.Generator,
) -> tuple[str, bool, float]:
    """
    Return (outcome, success, relative total-energy drift).

    Outcomes are "ionized", "captured_projectile", "retained_target", and
    "ambiguous_bound". In the target-electron scheme, capture means the
    physically required E_ep <= 0 and E_et > 0. The inequality printed for
    capture in the paper's prose is reversed relative to the definitions of
    E_et and E_ep and would classify an electron retained by H2O as captured.
    """
    q = int(charge_state)
    if bound_to == "target":
        target_core = CorePotential.from_zn(
            WATER_PSEUDO_NUCLEAR_CHARGE, 9
        )
        projectile_core = CorePotential.from_zn(
            CARBON_NUCLEAR_CHARGE, CARBON_NUCLEAR_CHARGE - q
        )
    elif bound_to == "projectile":
        if q not in CARBON_OUTER_ORBITAL:
            return "retained_target", True, 0.0
        target_core = CorePotential.from_zn(
            WATER_PSEUDO_NUCLEAR_CHARGE, 10
        )
        # One projectile electron is active, so it is excluded from N.
        projectile_core = CorePotential.from_zn(
            CARBON_NUCLEAR_CHARGE, CARBON_NUCLEAR_CHARGE - q - 1
        )
    else:
        raise ValueError("bound_to must be 'target' or 'projectile'")

    separation = (
        automatic_start_separation_au(energy_keV_u)
        if config.start_separation_au is None
        else config.start_separation_au
    )
    initial_state = _build_initial_state(
        energy_keV_u=energy_keV_u,
        impact_parameter_au=impact_parameter_au,
        separation_au=separation,
        bound_to=bound_to,
        binding_eV=binding_eV,
        target_core=target_core,
        projectile_core=projectile_core,
        radial_grid_points=config.radial_grid_points,
        rng=rng,
    )
    velocity = projectile_velocity_au(energy_keV_u)
    end_time = 2.0 * separation / velocity
    initial_relative = _state_to_relative_coordinates(initial_state)
    initial_energy = relative_three_body_energy(
        initial_relative,
        target_core,
        projectile_core,
        config.minimum_radius_au,
    )

    if config.backend == "numba":
        if integrate_relative_dop853 is None:
            raise RuntimeError(
                "The Numba backend was requested but could not be imported"
            ) from _NUMBA_IMPORT_ERROR
        success, final_relative, _, _ = integrate_relative_dop853(
            initial_relative,
            end_time,
            _core_parameters(target_core),
            _core_parameters(projectile_core),
            config.rtol,
            config.atol,
            config.max_step_au,
            config.minimum_radius_au,
            WATER_MASS_AU,
            CARBON_MASS_AU,
            config.maximum_integration_steps,
        )
        if not success or not np.all(np.isfinite(final_relative)):
            return "integration_failure", False, math.inf
        final_state = _relative_to_state(final_relative)
    elif config.backend == "scipy":
        max_step = (
            np.inf if not np.isfinite(config.max_step_au)
            else config.max_step_au
        )
        solution = solve_ivp(
            _three_body_rhs,
            (0.0, end_time),
            initial_state,
            method="DOP853",
            t_eval=(end_time,),
            args=(target_core, projectile_core, config.minimum_radius_au),
            rtol=config.rtol,
            atol=config.atol,
            max_step=max_step,
        )
        if not solution.success or solution.y.shape[1] == 0:
            return "integration_failure", False, math.inf
        final_state = solution.y[:, -1]
        if not np.all(np.isfinite(final_state)):
            return "integration_failure", False, math.inf
        final_relative = _state_to_relative_coordinates(final_state)
    else:  # Defensive: CLI validation should make this unreachable.
        raise ValueError(f"Unknown CTMC backend: {config.backend!r}")

    final_energy = relative_three_body_energy(
        final_relative,
        target_core,
        projectile_core,
        config.minimum_radius_au,
    )
    energy_drift = abs(final_energy - initial_energy) / max(
        abs(initial_energy), 1.0
    )

    energy_target = _electron_core_energy(
        final_state,
        0,
        target_core,
        WATER_MASS_AU,
        config.minimum_radius_au,
    )
    energy_projectile = _electron_core_energy(
        final_state,
        1,
        projectile_core,
        CARBON_MASS_AU,
        config.minimum_radius_au,
    )

    if energy_target > 0.0 and energy_projectile > 0.0:
        outcome = "ionized"
    elif energy_projectile <= 0.0 and energy_target > 0.0:
        outcome = "captured_projectile"
    elif energy_target <= 0.0 and energy_projectile > 0.0:
        outcome = "retained_target"
    else:
        # At a converged final separation this should be negligible. Assign to
        # the more strongly bound center, while retaining a diagnostic label.
        if energy_projectile < energy_target:
            outcome = "captured_projectile"
        else:
            outcome = "ambiguous_bound"

    return outcome, True, float(energy_drift)


def _simulate_target_orbital(
    energy_keV_u: float,
    charge_state: int,
    impact_parameter_au: float,
    orbital: Orbital,
    config: CTMCConfig,
    rng: np.random.Generator,
) -> tuple[float, float, int, int, float]:
    ionized = 0
    captured = 0
    failures = 0
    successes = 0
    maximum_energy_drift = 0.0
    unreported_trajectories = 0
    for _ in range(config.trajectories):
        outcome, success, drift = simulate_one_trajectory(
            energy_keV_u=energy_keV_u,
            charge_state=charge_state,
            impact_parameter_au=impact_parameter_au,
            bound_to="target",
            binding_eV=orbital.binding_eV,
            config=config,
            rng=rng,
        )
        unreported_trajectories += 1
        if unreported_trajectories >= _WORKER_PROGRESS_INTERVAL:
            _advance_worker_progress(unreported_trajectories)
            unreported_trajectories = 0
        if not success:
            failures += 1
            continue
        successes += 1
        maximum_energy_drift = max(maximum_energy_drift, drift)
        ionized += int(outcome == "ionized")
        captured += int(outcome == "captured_projectile")
    _advance_worker_progress(unreported_trajectories)

    if successes == 0:
        raise RuntimeError(
            "All target-electron trajectories failed for "
            f"E={energy_keV_u:g} keV/u, q={charge_state}, "
            f"b={impact_parameter_au:g} a.u., orbital={orbital.label}"
        )
    return (
        ionized / successes,
        captured / successes,
        failures,
        successes,
        maximum_energy_drift,
    )


def _simulate_projectile_loss(
    energy_keV_u: float,
    charge_state: int,
    impact_parameter_au: float,
    config: CTMCConfig,
    rng: np.random.Generator,
) -> tuple[float, int, int, float]:
    orbital = CARBON_OUTER_ORBITAL.get(int(charge_state))
    if orbital is None:
        return 0.0, 0, 0, 0.0

    lost = 0
    failures = 0
    successes = 0
    maximum_energy_drift = 0.0
    unreported_trajectories = 0
    for _ in range(config.trajectories):
        outcome, success, drift = simulate_one_trajectory(
            energy_keV_u=energy_keV_u,
            charge_state=charge_state,
            impact_parameter_au=impact_parameter_au,
            bound_to="projectile",
            binding_eV=orbital.binding_eV,
            config=config,
            rng=rng,
        )
        unreported_trajectories += 1
        if unreported_trajectories >= _WORKER_PROGRESS_INTERVAL:
            _advance_worker_progress(unreported_trajectories)
            unreported_trajectories = 0
        if not success:
            failures += 1
            continue
        successes += 1
        maximum_energy_drift = max(maximum_energy_drift, drift)
        # Equation (paper prose below eq. 3): projectile ionization requires
        # the electron to be unbound from both centers.
        lost += int(outcome == "ionized")
    _advance_worker_progress(unreported_trajectories)

    if successes == 0:
        raise RuntimeError(
            "All projectile-electron trajectories failed for "
            f"E={energy_keV_u:g} keV/u, q={charge_state}, "
            f"b={impact_parameter_au:g} a.u."
        )
    return (
        lost / successes,
        failures,
        successes,
        maximum_energy_drift,
    )


# ---------------------------------------------------------------------------
# Parallel worker: one (energy, charge, impact parameter) point
# ---------------------------------------------------------------------------


def _init_worker(
    config: CTMCConfig,
    progress_counter=None,
    progress_interval: int = CARBON_CTMC_PROGRESS_INTERVAL,
) -> None:
    global _WORKER_CONFIG, _WORKER_PROGRESS_COUNTER
    global _WORKER_PROGRESS_INTERVAL
    _WORKER_CONFIG = config
    _WORKER_PROGRESS_COUNTER = progress_counter
    _WORKER_PROGRESS_INTERVAL = max(int(progress_interval), 1)


def _advance_worker_progress(trajectories: int) -> None:
    if trajectories <= 0 or _WORKER_PROGRESS_COUNTER is None:
        return
    with _WORKER_PROGRESS_COUNTER.get_lock():
        _WORKER_PROGRESS_COUNTER.value += int(trajectories)


def _seed_for_task(
    master_seed: int,
    energy_index: int,
    charge_state: int,
    impact_index: int,
) -> np.random.SeedSequence:
    return np.random.SeedSequence(
        [int(master_seed), int(energy_index), int(charge_state), int(impact_index)]
    )


def _compute_probability_point(
    task: tuple[int, int, float, int, int, float]
) -> tuple[int, int, int, np.ndarray, np.ndarray, float, int, int, float]:
    energy_index, charge_index, energy, charge, impact_index, impact = task
    if _WORKER_CONFIG is None:
        raise RuntimeError("Worker CTMC configuration was not initialized")
    config = _WORKER_CONFIG
    rng = np.random.default_rng(
        _seed_for_task(config.seed, energy_index, charge, impact_index)
    )

    pi = np.zeros(len(WATER_ORBITALS), dtype=float)
    pc = np.zeros(len(WATER_ORBITALS), dtype=float)
    failures = 0
    successes = 0
    maximum_energy_drift = 0.0

    for orbital_index, orbital in enumerate(WATER_ORBITALS):
        if impact > config.target_bmax_au[orbital_index]:
            continue
        result = _simulate_target_orbital(
            energy,
            charge,
            impact,
            orbital,
            config,
            rng,
        )
        pi[orbital_index], pc[orbital_index] = result[:2]
        failures += result[2]
        successes += result[3]
        maximum_energy_drift = max(maximum_energy_drift, result[4])

    pl = 0.0
    if charge <= 5 and impact <= config.loss_bmax_au:
        loss_result = _simulate_projectile_loss(
            energy,
            charge,
            impact,
            config,
            rng,
        )
        pl = loss_result[0]
        failures += loss_result[1]
        successes += loss_result[2]
        maximum_energy_drift = max(
            maximum_energy_drift, loss_result[3]
        )

    attempted = failures + successes
    if attempted and failures / attempted > config.max_failure_fraction:
        raise RuntimeError(
            f"Trajectory failure fraction {failures / attempted:.3%} exceeds "
            f"limit {config.max_failure_fraction:.3%} at "
            f"E={energy:g} keV/u, q={charge}, b={impact:g} a.u."
        )

    return (
        energy_index,
        charge_index,
        impact_index,
        pi,
        pc,
        pl,
        failures,
        successes,
        maximum_energy_drift,
    )


# ---------------------------------------------------------------------------
# IEVM/IPM probabilities and cross sections, equations (13)-(20)
# ---------------------------------------------------------------------------


def _ipm_exact_one_capture_and_transfer_ionization(
    pi: np.ndarray, pc: np.ndarray
) -> tuple[np.ndarray, np.ndarray]:
    """
    IPM probabilities for exactly one capture and for one capture plus one
    target ionization. All remaining target electrons undergo no removal.
    """
    n_impact = pi.shape[0]
    distribution = np.zeros((2, 2, n_impact), dtype=float)
    distribution[0, 0, :] = 1.0

    for shell_index, orbital in enumerate(WATER_ORBITALS):
        pn = np.clip(
            1.0 - pi[:, shell_index] - pc[:, shell_index],
            0.0,
            1.0,
        )
        for _ in range(orbital.active_electrons):
            updated = np.zeros_like(distribution)
            updated[0, 0] += distribution[0, 0] * pn
            updated[1, 0] += distribution[1, 0] * pn
            updated[0, 1] += distribution[0, 1] * pn
            updated[1, 1] += distribution[1, 1] * pn

            updated[1, 0] += distribution[0, 0] * pc[:, shell_index]
            updated[1, 1] += distribution[0, 1] * pc[:, shell_index]

            updated[0, 1] += distribution[0, 0] * pi[:, shell_index]
            updated[1, 1] += distribution[1, 0] * pi[:, shell_index]
            distribution = updated

    return distribution[1, 0], distribution[1, 1]


def many_electron_probabilities(
    pi: np.ndarray,
    pc: np.ndarray,
    pl: np.ndarray,
    charge_state: int,
) -> dict[str, np.ndarray]:
    if pi.shape != pc.shape or pi.ndim != 2:
        raise ValueError("pi and pc must have shape (n_impact, n_orbitals)")
    if pi.shape[1] != len(WATER_ORBITALS):
        raise ValueError("Unexpected number of water orbitals")
    if pl.shape != (pi.shape[0],):
        raise ValueError("pl must have shape (n_impact,)")

    pn = np.clip(1.0 - pi - pc, 0.0, 1.0)

    # Modified IEVM, equations (13) and (14), with NL=2 for every H2O
    # orbital and c=2 for pure double target ionization.
    si = np.zeros(pi.shape[0], dtype=float)
    di = np.zeros(pi.shape[0], dtype=float)
    for shell_index, orbital in enumerate(WATER_ORBITALS):
        nl = orbital.active_electrons
        si += nl * pi[:, shell_index] * pn[:, shell_index] ** (nl - 1)
        if nl >= 2:
            di += (
                0.5
                * nl
                * (nl - 1)
                * pi[:, shell_index] ** 2
                * pn[:, shell_index] ** (nl - 2)
            )

    sc, ti = _ipm_exact_one_capture_and_transfer_ionization(pi, pc)
    if charge_state == 0:
        sc.fill(0.0)
        ti.fill(0.0)

    projectile_orbital = CARBON_OUTER_ORBITAL.get(int(charge_state))
    if projectile_orbital is None:
        sl = np.zeros_like(pl)
    else:
        nl = projectile_orbital.active_electrons
        sl = nl * pl * np.clip(1.0 - pl, 0.0, 1.0) ** (nl - 1)

    li = si * sl
    if charge_state == 6:
        sl.fill(0.0)
        li.fill(0.0)

    channels = {
        "SI": si,
        "DI": di,
        "SC": sc,
        "TI": ti,
        "SL": sl,
        "LI": li,
    }
    for name, values in channels.items():
        if not np.all(np.isfinite(values)) or np.any(values < -1.0e-12):
            raise RuntimeError(f"Invalid {name} many-electron channel weight")
        # The modified IEVM sums shell-local removal terms (paper eqs. 13-14)
        # without the other-shell survival products present in the IPM. Its
        # channel weights can consequently exceed one at very small b. Do not
        # clip them: clipping would silently replace the published model by an
        # ad-hoc unitarization. SC and TI, evaluated with the IPM, remain
        # normalized probabilities.
        channels[name] = np.maximum(values, 0.0)

    channels["decrease"] = channels["SC"] + channels["TI"]
    channels["increase"] = channels["SL"] + channels["LI"]
    return channels


def integrate_impact_parameter(
    impact_au: np.ndarray, probability: np.ndarray
) -> float:
    sigma_bohr2 = 2.0 * math.pi * np.trapezoid(
        impact_au * probability, impact_au
    )
    return float(max(sigma_bohr2, 0.0) * BOHR2_CM2)


def build_cross_section_rows(
    energies: np.ndarray,
    charges: np.ndarray,
    impact_au: np.ndarray,
    pi: np.ndarray,
    pc: np.ndarray,
    pl: np.ndarray,
) -> tuple[np.ndarray, list[str]]:
    columns = [
        "E_keV_u",
        "q",
        "sigma_SC_cm2",
        "sigma_TI_cm2",
        "sigma_SL_cm2",
        "sigma_LI_cm2",
        "sigma_decrease_cm2",
        "sigma_increase_cm2",
        "sigma_SI_cm2",
        "sigma_DI_cm2",
    ]
    rows: list[list[float]] = []
    for energy_index, energy in enumerate(energies):
        for charge_index, charge in enumerate(charges):
            probabilities = many_electron_probabilities(
                pi[energy_index, charge_index],
                pc[energy_index, charge_index],
                pl[energy_index, charge_index],
                int(charge),
            )
            cross_sections = {
                name: integrate_impact_parameter(impact_au, values)
                for name, values in probabilities.items()
            }
            rows.append(
                [
                    float(energy),
                    float(charge),
                    cross_sections["SC"],
                    cross_sections["TI"],
                    cross_sections["SL"],
                    cross_sections["LI"],
                    cross_sections["decrease"],
                    cross_sections["increase"],
                    cross_sections["SI"],
                    cross_sections["DI"],
                ]
            )
    return np.asarray(rows, dtype=float), columns


# ---------------------------------------------------------------------------
# Grids, checkpointing, and output
# ---------------------------------------------------------------------------


def parse_float_list(text: str) -> np.ndarray:
    values = [float(item.strip()) for item in text.split(",") if item.strip()]
    if not values:
        raise argparse.ArgumentTypeError("Expected at least one numeric value")
    values = sorted(set(values))
    if values[0] <= 0.0:
        raise argparse.ArgumentTypeError("Energies must be positive")
    return np.asarray(values, dtype=float)


def parse_charges(text: str, charge_step: int) -> np.ndarray:
    cleaned = text.strip()
    if ":" in cleaned:
        parts = [part.strip() for part in cleaned.split(":")]
        if len(parts) != 2:
            raise ValueError("Charge range must have form qmin:qmax")
        qmin, qmax = map(int, parts)
        charges = np.arange(qmin, qmax + 1, charge_step, dtype=int)
    else:
        charges = np.asarray(
            sorted(set(int(part.strip()) for part in cleaned.split(",") if part.strip())),
            dtype=int,
        )
    if charges.size == 0:
        raise ValueError("No charge states selected")
    if np.any((charges < 0) | (charges > 6)):
        raise ValueError("Carbon charge states must lie in 0,...,6")
    return charges


def build_energy_grid(args: argparse.Namespace) -> np.ndarray:
    if args.energies is not None:
        return parse_float_list(args.energies)
    if args.energy_step_kev_u is not None:
        step = float(args.energy_step_kev_u)
        if step <= 0.0:
            raise ValueError("--energy-step-kev-u must be positive")
        count = int(
            math.floor(
                (args.energy_max_kev_u - args.energy_min_kev_u) / step
            )
        )
        grid = args.energy_min_kev_u + step * np.arange(count + 1)
        if grid[-1] < args.energy_max_kev_u * (1.0 - 1.0e-12):
            grid = np.append(grid, args.energy_max_kev_u)
        return np.asarray(grid, dtype=float)
    if args.energy_points < 2:
        raise ValueError("--energy-points must be at least two")
    if args.energy_spacing == "linear":
        return np.linspace(
            args.energy_min_kev_u,
            args.energy_max_kev_u,
            args.energy_points,
        )
    return np.geomspace(
        args.energy_min_kev_u,
        args.energy_max_kev_u,
        args.energy_points,
    )


def configuration_signature(
    energies: np.ndarray,
    charges: np.ndarray,
    impact_au: np.ndarray,
    config: CTMCConfig,
) -> str:
    config_payload = asdict(config)
    if not np.isfinite(config_payload["max_step_au"]):
        config_payload["max_step_au"] = None
    payload = {
        "energies": energies.tolist(),
        "charges": charges.tolist(),
        "impact_au": impact_au.tolist(),
        "config": config_payload,
        "model_version": 1,
    }
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(encoded).hexdigest()


def save_checkpoint(
    path: Path,
    *,
    signature: str,
    energies: np.ndarray,
    charges: np.ndarray,
    impact_au: np.ndarray,
    pi: np.ndarray,
    pc: np.ndarray,
    pl: np.ndarray,
    done: np.ndarray,
    failures: np.ndarray,
    successes: np.ndarray,
    maximum_energy_drift: np.ndarray,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(".tmp.npz")
    np.savez_compressed(
        temporary,
        signature=np.asarray(signature),
        energies_keV_u=energies,
        charges=charges,
        impact_au=impact_au,
        pi=pi,
        pc=pc,
        pl=pl,
        done=done,
        failures=failures,
        successes=successes,
        maximum_energy_drift=maximum_energy_drift,
    )
    os.replace(temporary, path)


def load_checkpoint(
    path: Path,
    expected_signature: str,
) -> dict[str, np.ndarray] | None:
    if not path.exists():
        return None
    with np.load(path, allow_pickle=False) as data:
        signature = str(np.asarray(data["signature"]).item())
        if signature != expected_signature:
            raise RuntimeError(
                f"Checkpoint {path} belongs to a different configuration. "
                "Use a new output directory or remove the checkpoint."
            )
        return {key: np.asarray(data[key]) for key in data.files}


def write_outputs(
    output_dir: Path,
    *,
    energies: np.ndarray,
    charges: np.ndarray,
    impact_au: np.ndarray,
    pi: np.ndarray,
    pc: np.ndarray,
    pl: np.ndarray,
    failures: np.ndarray,
    successes: np.ndarray,
    maximum_energy_drift: np.ndarray,
    config: CTMCConfig,
    workers: int,
    signature: str,
) -> tuple[Path, Path, Path, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    rows, columns = build_cross_section_rows(
        energies, charges, impact_au, pi, pc, pl
    )

    dat_path = output_dir / "carbon_charge_exchange_h2o.dat"
    csv_path = output_dir / "carbon_charge_exchange_h2o.csv"
    probabilities_path = (
        output_dir / "carbon_charge_exchange_probabilities.npz"
    )
    metadata_path = output_dir / "carbon_charge_exchange_metadata.json"

    dat_header = (
        " ".join(columns)
        + "\nMicroscopic cross sections in cm2 per H2O molecule; "
        "E is projectile energy in keV/u."
    )
    np.savetxt(
        dat_path,
        rows,
        fmt=["%.9E", "%.0f"] + ["%.9E"] * (rows.shape[1] - 2),
        header=dat_header,
        comments="# ",
    )
    np.savetxt(
        csv_path,
        rows,
        delimiter=",",
        fmt=["%.9E", "%.0f"] + ["%.9E"] * (rows.shape[1] - 2),
        header=",".join(columns),
        comments="",
    )
    np.savez_compressed(
        probabilities_path,
        energies_keV_u=energies,
        charges=charges,
        impact_au=impact_au,
        orbital_labels=np.asarray([o.label for o in WATER_ORBITALS]),
        pi=pi,
        pc=pc,
        pl=pl,
        failures=failures,
        successes=successes,
        maximum_energy_drift=maximum_energy_drift,
    )

    attempted = int(np.sum(failures) + np.sum(successes))
    config_metadata = asdict(config)
    if not np.isfinite(config_metadata["max_step_au"]):
        config_metadata["max_step_au"] = None
    metadata = {
        "model": "Liamsuwan-Nikjoo three-body CTMC with IEVM/IPM",
        "doi": "10.1088/0031-9155/58/3/641",
        "target": "isolated spherical H2O pseudotarget",
        "density_applied": False,
        "cross_section_unit": "cm2 per H2O molecule",
        "energy_unit": "keV/u",
        "charge_states": charges.tolist(),
        "configuration_signature": signature,
        "workers": int(workers),
        "ctmc_config": config_metadata,
        "water_orbitals": [asdict(orbital) for orbital in WATER_ORBITALS],
        "carbon_outer_orbitals": {
            str(q): asdict(orbital)
            for q, orbital in CARBON_OUTER_ORBITAL.items()
        },
        "trajectory_statistics": {
            "attempted": attempted,
            "successful": int(np.sum(successes)),
            "failed": int(np.sum(failures)),
            "failure_fraction": (
                float(np.sum(failures) / attempted) if attempted else 0.0
            ),
            "maximum_relative_total_energy_drift": float(
                np.max(maximum_energy_drift)
            ),
        },
        "notes": [
            "q is discrete carbon charge, not dielectric momentum transfer.",
            "No ELF or condensed-phase correction is used.",
            "Ice density must be applied in Geant4 as n_H2O*sigma.",
            "The paper does not tabulate exact per-orbital bmax values; "
            "the conservative default uses 25 a.u. for every H2O orbital.",
            "The automatic initial separation smoothly spans the paper's "
            "stated 10000-to-1000 a.u. range and must be convergence-tested.",
            "The capture inequality in the paper prose is reversed relative "
            "to its E_et/E_ep definitions; this code uses the physical "
            "projectile-bound condition E_ep<=0 and E_et>0.",
            "Modified-IEVM shell sums are retained exactly as published and "
            "are not ad-hoc clipped if their approximate channel weights "
            "exceed one at very small impact parameter.",
        ],
    }
    metadata_path.write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return dat_path, csv_path, probabilities_path, metadata_path


def iter_pending_probability_tasks(
    energies: np.ndarray,
    charges: np.ndarray,
    impact_au: np.ndarray,
    done: np.ndarray,
) -> Iterable[tuple[int, int, float, int, int, float]]:
    """Yield unfinished points fast-energy-first without materializing a list."""
    # High-energy trajectories have shorter physical time intervals. Completing
    # them first produces early checkpoints without changing any task seed or
    # the final table ordering.
    for energy_index in range(energies.size - 1, -1, -1):
        energy = energies[energy_index]
        for charge_index, charge in enumerate(charges):
            for impact_index, impact in enumerate(impact_au):
                if not done[energy_index, charge_index, impact_index]:
                    yield (
                        energy_index,
                        charge_index,
                        float(energy),
                        int(charge),
                        impact_index,
                        float(impact),
                    )


def estimate_trajectory_count(
    tasks: Iterable[tuple[int, int, float, int, int, float]],
    config: CTMCConfig,
) -> int:
    count = 0
    for _, _, _, charge, _, impact in tasks:
        active_target_shells = sum(
            impact <= bmax for bmax in config.target_bmax_au
        )
        loss_active = charge <= 5 and impact <= config.loss_bmax_au
        count += config.trajectories * (
            active_target_shells + int(loss_active)
        )
    return int(count)


def bounded_parallel_results(
    executor: ProcessPoolExecutor,
    tasks: Iterable[tuple[int, int, float, int, int, float]],
    maximum_pending: int,
) -> Iterable[
    tuple[int, int, int, np.ndarray, np.ndarray, float, int, int, float]
]:
    """Submit a bounded number of futures instead of all grid points at once."""
    task_iterator = iter(tasks)
    pending = set()
    for _ in range(maximum_pending):
        try:
            task = next(task_iterator)
        except StopIteration:
            break
        pending.add(executor.submit(_compute_probability_point, task))

    while pending:
        completed, pending = wait(pending, return_when=FIRST_COMPLETED)
        for future in completed:
            yield future.result()
            try:
                task = next(task_iterator)
            except StopIteration:
                continue
            pending.add(executor.submit(_compute_probability_point, task))


def parse_target_bmax(text: str) -> tuple[float, ...]:
    values = tuple(
        float(part.strip()) for part in text.split(",") if part.strip()
    )
    if len(values) == 1:
        values = values * len(WATER_ORBITALS)
    if len(values) != len(WATER_ORBITALS):
        raise ValueError(
            "--target-bmax-au requires one value or five comma-separated "
            "values ordered as 1b1,3a1,1b2,2a1,1a1"
        )
    if any(value <= 0.0 for value in values):
        raise ValueError("All target bmax values must be positive")
    return values


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate charge-state-resolved C(q+)+H2O CTMC cross sections "
            "for Geant4."
        )
    )
    parser.add_argument(
        "--energy-min-kev-u",
        type=float,
        default=CARBON_CTMC_ENERGY_MIN_KEV_U,
    )
    parser.add_argument(
        "--energy-max-kev-u",
        type=float,
        default=CARBON_CTMC_ENERGY_MAX_KEV_U,
    )
    parser.add_argument(
        "--energy-points",
        "--nE",
        type=int,
        default=CARBON_CTMC_ENERGY_POINTS,
        help="Number of projectile-energy points (default: %(default)s).",
    )
    parser.add_argument(
        "--energy-spacing",
        choices=("log", "linear"),
        default=CARBON_CTMC_ENERGY_SPACING,
    )
    parser.add_argument(
        "--energy-step-kev-u",
        type=float,
        default=None,
        help=(
            "Optional linear projectile-energy step; overrides "
            "--energy-points. This is not an ELF energy-loss bin."
        ),
    )
    parser.add_argument(
        "--energies",
        type=str,
        default=None,
        help="Explicit comma-separated energies in keV/u; overrides the grid.",
    )
    parser.add_argument(
        "--charges",
        type=str,
        default=CARBON_CTMC_CHARGES,
        help="Charge range qmin:qmax or comma-separated values.",
    )
    parser.add_argument(
        "--charge-step",
        type=int,
        default=CARBON_CTMC_CHARGE_STEP,
        help=(
            "Discrete carbon charge-state step (physical default: 1); "
            "this is not a momentum-transfer dq."
        ),
    )
    parser.add_argument(
        "--impact-points",
        "--nb",
        type=int,
        default=CARBON_CTMC_IMPACT_POINTS,
        help="Uniform impact-parameter grid size.",
    )
    parser.add_argument(
        "--target-bmax-au",
        type=str,
        default=str(CARBON_CTMC_TARGET_BMAX_AU),
        help="One bmax or five orbital-specific bmax values in atomic units.",
    )
    parser.add_argument(
        "--loss-bmax-au",
        type=float,
        default=CARBON_CTMC_LOSS_BMAX_AU,
    )
    parser.add_argument(
        "--trajectories",
        type=int,
        default=CARBON_CTMC_TRAJECTORIES,
        help="Trajectories per orbital and impact point.",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=CARBON_CTMC_WORKERS,
        help="Process workers (default: %(default)s).",
    )
    parser.add_argument(
        "--backend",
        choices=("numba", "scipy"),
        default=CARBON_CTMC_BACKEND,
        help=(
            "Trajectory backend: compiled relative-coordinate DOP853 "
            "(numba) or the full-coordinate SciPy reference."
        ),
    )
    parser.add_argument(
        "--progress-interval",
        type=int,
        default=CARBON_CTMC_PROGRESS_INTERVAL,
        help=(
            "Worker trajectory count between shared tqdm updates "
            "(default: %(default)s)."
        ),
    )
    parser.add_argument(
        "--radial-grid-points",
        type=int,
        default=CARBON_CTMC_RADIAL_GRID_POINTS,
    )
    parser.add_argument(
        "--start-separation-au",
        type=float,
        default=None,
        help=(
            "Initial core separation. Default follows the paper's stated "
            "10000-to-1000 a.u. range as a smooth function of energy."
        ),
    )
    parser.add_argument("--rtol", type=float, default=1.0e-8)
    parser.add_argument("--atol", type=float, default=1.0e-10)
    parser.add_argument(
        "--max-step-au",
        type=float,
        default=math.inf,
        help="Maximum DOP853 time step; default lets the solver adapt freely.",
    )
    parser.add_argument(
        "--maximum-integration-steps",
        type=int,
        default=CARBON_CTMC_MAXIMUM_INTEGRATION_STEPS,
        help="Safety limit on accepted plus rejected DOP853 steps.",
    )
    parser.add_argument(
        "--minimum-radius-au",
        type=float,
        default=1.0e-10,
        help="Numerical division floor, not a softened physical potential.",
    )
    parser.add_argument(
        "--max-failure-fraction",
        type=float,
        default=0.01,
    )
    parser.add_argument("--seed", type=int, default=CARBON_CTMC_SEED)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=CARBON_CHARGE_EXCHANGE_DIR,
    )
    parser.add_argument(
        "--checkpoint-every",
        type=int,
        default=10,
        help="Save restart data after this many completed grid points.",
    )
    parser.add_argument(
        "--no-resume",
        action="store_true",
        help="Ignore an existing matching checkpoint.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print grid and trajectory count without integrating.",
    )
    return parser


def validate_args(args: argparse.Namespace) -> None:
    if args.energy_min_kev_u <= 0.0:
        raise ValueError("--energy-min-kev-u must be positive")
    if args.energy_max_kev_u <= args.energy_min_kev_u:
        raise ValueError("--energy-max-kev-u must exceed the minimum")
    if args.charge_step < 1:
        raise ValueError("--charge-step must be a positive integer")
    if args.impact_points < 2:
        raise ValueError("--impact-points must be at least two")
    if args.trajectories < 1:
        raise ValueError("--trajectories must be positive")
    if args.workers < 1:
        raise ValueError("--workers must be positive")
    if args.backend == "numba" and integrate_relative_dop853 is None:
        raise ValueError(
            "The Numba backend is unavailable: "
            f"{_NUMBA_IMPORT_ERROR!s}. Use --backend scipy or install numba."
        )
    if args.maximum_integration_steps < 1:
        raise ValueError("--maximum-integration-steps must be positive")
    if args.progress_interval < 1:
        raise ValueError("--progress-interval must be positive")
    if args.radial_grid_points < 128:
        raise ValueError("--radial-grid-points must be at least 128")
    if args.loss_bmax_au <= 0.0:
        raise ValueError("--loss-bmax-au must be positive")
    if args.start_separation_au is not None and args.start_separation_au <= 0:
        raise ValueError("--start-separation-au must be positive")
    if args.rtol <= 0.0 or args.atol <= 0.0:
        raise ValueError("Integrator tolerances must be positive")
    if args.minimum_radius_au <= 0.0:
        raise ValueError("--minimum-radius-au must be positive")
    if not (0.0 <= args.max_failure_fraction < 1.0):
        raise ValueError("--max-failure-fraction must lie in [0,1)")
    if args.checkpoint_every < 1:
        raise ValueError("--checkpoint-every must be positive")


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        validate_args(args)
        energies = build_energy_grid(args)
        charges = parse_charges(args.charges, args.charge_step)
        target_bmax = parse_target_bmax(args.target_bmax_au)
    except ValueError as exc:
        parser.error(str(exc))

    maximum_b = max(max(target_bmax), args.loss_bmax_au)
    impact_au = np.linspace(0.0, maximum_b, args.impact_points)
    config = CTMCConfig(
        backend=str(args.backend),
        trajectories=int(args.trajectories),
        target_bmax_au=target_bmax,
        loss_bmax_au=float(args.loss_bmax_au),
        radial_grid_points=int(args.radial_grid_points),
        start_separation_au=(
            None
            if args.start_separation_au is None
            else float(args.start_separation_au)
        ),
        rtol=float(args.rtol),
        atol=float(args.atol),
        max_step_au=float(args.max_step_au),
        minimum_radius_au=float(args.minimum_radius_au),
        max_failure_fraction=float(args.max_failure_fraction),
        maximum_integration_steps=int(args.maximum_integration_steps),
        seed=int(args.seed),
    )

    shape = (energies.size, charges.size, impact_au.size)
    pi = np.full(shape + (len(WATER_ORBITALS),), np.nan, dtype=float)
    pc = np.full_like(pi, np.nan)
    pl = np.full(shape, np.nan, dtype=float)
    done = np.zeros(shape, dtype=bool)
    failures = np.zeros(shape, dtype=np.int64)
    successes = np.zeros(shape, dtype=np.int64)
    maximum_energy_drift = np.zeros(shape, dtype=float)

    signature = configuration_signature(
        energies, charges, impact_au, config
    )
    checkpoint_path = (
        args.output_dir / "carbon_charge_exchange_ctmc_checkpoint.npz"
    )
    if not args.no_resume:
        checkpoint = load_checkpoint(checkpoint_path, signature)
        if checkpoint is not None:
            pi[...] = checkpoint["pi"]
            pc[...] = checkpoint["pc"]
            pl[...] = checkpoint["pl"]
            done[...] = checkpoint["done"]
            failures[...] = checkpoint["failures"]
            successes[...] = checkpoint["successes"]
            maximum_energy_drift[...] = checkpoint["maximum_energy_drift"]
            print(
                f"Resumed {int(np.sum(done))}/{done.size} probability points "
                f"from {checkpoint_path}"
            )

    pending_points = int(done.size - np.count_nonzero(done))
    estimated = estimate_trajectory_count(
        iter_pending_probability_tasks(energies, charges, impact_au, done),
        config,
    )
    print(
        f"Grid: {energies.size} energies x {charges.size} charge states x "
        f"{impact_au.size} impact parameters"
    )
    print(
        f"Pending probability points: {pending_points:,}; "
        f"estimated trajectories: {estimated:,}"
    )
    print(f"Backend: {config.backend}; workers: {args.workers}")
    if args.dry_run:
        return 0

    if config.backend == "numba":
        assert warm_up_numba_backend is not None
        print("Compiling/loading the Numba DOP853 kernel...")
        warm_up_numba_backend()

    def store_result(
        result: tuple[
            int, int, int, np.ndarray, np.ndarray, float, int, int, float
        ]
    ) -> None:
        (
            energy_index,
            charge_index,
            impact_index,
            point_pi,
            point_pc,
            point_pl,
            point_failures,
            point_successes,
            point_maximum_drift,
        ) = result
        pi[energy_index, charge_index, impact_index] = point_pi
        pc[energy_index, charge_index, impact_index] = point_pc
        pl[energy_index, charge_index, impact_index] = point_pl
        failures[energy_index, charge_index, impact_index] = point_failures
        successes[energy_index, charge_index, impact_index] = point_successes
        maximum_energy_drift[
            energy_index, charge_index, impact_index
        ] = point_maximum_drift
        done[energy_index, charge_index, impact_index] = True

    process_context = multiprocessing.get_context()
    trajectory_counter = process_context.Value("Q", 0)
    stop_progress = threading.Event()
    trajectory_progress = tqdm(
        total=estimated,
        desc="Trajectories",
        unit="traj",
        unit_scale=True,
        dynamic_ncols=True,
        position=0,
    )
    point_progress = tqdm(
        total=pending_points,
        desc="Grid points",
        unit="point",
        dynamic_ncols=True,
        position=1,
    )

    def monitor_trajectory_progress() -> None:
        displayed = 0
        while not stop_progress.wait(0.5):
            with trajectory_counter.get_lock():
                completed = int(trajectory_counter.value)
            if completed > displayed:
                trajectory_progress.update(completed - displayed)
                displayed = completed
        with trajectory_counter.get_lock():
            completed = int(trajectory_counter.value)
        if completed > displayed:
            trajectory_progress.update(completed - displayed)

    progress_thread = threading.Thread(
        target=monitor_trajectory_progress,
        name="ctmc-tqdm-monitor",
        daemon=True,
    )
    progress_thread.start()

    completed_since_checkpoint = 0
    try:
        try:
            if args.workers == 1:
                _init_worker(
                    config,
                    trajectory_counter,
                    args.progress_interval,
                )
                iterator: Iterable[
                    tuple[
                        int,
                        int,
                        int,
                        np.ndarray,
                        np.ndarray,
                        float,
                        int,
                        int,
                        float,
                    ]
                ] = map(
                    _compute_probability_point,
                    iter_pending_probability_tasks(
                        energies, charges, impact_au, done
                    ),
                )
                for result in iterator:
                    store_result(result)
                    point_progress.update(1)
                    completed_since_checkpoint += 1
                    if completed_since_checkpoint >= args.checkpoint_every:
                        save_checkpoint(
                            checkpoint_path,
                            signature=signature,
                            energies=energies,
                            charges=charges,
                            impact_au=impact_au,
                            pi=pi,
                            pc=pc,
                            pl=pl,
                            done=done,
                            failures=failures,
                            successes=successes,
                            maximum_energy_drift=maximum_energy_drift,
                        )
                        completed_since_checkpoint = 0
            else:
                with ProcessPoolExecutor(
                    max_workers=args.workers,
                    initializer=_init_worker,
                    initargs=(
                        config,
                        trajectory_counter,
                        args.progress_interval,
                    ),
                    mp_context=process_context,
                ) as executor:
                    results = bounded_parallel_results(
                        executor,
                        iter_pending_probability_tasks(
                            energies, charges, impact_au, done
                        ),
                        maximum_pending=max(2 * args.workers, 1),
                    )
                    for result in results:
                        store_result(result)
                        point_progress.update(1)
                        completed_since_checkpoint += 1
                        if (
                            completed_since_checkpoint
                            >= args.checkpoint_every
                        ):
                            save_checkpoint(
                                checkpoint_path,
                                signature=signature,
                                energies=energies,
                                charges=charges,
                                impact_au=impact_au,
                                pi=pi,
                                pc=pc,
                                pl=pl,
                                done=done,
                                failures=failures,
                                successes=successes,
                                maximum_energy_drift=maximum_energy_drift,
                            )
                            completed_since_checkpoint = 0
        finally:
            if np.any(done):
                save_checkpoint(
                    checkpoint_path,
                    signature=signature,
                    energies=energies,
                    charges=charges,
                    impact_au=impact_au,
                    pi=pi,
                    pc=pc,
                    pl=pl,
                    done=done,
                    failures=failures,
                    successes=successes,
                    maximum_energy_drift=maximum_energy_drift,
                )
    finally:
        stop_progress.set()
        progress_thread.join()
        point_progress.close()
        trajectory_progress.close()

    if not np.all(done):
        raise RuntimeError("CTMC grid is incomplete; checkpoint was preserved")

    paths = write_outputs(
        args.output_dir,
        energies=energies,
        charges=charges,
        impact_au=impact_au,
        pi=pi,
        pc=pc,
        pl=pl,
        failures=failures,
        successes=successes,
        maximum_energy_drift=maximum_energy_drift,
        config=config,
        workers=args.workers,
        signature=signature,
    )
    print("Wrote:")
    for path in paths:
        print(f"  {path}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("\nInterrupted; the CTMC checkpoint was preserved.", file=sys.stderr)
        raise SystemExit(130)
