"""Binary-collision building blocks for phase-resolved ion--ice scattering."""

from .config import (
    DEFAULT_AXIS_RELATIVE_TOLERANCE,
    DEFAULT_BASE_ENERGY_POINTS,
    DEFAULT_ENERGY_MAX_EV,
    DEFAULT_ENERGY_MIN_EV,
    DEFAULT_MAX_ENERGY_POINTS,
    DEFAULT_MAX_IMPACT_POINTS,
    DEFAULT_MINIMUM_TURNING_POTENTIAL_EV,
    DEFAULT_PROJECTILES,
    DEFAULT_QUADRATURE_ORDER,
    DEFAULT_WORKERS,
)
from .convergence import (
    DEFAULT_MAXIMUM_TRAJECTORIES,
    DEFAULT_MINIMUM_TRAJECTORIES,
    DEFAULT_STATISTICAL_CONFIDENCE,
    DEFAULT_STATISTICAL_RELATIVE_TOLERANCE,
    DEFAULT_TRAJECTORY_BATCH_SIZE,
    OBSERVABLES,
    RatioStatistics,
    convergence_report,
    doubling_schedule,
)
from .scattering import (
    CollisionResult,
    NLHCollisionKernel,
    PairKinematics,
    TwoBodyOutcome,
    hard_cross_section_angstrom2,
    maximum_impact_parameter_angstrom,
    pair_kinematics,
    solve_nlh_collision,
    two_body_outcome_from_cm_angle,
    two_body_observables_from_cm_angles,
    turning_threshold_radius_angstrom,
)
from .runtime import (
    AdaptiveKernelTable,
    KernelTableError,
    RuntimeCollision,
)
from .structure import IceStructure, StructureValidationError, load_ice_structure
from .trajectory import (
    HardCollisionEvent,
    HardTrajectoryResult,
    PeriodicHardCollisionTransport,
)

__all__ = [
    "CollisionResult",
    "DEFAULT_AXIS_RELATIVE_TOLERANCE",
    "DEFAULT_BASE_ENERGY_POINTS",
    "DEFAULT_ENERGY_MAX_EV",
    "DEFAULT_ENERGY_MIN_EV",
    "DEFAULT_MAX_ENERGY_POINTS",
    "DEFAULT_MAX_IMPACT_POINTS",
    "DEFAULT_MAXIMUM_TRAJECTORIES",
    "DEFAULT_MINIMUM_TRAJECTORIES",
    "DEFAULT_MINIMUM_TURNING_POTENTIAL_EV",
    "DEFAULT_PROJECTILES",
    "DEFAULT_QUADRATURE_ORDER",
    "DEFAULT_STATISTICAL_CONFIDENCE",
    "DEFAULT_STATISTICAL_RELATIVE_TOLERANCE",
    "DEFAULT_TRAJECTORY_BATCH_SIZE",
    "DEFAULT_WORKERS",
    "IceStructure",
    "AdaptiveKernelTable",
    "HardCollisionEvent",
    "HardTrajectoryResult",
    "KernelTableError",
    "NLHCollisionKernel",
    "OBSERVABLES",
    "PairKinematics",
    "PeriodicHardCollisionTransport",
    "RuntimeCollision",
    "RatioStatistics",
    "TwoBodyOutcome",
    "StructureValidationError",
    "hard_cross_section_angstrom2",
    "convergence_report",
    "doubling_schedule",
    "load_ice_structure",
    "maximum_impact_parameter_angstrom",
    "pair_kinematics",
    "solve_nlh_collision",
    "two_body_outcome_from_cm_angle",
    "two_body_observables_from_cm_angles",
    "turning_threshold_radius_angstrom",
]
