#!/usr/bin/env python3
"""
Compute stopping power and IMFP from projectile DCS tables.

This is the projectile analogue of plot_stopping_power_xs.py, but omits the
W-value panel. It expects DCS files generated by generate_ice_cross_sections_ion.py,
for example sigmadiff_excitation_proton_hexagonal_ice_emfietzoglou_kyriakou.dat.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np
import uproot
from matplotlib.ticker import LogFormatterMathtext, LogLocator, NullFormatter

PYTHON_SCRIPTS_DIR = Path(__file__).resolve().parents[1]
if str(PYTHON_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(PYTHON_SCRIPTS_DIR))
PHYSICS_ICE_DIR = Path(__file__).resolve().parents[1] / "physics_ice"
if str(PHYSICS_ICE_DIR) not in sys.path:
    sys.path.insert(0, str(PHYSICS_ICE_DIR))

from constants import (  # noqa: E402
    CROSS_SECTIONS_DIR,
    CROSS_SECTION_PLOTS_DIR,
    CUSTOM_DATA_ROOT_GEANT4,
    CUSTOM_DATA_ROOT_PROJECT,
    EMFIETZOGLOU_SCALE_1E16,
    FONT_COURIER,
    FONTSIZE_24,
    ICE_AMORPHOUS_DENSITY_G_CM3,
    ICE_HEXAGONAL_DENSITY_G_CM3,
    MC2_eV,
    N,
    OUTPUT_DIR,
    PROJECT_ROOT,
    PROJECTILE_LIBRARY,
    RC_BASE_ELASTIC,
    rcparams_with_fontsize,
)
from physics_ice.root_utils import resolve_root_paths  # noqa: E402
from plot_proton_root_observables import ION_CONFIGS as ROOT_ION_CONFIGS  # noqa: E402

plt.rcParams["font.family"] = FONT_COURIER
plt.rcParams["mathtext.rm"] = FONT_COURIER
plt.rcParams["mathtext.fontset"] = "custom"
plt.rcParams.update(rcparams_with_fontsize(RC_BASE_ELASTIC, FONTSIZE_24))

CM_PER_NM = 1.0e7
EV_NM_TO_MEV_CM = 10.0
EV_NM_TO_EV_ANG = 0.1
WATER_DENSITY_G_CM3 = 1.0
N_CM3_WATER = N / 1.0e6
GEANT4_DNA_SCALE_CM2 = EMFIETZOGLOU_SCALE_1E16 * 1.0e-16
GEANT4_SI_M2_TO_CM2 = 1.0e4
WATER_EXCITATION_ENERGIES_EV = np.array([8.22, 10.00, 11.24, 12.61, 13.77], dtype=float)
WATER_IONISATION_BINDINGS_EV = np.array([12.60, 14.70, 18.40, 32.20, 540.0], dtype=float)
RUDD_ALPHA_WMAX_FACTOR = 4.0 * 0.511 / 3728.0
BOHR_RADIUS_CM = 5.29177210903e-9
RYDBERG_EV = 13.6
BARKAS_ZEFF_COEFF = 125.0
FINE_STRUCTURE = 7.2973525693e-3
CLASSICAL_ELECTRON_RADIUS_CM = 2.8179403262e-13
TARGET_ELECTRONS_H2O = 10.0
SIMULATION_REDUCER_VERSION = 2
ICE_DENSITY_BY_TYPE = {
    "amorphous": ICE_AMORPHOUS_DENSITY_G_CM3,
    "hexagonal": ICE_HEXAGONAL_DENSITY_G_CM3,
}
PROJECTILE_AXIS_LABELS = {
    "proton": "Proton",
    "alpha": "Alpha",
    "carbon": "Carbon",
    "oxygen": "Oxygen",
}
ICRU_DATA_DIR = Path(__file__).resolve().parent / "data"
ICRU_WATER_DENSITY_G_CM3 = 0.998
ICRU_STOPPING_POWER_FILES = {
    "proton": ICRU_DATA_DIR / "icru90_stopping_power_liquid_water_proton.csv",
    "alpha": ICRU_DATA_DIR / "icru90_stopping_power_liquid_water_alpha.csv",
    "carbon": ICRU_DATA_DIR / "icru90_stopping_power_liquid_water_carbon.csv",
    "oxygen": ICRU_DATA_DIR / "icru73_stopping_power_liquid_water_oxygen.csv",
}


def _icru_label(projectile_key: str) -> str:
    return "ICRU 73 water" if projectile_key == "oxygen" else "ICRU 90 water"


def _projectile_config(key: str) -> tuple[str, dict]:
    lookup = str(key).strip().lower()
    for name, cfg in PROJECTILE_LIBRARY.items():
        aliases = cfg.get("aliases", ())
        if lookup == name or lookup in aliases:
            return name, cfg
    supported = ", ".join(PROJECTILE_LIBRARY)
    raise ValueError(f"Unsupported projectile {key!r}; choose one of: {supported}")


def _ensure_exists(path: Path) -> None:
    if not path.exists():
        raise FileNotFoundError(f"Missing required data file: {path}")


def _projectile_paths(projectile_token: str, ice_type: str, cross_section_set: str = "bare") -> dict[str, Path]:
    ice_label = f"{ice_type}_ice"
    # Files with this suffix are Born + Barkas corrected total tables, not Barkas-only tables.
    suffix = "_barkas_dcs" if str(cross_section_set) == "barkas_dcs" else ""
    return {
        "exc_dcs": CROSS_SECTIONS_DIR / (
            f"sigmadiff_excitation_{projectile_token}_{ice_label}{suffix}_emfietzoglou_kyriakou.dat"
        ),
        "ion_dcs": CROSS_SECTIONS_DIR / (
            f"sigmadiff_ionisation_{projectile_token}_{ice_label}{suffix}_emfietzoglou_kyriakou.dat"
        ),
        "exc_total": CROSS_SECTIONS_DIR / (
            f"sigma_excitation_{projectile_token}_{ice_label}{suffix}_emfietzoglou_kyriakou.dat"
        ),
        "ion_total": CROSS_SECTIONS_DIR / (
            f"sigma_ionisation_{projectile_token}_{ice_label}{suffix}_emfietzoglou_kyriakou.dat"
        ),
    }


def _find_geant4_dna_file(filename: str) -> Path | None:
    for root in (CUSTOM_DATA_ROOT_GEANT4, CUSTOM_DATA_ROOT_PROJECT):
        dna_dir = root / "G4EMLOW8.6.1" / "dna"
        path = dna_dir / filename
        if path.exists():
            return path
        if root.exists():
            for subdir in sorted(root.glob("G4EMLOW*/dna")):
                path = subdir / filename
                if path.exists():
                    return path
    return None


def _water_born_paths(projectile_key: str) -> dict[str, Path] | None:
    if projectile_key != "proton":
        return None
    names = {
        "exc_total": "sigma_excitation_p_born.dat",
        "ion_dcs": "sigmadiff_ionisation_p_born.dat",
        "ion_total": "sigma_ionisation_p_born.dat",
    }
    paths: dict[str, Path] = {}
    for key, name in names.items():
        path = _find_geant4_dna_file(name)
        if path is None:
            return None
        paths[key] = path
    return paths


def _alpha_rudd_ionisation_path() -> Path | None:
    return _find_geant4_dna_file("sigma_ionisation_alphaplusplus_rudd.dat")


def _first_column_bounds(path: Path) -> tuple[float, float]:
    _ensure_exists(path)
    values = np.loadtxt(path, dtype=float, usecols=[0])
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values) & (values > 0.0)]
    if values.size == 0:
        raise ValueError(f"No positive incident-energy values in {path}")
    return float(np.min(values)), float(np.max(values))


def _available_energy_range(projectile_token: str, ice_type: str, cross_section_set: str = "bare") -> tuple[float, float]:
    ranges = [
        _first_column_bounds(path)
        for path in _projectile_paths(projectile_token, ice_type, cross_section_set).values()
    ]
    emin = max(item[0] for item in ranges)
    emax = min(item[1] for item in ranges)
    if emin >= emax:
        raise ValueError(
            f"No common projectile cross-section/DCS energy range for {projectile_token}, {ice_type} ice."
        )
    return emin, emax


def _generator_tlist_range(projectile_token: str, ice_type: str) -> tuple[float, float] | None:
    cache_path = OUTPUT_DIR / f"cross_section_corrections_pwba_{projectile_token}_{ice_type}_ice.npz"
    if not cache_path.exists():
        return None
    data = np.load(cache_path, allow_pickle=True)
    if "T_eV" not in data:
        return None
    values = np.asarray(data["T_eV"], dtype=float)
    values = values[np.isfinite(values) & (values > 0.0)]
    if values.size == 0:
        return None
    return float(np.min(values)), float(np.max(values))


def _plot_energy_range(
    projectile_token: str,
    ice_type: str,
    cross_section_set: str = "bare",
) -> tuple[float, float]:
    return _available_energy_range(projectile_token, ice_type, cross_section_set)


def _simpson_nonuniform(x: np.ndarray, y: np.ndarray) -> float:
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    mask = np.isfinite(x) & np.isfinite(y)
    x = x[mask]
    y = y[mask]
    if x.size < 2:
        return 0.0
    order = np.argsort(x)
    x = x[order]
    y = y[order]
    unique_x, inv = np.unique(x, return_inverse=True)
    if unique_x.size != x.size:
        y_sum = np.zeros_like(unique_x)
        counts = np.zeros_like(unique_x)
        for i, idx in enumerate(inv):
            y_sum[idx] += y[i]
            counts[idx] += 1.0
        x = unique_x
        y = y_sum / np.where(counts == 0.0, 1.0, counts)
    if x.size < 2:
        return 0.0
    if x.size == 2:
        return float(np.trapezoid(y, x))

    total = 0.0
    end = x.size if x.size % 2 == 1 else x.size - 1
    for i in range(0, end - 2, 2):
        x0, x1, x2 = x[i], x[i + 1], x[i + 2]
        y0, y1, y2 = y[i], y[i + 1], y[i + 2]
        h0 = x1 - x0
        h1 = x2 - x1
        if h0 <= 0.0 or h1 <= 0.0:
            continue
        w0 = 2.0 - h1 / h0
        w1 = ((h0 + h1) ** 2) / (h0 * h1)
        w2 = 2.0 - h0 / h1
        total += (h0 + h1) * (w0 * y0 + w1 * y1 + w2 * y2) / 6.0
    if x.size % 2 == 0:
        total += float(np.trapezoid(y[-2:], x[-2:]))
    return float(total)


def _interp_loglog(x: np.ndarray, y: np.ndarray, x_new: np.ndarray) -> np.ndarray:
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    x_new = np.asarray(x_new, dtype=float)
    order = np.argsort(x)
    x = x[order]
    y = y[order]
    positive = (x > 0.0) & (y > 0.0)
    out = np.zeros_like(x_new)
    if np.count_nonzero(positive) < 2:
        return out
    xp = x[positive]
    yp = y[positive]
    mask = (x_new >= xp[0]) & (x_new <= xp[-1])
    out[mask] = 10.0 ** np.interp(
        np.log10(x_new[mask]),
        np.log10(xp),
        np.log10(yp),
    )
    out[~np.isfinite(out)] = 0.0
    return out


def _projectile_wmax_nonrel_eV(tau_eV: float, projectile_mass_au: float) -> float:
    return 4.0 * float(tau_eV) / float(projectile_mass_au)


def _projectile_beta(energy_eV: np.ndarray, projectile_mass_au: float) -> np.ndarray:
    energy = np.asarray(energy_eV, dtype=float)
    rest_eV = float(projectile_mass_au) * MC2_eV
    gamma = 1.0 + np.maximum(energy, 0.0) / rest_eV
    beta2 = 1.0 - 1.0 / np.square(gamma)
    return np.sqrt(np.maximum(beta2, 0.0))


def _barkas_effective_charge(energy_eV: np.ndarray, projectile_charge: float, projectile_mass_au: float) -> np.ndarray:
    """Barkas effective-charge formula for a projectile charge prefactor."""
    z = float(projectile_charge)
    energy = np.asarray(energy_eV, dtype=float)
    if z <= 0.0:
        return np.zeros_like(energy)
    beta = _projectile_beta(energy, projectile_mass_au)
    zeff = z * (1.0 - np.exp(-BARKAS_ZEFF_COEFF * beta * z ** (-2.0 / 3.0)))
    return np.clip(zeff, 0.0, z)


def _barkas_zeff_scale(energy_eV: np.ndarray, projectile_charge: float, projectile_mass_au: float) -> np.ndarray:
    z = float(projectile_charge)
    if z <= 0.0:
        return np.ones_like(np.asarray(energy_eV, dtype=float))
    zeff = _barkas_effective_charge(energy_eV, z, projectile_mass_au)
    return np.square(zeff / z)


def _bloch_log_correction(eta: np.ndarray, max_terms: int = 50000, tol: float = 1.0e-12) -> np.ndarray:
    """Bloch correction to the Bethe stopping logarithm."""
    eta = np.asarray(eta, dtype=float)
    eta2 = eta * eta
    total = np.zeros_like(eta, dtype=float)
    for n in range(1, max_terms + 1):
        nf = float(n)
        term = eta2 / (nf * (nf * nf + eta2))
        total += term
        if n > 1000 and np.nanmax(np.abs(term)) < tol:
            break
    return -total


def _bloch_eloss_xs_ev_cm2(
    energy_eV: np.ndarray,
    projectile_mass_au: float,
    interaction_charge: np.ndarray | float,
) -> np.ndarray:
    """Stopping-cross-section Bloch term; this is not a DCS/TCS correction."""
    beta = _projectile_beta(energy_eV, projectile_mass_au)
    beta = np.maximum(beta, 1.0e-300)
    q = np.asarray(interaction_charge, dtype=float)
    eta = q * FINE_STRUCTURE / beta
    delta_l = _bloch_log_correction(eta)
    return (
        4.0
        * np.pi
        * CLASSICAL_ELECTRON_RADIUS_CM**2
        * MC2_eV
        * TARGET_ELECTRONS_H2O
        * (q * q / (beta * beta))
        * delta_l
    )


def _units_and_label(units: str, density: float, dedx: np.ndarray) -> tuple[np.ndarray, str]:
    if units == "ev_ang":
        return dedx * EV_NM_TO_EV_ANG, r"Stopping Power (eV/$\AA$)"
    if units == "mev_cm":
        return dedx * EV_NM_TO_MEV_CM, "Stopping Power (MeV/cm)"
    if units == "mev_cm2_g":
        return (dedx * EV_NM_TO_MEV_CM) / density, "Mass Stopping Power (MeV cm^2/g)"
    return dedx, "Stopping Power (eV/nm)"


def _icru_mass_stopping_to_units(units: str, mass_sp: np.ndarray) -> np.ndarray:
    linear_mev_cm = np.asarray(mass_sp, dtype=float) * ICRU_WATER_DENSITY_G_CM3
    if units == "ev_ang":
        return linear_mev_cm * 0.01
    if units == "mev_cm":
        return linear_mev_cm
    if units == "mev_cm2_g":
        return np.asarray(mass_sp, dtype=float)
    return linear_mev_cm / EV_NM_TO_MEV_CM


def _load_icru_stopping_power(projectile_key: str) -> tuple[np.ndarray, np.ndarray] | None:
    path = ICRU_STOPPING_POWER_FILES.get(projectile_key)
    if path is None or not path.exists():
        return None
    data = np.loadtxt(path, delimiter=",", comments="#", dtype=float)
    data = np.atleast_2d(data)
    energy_eV = data[:, 0] * 1.0e6
    mass_sp = data[:, 1]
    valid = np.isfinite(energy_eV) & np.isfinite(mass_sp) & (energy_eV > 0.0) & (mass_sp > 0.0)
    return energy_eV[valid], mass_sp[valid]


def _load_total_sigma_table(path: Path, drop_kshell: bool = False) -> tuple[np.ndarray, np.ndarray]:
    _ensure_exists(path)
    data = np.loadtxt(path, dtype=float)
    data = np.atleast_2d(data)
    energy = data[:, 0]
    components = data[:, 1:]
    if drop_kshell and components.shape[1] >= 5:
        components = components[:, :-1]
    sigma = np.sum(components, axis=1) * GEANT4_DNA_SCALE_CM2
    valid = np.isfinite(energy) & np.isfinite(sigma) & (energy > 0.0)
    return energy[valid], sigma[valid]


def _load_component_sigma_table(path: Path) -> tuple[np.ndarray, np.ndarray]:
    _ensure_exists(path)
    data = np.loadtxt(path, dtype=float)
    data = np.atleast_2d(data)
    energy = data[:, 0]
    sigma_components = data[:, 1:] * GEANT4_DNA_SCALE_CM2
    valid = np.isfinite(energy) & (energy > 0.0) & np.all(np.isfinite(sigma_components), axis=1)
    return energy[valid], sigma_components[valid, :]


def _load_alpha_rudd_components(path: Path, drop_kshell: bool = False) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    _ensure_exists(path)
    data = np.loadtxt(path, dtype=float)
    data = np.atleast_2d(data)
    energy = data[:, 0]
    components = data[:, 1:] * GEANT4_SI_M2_TO_CM2
    bindings = WATER_IONISATION_BINDINGS_EV[: components.shape[1]]
    if drop_kshell and components.shape[1] >= 5:
        components = components[:, :-1]
        bindings = bindings[:-1]
    valid = np.isfinite(energy) & (energy > 0.0) & np.all(np.isfinite(components), axis=1)
    return energy[valid], components[valid, :], bindings


def _alpha_rudd_dcs_shape(incident_eV: float, transfer_eV: np.ndarray, shell: int) -> np.ndarray:
    """Geant4-DNA G4DNARuddIonisationModel alpha++ DCS shape for liquid water."""
    transfer = np.asarray(transfer_eV, dtype=float)
    binding = float(WATER_IONISATION_BINDINGS_EV[shell])
    secondary = transfer - binding
    out = np.zeros_like(transfer)
    valid = secondary >= 0.0
    if not np.any(valid):
        return out

    if shell == 4:
        A1, B1, C1, D1, E1 = 1.25, 0.5, 1.00, 1.00, 3.00
        A2, B2, C2, D2, alpha_const = 1.10, 1.30, 1.00, 0.00, 0.66
    else:
        A1, B1, C1, D1, E1 = 1.02, 82.0, 0.45, -0.80, 0.38
        A2, B2, C2, D2, alpha_const = 1.07, 11.6, 0.60, 0.04, 0.64

    gj = np.array([0.99, 1.11, 1.11, 0.52, 1.0], dtype=float)[shell]
    tau = (0.511 / 3728.0) * float(incident_eV)
    v2 = tau / binding
    if v2 <= 0.0:
        return out
    v = np.sqrt(v2)
    wc = 4.0 * v2 - 2.0 * v - (RYDBERG_EV / (4.0 * binding))
    s_factor = 4.0 * np.pi * BOHR_RADIUS_CM * BOHR_RADIUS_CM * 2.0 * (RYDBERG_EV / binding) ** 2
    w = secondary[valid] / binding
    l1 = (C1 * v**D1) / (1.0 + E1 * v ** (D1 + 4.0))
    l2 = C2 * v**D2
    h1 = (A1 * np.log1p(v2)) / (v2 + (B1 / v2))
    h2 = (A2 / v2) + (B2 / (v2 * v2))
    f1 = l1 + h1
    f2 = (l2 * h2) / (l2 + h2)
    denom = (1.0 + w) ** 3 * (1.0 + np.exp(alpha_const * (w - wc) / v))

    # For alpha++ Geant4 applies z_eff^2 = 4 to the Rudd water DCS.
    out[valid] = 4.0 * gj * (s_factor / binding) * ((f1 + w * f2) / denom)
    out[~np.isfinite(out)] = 0.0
    return out


def _alpha_rudd_eloss_xs(
    energy_grid: np.ndarray,
    rudd_energy: np.ndarray,
    rudd_components: np.ndarray,
    bindings: np.ndarray,
) -> np.ndarray:
    """Return energy-loss cross-section from Rudd DCS shape normalized to Geant4 tabulated sigma."""
    component_interp = [
        _interp_loglog(rudd_energy, rudd_components[:, i], energy_grid)
        for i in range(rudd_components.shape[1])
    ]
    eloss = np.zeros_like(energy_grid, dtype=float)
    for ie, incident in enumerate(np.asarray(energy_grid, dtype=float)):
        for shell, binding in enumerate(bindings):
            shell_sigma = float(component_interp[shell][ie])
            wmax = RUDD_ALPHA_WMAX_FACTOR * float(incident)
            if shell_sigma <= 0.0 or wmax <= 0.0:
                continue
            secondary = np.concatenate(([0.0], np.geomspace(1.0e-6, wmax, 280)))
            transfer = float(binding) + secondary
            shape = _alpha_rudd_dcs_shape(float(incident), transfer, shell)
            area = float(np.trapezoid(shape, transfer))
            if not np.isfinite(area) or area <= 0.0:
                continue
            mean_loss = float(np.trapezoid(transfer * shape, transfer) / area)
            if np.isfinite(mean_loss) and mean_loss > 0.0:
                eloss[ie] += shell_sigma * mean_loss
    return eloss


def _energy_loss_xs_with_cutoff(
    omega: np.ndarray,
    sigma: np.ndarray,
    cutoff_eV: float | None,
) -> float:
    order = np.argsort(omega)
    omega = np.asarray(omega, dtype=float)[order]
    sigma = np.asarray(sigma, dtype=float)[order]

    if cutoff_eV is None:
        return _simpson_nonuniform(omega, omega * sigma)

    cutoff = float(cutoff_eV)
    if cutoff <= float(np.min(omega)):
        return 0.0

    keep = omega <= cutoff
    x = omega[keep]
    y = sigma[keep]
    if cutoff < float(np.max(omega)) and np.any(omega < cutoff) and np.any(omega > cutoff):
        y_cut = float(np.interp(cutoff, omega, sigma))
        if x.size == 0 or not np.isclose(float(x[-1]), cutoff):
            x = np.append(x, cutoff)
            y = np.append(y, y_cut)
    if x.size < 2:
        return 0.0
    return _simpson_nonuniform(x, x * y)


def _dcs_moments_table(
    path: Path,
    projectile_mass_au: float,
    stopping_cutoff: str,
    drop_kshell: bool = False,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return incident energy, sigma_total, and energy-loss cross-section."""
    _ensure_exists(path)
    scale_cm2 = GEANT4_DNA_SCALE_CM2
    energies: list[float] = []
    sigma_xs: list[float] = []
    eloss_xs: list[float] = []

    current_e: float | None = None
    transfer_vals: list[float] = []
    sigma_vals: list[list[float]] = []
    n_channels: int | None = None

    def flush() -> None:
        if current_e is None or len(transfer_vals) < 2 or n_channels is None:
            return
        omega = np.asarray(transfer_vals, dtype=float)
        sigma = np.asarray(sigma_vals, dtype=float) * scale_cm2
        if drop_kshell and sigma.shape[0] >= 5:
            sigma = sigma[:-1, :]
        cutoff_eV = None
        if stopping_cutoff == "wmax_nonrel":
            cutoff_eV = min(float(current_e), _projectile_wmax_nonrel_eV(float(current_e), projectile_mass_au))
        sigma_sum = 0.0
        eloss_sum = 0.0
        for j in range(sigma.shape[0]):
            s = sigma[j]
            sigma_sum += _simpson_nonuniform(omega, s)
            eloss_sum += _energy_loss_xs_with_cutoff(omega, s, cutoff_eV)
        energies.append(float(current_e))
        sigma_xs.append(float(sigma_sum))
        eloss_xs.append(float(eloss_sum))

    with open(path, "r") as handle:
        for line in handle:
            if not line.strip():
                continue
            parts = line.split()
            if len(parts) < 3:
                continue
            incident_e = float(parts[0])
            transfer = float(parts[1])
            if n_channels is None:
                n_channels = len(parts) - 2
                sigma_vals = [[] for _ in range(n_channels)]
            if len(parts) < 2 + n_channels:
                continue
            if current_e is None:
                current_e = incident_e
            if incident_e != current_e:
                flush()
                current_e = incident_e
                transfer_vals = []
                sigma_vals = [[] for _ in range(n_channels)]
            transfer_vals.append(transfer)
            for j, value in enumerate(parts[2 : 2 + n_channels]):
                sigma_vals[j].append(float(value))
    flush()

    return (
        np.asarray(energies, dtype=float),
        np.asarray(sigma_xs, dtype=float),
        np.asarray(eloss_xs, dtype=float),
    )


def _to_dedx_ev_nm(eloss_xs: np.ndarray, n_cm3: float) -> np.ndarray:
    return (np.asarray(eloss_xs, dtype=float) * n_cm3) / CM_PER_NM


def _to_inverse_mfp_nm(sigma_xs: np.ndarray, n_cm3: float) -> np.ndarray:
    return (np.asarray(sigma_xs, dtype=float) * n_cm3) / CM_PER_NM


PROJECTILE_COMPONENT_KEYS = ("exc_eloss", "ion_eloss", "exc_sigma", "ion_sigma")


def _load_projectile_table_components(
    projectile_token: str,
    projectile_mass_au: float,
    ice_type: str,
    energy_grid: np.ndarray,
    stopping_cutoff: str,
    include_kshell: bool,
    table_set: str,
) -> dict:
    paths = _projectile_paths(projectile_token, ice_type, table_set)
    exc_energy, _, exc_eloss = _dcs_moments_table(paths["exc_dcs"], projectile_mass_au, stopping_cutoff)
    ion_energy, _, ion_eloss = _dcs_moments_table(
        paths["ion_dcs"],
        projectile_mass_au,
        stopping_cutoff,
        drop_kshell=not include_kshell,
    )
    exc_sigma_energy, exc_sigma = _load_total_sigma_table(paths["exc_total"])
    ion_sigma_energy, ion_sigma = _load_total_sigma_table(
        paths["ion_total"],
        drop_kshell=not include_kshell,
    )
    return {
        "table_set": table_set,
        "exc_eloss": _interp_loglog(exc_energy, exc_eloss, energy_grid),
        "ion_eloss": _interp_loglog(ion_energy, ion_eloss, energy_grid),
        "exc_sigma": _interp_loglog(exc_sigma_energy, exc_sigma, energy_grid),
        "ion_sigma": _interp_loglog(ion_sigma_energy, ion_sigma, energy_grid),
        "emin": max(
            float(np.min(exc_energy)),
            float(np.min(ion_energy)),
            float(np.min(exc_sigma_energy)),
            float(np.min(ion_sigma_energy)),
            float(np.min(energy_grid)),
        ),
        "emax": min(
            float(np.max(exc_energy)),
            float(np.max(ion_energy)),
            float(np.max(exc_sigma_energy)),
            float(np.max(ion_sigma_energy)),
            float(np.max(energy_grid)),
        ),
    }


def _difference_components(corrected: dict, bare: dict, label: str) -> tuple[dict, list[str]]:
    out = {
        "table_set": "barkas_difference",
        "emin": max(float(corrected["emin"]), float(bare["emin"])),
        "emax": min(float(corrected["emax"]), float(bare["emax"])),
    }
    warnings = []
    for key in PROJECTILE_COMPONENT_KEYS:
        diff = np.asarray(corrected[key], dtype=float) - np.asarray(bare[key], dtype=float)
        out[key] = diff
        nonfinite = int(np.count_nonzero(~np.isfinite(diff)))
        finite = diff[np.isfinite(diff)]
        negative = finite[finite < 0.0]
        if nonfinite:
            warnings.append(f"{label}: {key} corrected-minus-bare has {nonfinite} non-finite values.")
        if negative.size:
            warnings.append(
                f"{label}: {key} corrected-minus-bare has {negative.size} negative values "
                f"(min={float(np.min(negative)):.6g})."
            )
    return out, warnings


def _scale_components(components: dict, scale: np.ndarray | float) -> dict:
    out = {
        "table_set": components.get("table_set", ""),
        "emin": float(components["emin"]),
        "emax": float(components["emax"]),
    }
    for key in PROJECTILE_COMPONENT_KEYS:
        out[key] = np.asarray(components[key], dtype=float) * scale
    return out


def _add_components(left: dict, right: dict) -> dict:
    out = {
        "table_set": "combined",
        "emin": max(float(left["emin"]), float(right["emin"])),
        "emax": min(float(left["emax"]), float(right["emax"])),
    }
    for key in PROJECTILE_COMPONENT_KEYS:
        out[key] = np.asarray(left[key], dtype=float) + np.asarray(right[key], dtype=float)
    return out


def _append_bloch_label(label: str, include_bloch_stopping: bool) -> str:
    if not include_bloch_stopping:
        return label
    return f"{label} + Bloch"


def _components_to_series(
    components: dict,
    energy_grid: np.ndarray,
    ice_type: str,
    rho_ice: float | None,
    label: str,
    cross_section_tables: str,
    table_semantics: str,
    charge_scaling: str,
    barkas_difference_used: bool,
    warnings: list[str],
    projectile_charge: float,
    projectile_mass_au: float,
    charge_scale: np.ndarray,
    interaction_charge: np.ndarray,
    include_bloch_stopping: bool,
) -> dict:
    phase_density = ICE_DENSITY_BY_TYPE[ice_type]
    density = float(rho_ice) if rho_ice is not None else float(phase_density)
    n_cm3 = N_CM3_WATER * (density / WATER_DENSITY_G_CM3)

    exc_dedx = _to_dedx_ev_nm(components["exc_eloss"], n_cm3)
    ion_dedx = _to_dedx_ev_nm(components["ion_eloss"], n_cm3)
    dcs_total_dedx = exc_dedx + ion_dedx
    exc_imfp = _to_inverse_mfp_nm(components["exc_sigma"], n_cm3)
    ion_imfp = _to_inverse_mfp_nm(components["ion_sigma"], n_cm3)

    series_warnings = list(warnings)
    if include_bloch_stopping:
        bloch_eloss_xs = _bloch_eloss_xs_ev_cm2(energy_grid, projectile_mass_au, interaction_charge)
        bloch_dedx = _to_dedx_ev_nm(bloch_eloss_xs, n_cm3)
    else:
        bloch_eloss_xs = np.zeros_like(dcs_total_dedx)
        bloch_dedx = np.zeros_like(dcs_total_dedx)
    stopping_total_dedx = dcs_total_dedx + bloch_dedx

    with np.errstate(divide="ignore", invalid="ignore"):
        bloch_fraction = np.divide(
            bloch_dedx,
            dcs_total_dedx,
            out=np.full_like(bloch_dedx, np.nan, dtype=float),
            where=np.isfinite(dcs_total_dedx) & (dcs_total_dedx != 0.0),
        )
    if include_bloch_stopping:
        nonpositive = np.count_nonzero(np.isfinite(stopping_total_dedx) & (stopping_total_dedx <= 0.0))
        if nonpositive:
            series_warnings.append(
                "Bloch-corrected stopping power is non-positive at some energies; "
                "those values are invalid for log plotting."
            )
        too_large = np.count_nonzero(np.isfinite(bloch_fraction) & (np.abs(bloch_fraction) > 1.0))
        if too_large:
            series_warnings.append(
                "Bloch correction exceeds the DCS stopping magnitude; "
                "corrected-Bethe expansion may be outside its valid range."
            )

    if series_warnings:
        for warning in series_warnings:
            print(f"WARNING: {warning}")

    finite_bloch_fraction = bloch_fraction[np.isfinite(bloch_fraction)]
    finite_q = np.asarray(interaction_charge, dtype=float)
    finite_q = finite_q[np.isfinite(finite_q)]
    finite_bloch = bloch_dedx[np.isfinite(bloch_dedx)]

    return {
        "label": label,
        "ice_type": ice_type,
        "cross_section_tables": cross_section_tables,
        "table_semantics": table_semantics,
        "charge_scaling": charge_scaling,
        "barkas_difference_used": bool(barkas_difference_used),
        "warnings": series_warnings,
        "density_g_cm3": density,
        "charge_correction": charge_scaling,
        "projectile_charge_bare": float(projectile_charge),
        "zeff_scale_min": float(np.nanmin(charge_scale)),
        "zeff_scale_max": float(np.nanmax(charge_scale)),
        "include_bloch_stopping": bool(include_bloch_stopping),
        "bloch_charge_mode": "effective_charge" if "zeff" in str(charge_scaling) else "bare_charge",
        "bloch_interaction_charge_min": float(np.nanmin(finite_q)) if finite_q.size else None,
        "bloch_interaction_charge_max": float(np.nanmax(finite_q)) if finite_q.size else None,
        "bloch_min_ev_nm": float(np.nanmin(finite_bloch)) if finite_bloch.size else 0.0,
        "bloch_max_ev_nm": float(np.nanmax(finite_bloch)) if finite_bloch.size else 0.0,
        "bloch_min_fraction_of_dcs": (
            float(np.nanmin(finite_bloch_fraction)) if finite_bloch_fraction.size else None
        ),
        "bloch_max_fraction_of_dcs": (
            float(np.nanmax(finite_bloch_fraction)) if finite_bloch_fraction.size else None
        ),
        "emin": float(components["emin"]),
        "emax": float(components["emax"]),
        "dedx_exc": exc_dedx,
        "dedx_ion": ion_dedx,
        "dedx_dcs_total": dcs_total_dedx,
        "dedx_bloch": bloch_dedx,
        "bloch_eloss_xs_ev_cm2": bloch_eloss_xs,
        "dedx_stopping_total": stopping_total_dedx,
        "dedx_total": stopping_total_dedx,
        "imfp_exc": exc_imfp,
        "imfp_ion": ion_imfp,
        "imfp_total": exc_imfp + ion_imfp,
    }


def _build_series(
    projectile_token: str,
    projectile_label: str,
    projectile_mass_au: float,
    projectile_charge: float,
    ice_type: str,
    energy_grid: np.ndarray,
    rho_ice: float | None,
    stopping_cutoff: str,
    include_kshell: bool,
    barkas_zeff: bool,
    include_bloch_stopping: bool,
    cross_section_set: str = "bare",
) -> dict:
    bare = _load_projectile_table_components(
        projectile_token,
        projectile_mass_au,
        ice_type,
        energy_grid,
        stopping_cutoff,
        include_kshell,
        "bare",
    )
    corrected = None
    barkas = None
    difference_warnings: list[str] = []
    if cross_section_set == "barkas_dcs":
        corrected = _load_projectile_table_components(
            projectile_token,
            projectile_mass_au,
            ice_type,
            energy_grid,
            stopping_cutoff,
            include_kshell,
            "barkas_dcs",
        )
    if cross_section_set == "barkas_dcs" and barkas_zeff:
        if corrected is None:
            raise RuntimeError("Corrected table was not loaded for Barkas decomposition.")
        barkas, difference_warnings = _difference_components(
            corrected,
            bare,
            f"{projectile_label} {ice_type} ice",
        )

    one = np.ones_like(energy_grid, dtype=float)
    bare_charge = np.full_like(energy_grid, float(projectile_charge), dtype=float)
    effective_charge = _barkas_effective_charge(energy_grid, projectile_charge, projectile_mass_au)
    zeff_over_z_squared = _barkas_zeff_scale(energy_grid, projectile_charge, projectile_mass_au)
    zeff_over_z = np.sqrt(np.maximum(zeff_over_z_squared, 0.0))

    if cross_section_set == "bare":
        if barkas_zeff:
            components = _scale_components(bare, zeff_over_z_squared)
            label = f"{ice_type.capitalize()}: Born + z$_{{\\rm eff}}$"
            charge_scaling = "zeff_born_only"
            charge_scale = zeff_over_z_squared
            interaction_charge = effective_charge
        else:
            components = bare
            label = f"{ice_type.capitalize()}: Born"
            charge_scaling = "bare_charge"
            charge_scale = one
            interaction_charge = bare_charge
        return _components_to_series(
            components,
            energy_grid,
            ice_type,
            rho_ice,
            _append_bloch_label(label, include_bloch_stopping),
            "bare",
            "born_only",
            charge_scaling,
            False,
            [],
            projectile_charge,
            projectile_mass_au,
            charge_scale,
            interaction_charge,
            include_bloch_stopping,
        )

    if cross_section_set == "barkas_dcs":
        if corrected is None:
            raise RuntimeError("Corrected table was not loaded.")
        if barkas_zeff:
            if barkas is None:
                raise RuntimeError("Barkas difference was not available for Zeff decomposition.")
            born_scaled = _scale_components(bare, zeff_over_z_squared)
            barkas_scaled = _scale_components(barkas, zeff_over_z**3)
            components = _add_components(born_scaled, barkas_scaled)
            label = f"{ice_type.capitalize()}: Barkas + z$_{{\\rm eff}}$"
            charge_scaling = "zeff_decomposed_born_plus_barkas"
            charge_scale = zeff_over_z_squared
            barkas_difference_used = True
            warnings = difference_warnings
            interaction_charge = effective_charge
        else:
            components = corrected
            label = f"{ice_type.capitalize()}: Born + Barkas"
            charge_scaling = "bare_charge"
            charge_scale = one
            barkas_difference_used = False
            warnings = []
            interaction_charge = bare_charge
        return _components_to_series(
            components,
            energy_grid,
            ice_type,
            rho_ice,
            _append_bloch_label(label, include_bloch_stopping),
            "barkas_dcs",
            "born_plus_barkas_corrected",
            charge_scaling,
            barkas_difference_used,
            warnings,
            projectile_charge,
            projectile_mass_au,
            charge_scale,
            interaction_charge,
            include_bloch_stopping,
        )

    raise ValueError(f"Unsupported cross_section_set for series build: {cross_section_set!r}")


def _build_water_series(
    projectile_key: str,
    projectile_mass_au: float,
    energy_grid: np.ndarray,
    stopping_cutoff: str,
    include_kshell: bool,
) -> dict | None:
    if projectile_key == "alpha":
        path = _alpha_rudd_ionisation_path()
        if path is None:
            return None
        ion_energy, ion_components, bindings = _load_alpha_rudd_components(
            path,
            drop_kshell=not include_kshell,
        )
        ion_sigma = np.sum(ion_components, axis=1)
        ion_sigma_grid = _interp_loglog(ion_energy, ion_sigma, energy_grid)
        ion_eloss = _alpha_rudd_eloss_xs(energy_grid, ion_energy, ion_components, bindings)
        ion_dedx = _to_dedx_ev_nm(ion_eloss, N_CM3_WATER)
        ion_imfp = _to_inverse_mfp_nm(ion_sigma_grid, N_CM3_WATER)
        zeros = np.zeros_like(energy_grid)
        return {
            "label": "Geant4-DNA water (Rudd ion.)",
            "ice_type": "water",
            "source_model": "G4DNARuddIonisationModel alpha++ ionisation",
            "density_g_cm3": WATER_DENSITY_G_CM3,
            "emin": float(np.min(ion_energy)),
            "emax": float(np.max(ion_energy)),
            "dedx_exc": zeros,
            "dedx_ion": ion_dedx,
            "dedx_total": ion_dedx,
            "imfp_exc": zeros,
            "imfp_ion": ion_imfp,
            "imfp_total": ion_imfp,
        }

    paths = _water_born_paths(projectile_key)
    if paths is None:
        return None

    exc_energy, exc_components = _load_component_sigma_table(paths["exc_total"])
    exc_n = min(exc_components.shape[1], WATER_EXCITATION_ENERGIES_EV.size)
    exc_components = exc_components[:, :exc_n]
    exc_levels = WATER_EXCITATION_ENERGIES_EV[:exc_n]
    exc_sigma = np.sum(exc_components, axis=1)
    exc_eloss = np.sum(exc_components * exc_levels[None, :], axis=1)

    ion_energy, ion_sigma, ion_eloss = _dcs_moments_table(
        paths["ion_dcs"],
        projectile_mass_au,
        stopping_cutoff,
        drop_kshell=not include_kshell,
    )

    exc_dedx = _to_dedx_ev_nm(_interp_loglog(exc_energy, exc_eloss, energy_grid), N_CM3_WATER)
    ion_dedx = _to_dedx_ev_nm(_interp_loglog(ion_energy, ion_eloss, energy_grid), N_CM3_WATER)
    exc_imfp = _to_inverse_mfp_nm(_interp_loglog(exc_energy, exc_sigma, energy_grid), N_CM3_WATER)
    ion_imfp = _to_inverse_mfp_nm(_interp_loglog(ion_energy, ion_sigma, energy_grid), N_CM3_WATER)

    return {
        "label": "Geant4-DNA water",
        "ice_type": "water",
        "density_g_cm3": WATER_DENSITY_G_CM3,
        "emin": max(float(np.min(exc_energy)), float(np.min(ion_energy))),
        "emax": min(float(np.max(exc_energy)), float(np.max(ion_energy))),
        "dedx_exc": exc_dedx,
        "dedx_ion": ion_dedx,
        "dedx_total": exc_dedx + ion_dedx,
        "imfp_exc": exc_imfp,
        "imfp_ion": ion_imfp,
        "imfp_total": exc_imfp + ion_imfp,
    }


def _draw_manual_legend(ax, handles, labels) -> None:
    if not handles:
        return
    ncols = 2 if len(handles) > 4 else 1
    nrows = max(1, (len(handles) + ncols - 1) // ncols)
    fontsize = 18 if len(handles) > 4 else 22
    if nrows > 1:
        y_top, y_bottom = (0.55, 0.02) if ncols == 1 else (0.82, 0.18)
        y_values = np.linspace(y_top, y_bottom, nrows)
    else:
        y_values = np.array([0.5])
    col_width = 1.0 / ncols

    for idx, (handle, label) in enumerate(zip(handles, labels)):
        row = idx // ncols
        col = idx % ncols
        x0 = 0.40 if ncols == 1 else 0.04 + col * col_width
        y = float(y_values[row])
        line_x0 = x0
        line_x1 = x0 + 0.09
        text_x = x0 + 0.115
        ax.plot(
            [line_x0, line_x1],
            [y, y],
            transform=ax.transAxes,
            color=handle.get_color(),
            linestyle=handle.get_linestyle(),
            linewidth=handle.get_linewidth(),
            solid_capstyle="butt",
            clip_on=False,
        )
        ax.text(
            text_x,
            y,
            str(label),
            transform=ax.transAxes,
            ha="left",
            va="center",
            fontsize=fontsize,
            family=FONT_COURIER,
            clip_on=False,
        )


def _plot(
    energy_grid: np.ndarray,
    series: list[dict],
    units: str,
    projectile_key: str,
    projectile_axis_label: str,
    out_path: Path,
) -> None:
    expected_legend_count = len(series)
    if _load_icru_stopping_power(projectile_key) is not None:
        expected_legend_count += 1
    expected_legend_cols = 2 if expected_legend_count > 4 else 1
    expected_legend_rows = max(1, (expected_legend_count + expected_legend_cols - 1) // expected_legend_cols)
    legend_height_ratio = max(1.35, 0.62 * expected_legend_rows)
    fig_height = max(11.8, 10.4 + 0.68 * expected_legend_rows)

    fig = plt.figure(figsize=(10, fig_height))
    gs = fig.add_gridspec(
        4,
        1,
        height_ratios=[3.0, 0.9, 2.0, legend_height_ratio],
        hspace=0.15,
    )
    ax_sp = fig.add_subplot(gs[0, 0])
    ax_res = fig.add_subplot(gs[1, 0], sharex=ax_sp)
    ax_imfp = fig.add_subplot(gs[2, 0], sharex=ax_sp)
    ax_legend = fig.add_subplot(gs[3, 0])
    ax_legend.axis("off")
    ax_sp.tick_params(labelbottom=False)
    ax_res.tick_params(labelbottom=False)

    styles = {
        "amorphous": {"color": "SlateGray", "ls": "--"},
        "hexagonal": {"color": "0.55", "ls": "-"},
        "water": {"color": "#0072B2", "ls": "-."},
    }
    xmins = []
    xmaxs = []
    icru_curve = _load_icru_stopping_power(projectile_key)
    icru_energy = None
    icru_y = None
    icru_y_grid = None
    if icru_curve is not None:
        icru_energy, icru_mass_sp = icru_curve
        icru_y = _icru_mass_stopping_to_units(units, icru_mass_sp)
        icru_y_grid = _interp_loglog(icru_energy, icru_y, energy_grid)

    for item in series:
        item_energy = np.asarray(item.get("energy_eV", energy_grid), dtype=float)
        density = float(item["density_g_cm3"])
        y_sp, ylabel = _units_and_label(units, density, item["dedx_total"])
        y_imfp = item["imfp_total"]
        valid_sp = np.isfinite(item_energy) & (item_energy > 0.0) & np.isfinite(y_sp) & (y_sp > 0.0)
        valid_imfp = np.isfinite(item_energy) & (item_energy > 0.0) & np.isfinite(y_imfp) & (y_imfp > 0.0)
        emin = item.get("emin")
        emax = item.get("emax")
        if emin is not None:
            valid_sp &= item_energy >= float(emin)
            valid_imfp &= item_energy >= float(emin)
        if emax is not None:
            valid_sp &= item_energy <= float(emax)
            valid_imfp &= item_energy <= float(emax)
        valid_any = valid_sp | valid_imfp
        if np.any(valid_any):
            xmins.append(float(np.min(item_energy[valid_any])))
            xmaxs.append(float(np.max(item_energy[valid_any])))
        style = dict(styles.get(item["ice_type"], {"color": "0.5", "ls": "-"}))
        if item.get("charge_scaling") in {"zeff_born_only", "zeff_decomposed_born_plus_barkas"}:
            style["color"] = "#D55E00"
        if item.get("table_semantics") == "barkas_correction_only":
            style["color"] = "#CC79A7"
            style["ls"] = ":"
        ax_sp.loglog(
            item_energy[valid_sp],
            y_sp[valid_sp],
            color=style["color"],
            ls=style["ls"],
            linewidth=3,
            label=item["label"],
        )
        ax_imfp.loglog(
            item_energy[valid_imfp],
            y_imfp[valid_imfp],
            color=style["color"],
            ls=style["ls"],
            linewidth=3,
            label=item["label"],
        )
        if icru_y_grid is not None and item.get("ice_type") in {"amorphous", "hexagonal"}:
            icru_y_item = _interp_loglog(icru_energy, icru_y, item_energy)
            residual = (y_sp / icru_y_item) - 1.0
            valid_res = (
                valid_sp
                & np.isfinite(icru_y_item)
                & (icru_y_item > 0.0)
                & np.isfinite(residual)
            )
            if np.any(valid_res):
                ax_res.semilogx(
                    item_energy[valid_res],
                    residual[valid_res],
                    color=style["color"],
                    ls=style["ls"],
                    linewidth=2.4,
                )

    if icru_energy is not None and icru_y is not None:
        valid_icru = (
            np.isfinite(icru_energy)
            & np.isfinite(icru_y)
            & (icru_energy >= float(np.min(energy_grid)))
            & (icru_energy <= float(np.max(energy_grid)))
            & (icru_y > 0.0)
        )
        if np.any(valid_icru):
            ax_sp.loglog(
                icru_energy[valid_icru],
                icru_y[valid_icru],
                color="black",
                ls=":",
                linewidth=3,
                label=_icru_label(projectile_key),
                zorder=4,
            )

    ax_sp.set_ylabel(ylabel)
    ax_res.axhline(0.0, color="black", linewidth=1.0, alpha=0.7)
    ax_res.set_ylabel(r"$\Delta_{\rm ICRU}$")
    ax_res.set_yscale("symlog", base=10.0, linthresh=0.1, linscale=1.0)
    ax_imfp.set_ylabel(r"IMFP (nm$^{-1}$)")
    ax_imfp.set_xlabel(f"{projectile_axis_label} energy ($T$; eV)")
    if xmins and xmaxs:
        ax_imfp.set_xlim(float(np.min(xmins)), float(np.max(xmaxs)))
    else:
        ax_imfp.set_xlim(float(np.min(energy_grid)), float(np.max(energy_grid)))
    for ax in (ax_sp, ax_res, ax_imfp):
        ax.xaxis.set_major_locator(LogLocator(base=10.0, subs=(1.0,), numticks=50))
        ax.xaxis.set_major_formatter(LogFormatterMathtext(base=10.0))
        ax.xaxis.set_minor_locator(
            LogLocator(base=10.0, subs=np.arange(2, 10) * 0.1, numticks=100)
        )
        ax.xaxis.set_minor_formatter(NullFormatter())
    for ax in (ax_sp, ax_imfp):
        ax.yaxis.set_major_locator(LogLocator(base=10.0, subs=(1.0,), numticks=50))
        ax.yaxis.set_major_formatter(LogFormatterMathtext(base=10.0))

    handles, labels = ax_sp.get_legend_handles_labels()
    fig.subplots_adjust(left=0.30, right=0.98, top=0.97, bottom=0.05)
    legend_pos = ax_legend.get_position()
    ax_legend.set_position([0.04, legend_pos.y0, 0.92, legend_pos.height])
    _draw_manual_legend(ax_legend, handles, labels)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, bbox_inches="tight", pad_inches=0.35)
    fig.show()
    print(f"Saved plot to: {out_path}")


def _json_array(values: np.ndarray) -> list[float | None]:
    arr = np.asarray(values, dtype=float)
    return [float(v) if np.isfinite(v) else None for v in arr]


def _series_to_json(item: dict, energy_grid: np.ndarray, units: str) -> dict:
    item_energy = np.asarray(item.get("energy_eV", energy_grid), dtype=float)
    density = float(item["density_g_cm3"])
    sp_total, sp_label = _units_and_label(units, density, item["dedx_total"])
    sp_exc, _ = _units_and_label(units, density, item["dedx_exc"])
    sp_ion, _ = _units_and_label(units, density, item["dedx_ion"])
    dedx_dcs_total = np.asarray(item.get("dedx_dcs_total", item["dedx_total"]), dtype=float)
    dedx_bloch = np.asarray(item.get("dedx_bloch", np.zeros_like(dedx_dcs_total)), dtype=float)
    dedx_stopping_total = np.asarray(item.get("dedx_stopping_total", item["dedx_total"]), dtype=float)
    sp_dcs_total, _ = _units_and_label(units, density, dedx_dcs_total)
    sp_bloch, _ = _units_and_label(units, density, dedx_bloch)
    sp_stopping_total, _ = _units_and_label(units, density, dedx_stopping_total)
    dedx_simulation_total = item.get("dedx_simulation_total")
    sp_simulation_total = None
    if dedx_simulation_total is not None:
        dedx_simulation_total = np.asarray(dedx_simulation_total, dtype=float)
        sp_simulation_total, _ = _units_and_label(units, density, dedx_simulation_total)
    payload = {
        "label": item["label"],
        "material": item["ice_type"],
        "density_g_cm3": density,
        "valid_energy_eV": {
            "min": float(item["emin"]),
            "max": float(item["emax"]),
        },
        "energy_eV": _json_array(item_energy),
        "stopping_power": {
            "units": sp_label,
            "total": _json_array(sp_total),
            "excitation": _json_array(sp_exc),
            "ionisation": _json_array(sp_ion),
            "dcs_total": _json_array(sp_dcs_total),
            "bloch": _json_array(sp_bloch),
            "stopping_total": _json_array(sp_stopping_total),
        },
        "dedx_ev_nm": {
            "total": _json_array(item["dedx_total"]),
            "excitation": _json_array(item["dedx_exc"]),
            "ionisation": _json_array(item["dedx_ion"]),
            "dcs_total": _json_array(dedx_dcs_total),
            "bloch": _json_array(dedx_bloch),
            "stopping_total": _json_array(dedx_stopping_total),
        },
        "imfp_nm_inv": {
            "total": _json_array(item["imfp_total"]),
            "excitation": _json_array(item["imfp_exc"]),
            "ionisation": _json_array(item["imfp_ion"]),
        },
    }
    if sp_simulation_total is not None and dedx_simulation_total is not None:
        payload["stopping_power"]["simulation_uncorrected"] = _json_array(sp_simulation_total)
        payload["dedx_ev_nm"]["simulation_uncorrected"] = _json_array(dedx_simulation_total)
    if item.get("source_model"):
        payload["source_model"] = str(item["source_model"])
    if item.get("stopping_source"):
        payload["stopping_source"] = str(item["stopping_source"])
    if item.get("simulation_cache"):
        payload["simulation_cache"] = str(item["simulation_cache"])
    if "simulation_barkas_dcs" in item:
        payload["simulation_barkas_dcs"] = item["simulation_barkas_dcs"]
    if "simulation_charge_exchange" in item:
        payload["simulation_charge_exchange"] = item["simulation_charge_exchange"]
    if item.get("cross_section_tables"):
        payload["cross_section_tables"] = str(item["cross_section_tables"])
    if item.get("table_semantics"):
        payload["table_semantics"] = str(item["table_semantics"])
    if item.get("charge_scaling"):
        payload["charge_scaling"] = str(item["charge_scaling"])
    payload["barkas_difference_used"] = bool(item.get("barkas_difference_used", False))
    if item.get("warnings"):
        payload["warnings"] = list(item["warnings"])
    if item.get("charge_correction"):
        payload["charge_correction"] = str(item["charge_correction"])
        payload["projectile_charge_bare"] = float(item.get("projectile_charge_bare", np.nan))
        payload["zeff_scale_min"] = float(item.get("zeff_scale_min", np.nan))
        payload["zeff_scale_max"] = float(item.get("zeff_scale_max", np.nan))
    payload["include_bloch_stopping"] = bool(item.get("include_bloch_stopping", False))
    payload["bloch_charge_mode"] = str(item.get("bloch_charge_mode", "none"))
    payload["bloch_diagnostics"] = {
        "min_ev_nm": item.get("bloch_min_ev_nm"),
        "max_ev_nm": item.get("bloch_max_ev_nm"),
        "min_fraction_of_dcs": item.get("bloch_min_fraction_of_dcs"),
        "max_fraction_of_dcs": item.get("bloch_max_fraction_of_dcs"),
        "interaction_charge_min": item.get("bloch_interaction_charge_min"),
        "interaction_charge_max": item.get("bloch_interaction_charge_max"),
    }
    return payload


def _ratios_at_energies(
    energy_grid: np.ndarray,
    series: list[dict],
    units: str,
    projectile_key: str,
) -> list[dict]:
    points_eV = np.asarray([1.0e6, 3.0e6, 1.0e7], dtype=float)
    water = next((item for item in series if item.get("ice_type") == "water"), None)
    icru_curve = _load_icru_stopping_power(projectile_key)
    icru_y = None
    icru_energy = None
    if icru_curve is not None:
        icru_energy, icru_mass_sp = icru_curve
        icru_y = _icru_mass_stopping_to_units(units, icru_mass_sp)

    water_sp = None
    water_imfp = None
    if water is not None:
        water_energy = np.asarray(water.get("energy_eV", energy_grid), dtype=float)
        water_sp = _units_and_label(units, float(water["density_g_cm3"]), water["dedx_total"])[0]
        water_imfp = np.asarray(water["imfp_total"], dtype=float)
    material_counts = {
        str(item.get("ice_type")): sum(str(other.get("ice_type")) == str(item.get("ice_type")) for other in series)
        for item in series
    }
    icru_ratio_key = "stopping_power_over_icru73_water" if projectile_key == "oxygen" else "stopping_power_over_icru90_water"

    rows = []
    for point in points_eV:
        row = {"energy_eV": float(point), "energy_MeV": float(point / 1.0e6), "materials": {}}
        water_sp_point = None
        water_imfp_point = None
        if water_sp is not None:
            water_sp_point = float(_interp_loglog(water_energy, water_sp, np.asarray([point]))[0])
            water_imfp_point = float(_interp_loglog(water_energy, water_imfp, np.asarray([point]))[0])
        icru_point = None
        if icru_energy is not None and icru_y is not None:
            icru_point = float(_interp_loglog(icru_energy, icru_y, np.asarray([point]))[0])

        for item in series:
            item_energy = np.asarray(item.get("energy_eV", energy_grid), dtype=float)
            sp = _units_and_label(units, float(item["density_g_cm3"]), item["dedx_total"])[0]
            imfp = np.asarray(item["imfp_total"], dtype=float)
            sp_point = float(_interp_loglog(item_energy, sp, np.asarray([point]))[0])
            imfp_point = float(_interp_loglog(item_energy, imfp, np.asarray([point]))[0])
            entry = {
                "label": str(item.get("label", item["ice_type"])),
                "stopping_power": sp_point if sp_point > 0.0 else None,
                "imfp_nm_inv": imfp_point if imfp_point > 0.0 else None,
            }
            if item.get("charge_correction"):
                entry["charge_correction"] = str(item["charge_correction"])
            if item.get("cross_section_tables"):
                entry["cross_section_tables"] = str(item["cross_section_tables"])
            if item.get("table_semantics"):
                entry["table_semantics"] = str(item["table_semantics"])
            if item.get("charge_scaling"):
                entry["charge_scaling"] = str(item["charge_scaling"])
            if item.get("stopping_source"):
                entry["stopping_source"] = str(item["stopping_source"])
            entry["barkas_difference_used"] = bool(item.get("barkas_difference_used", False))
            if item.get("warnings"):
                entry["warnings"] = list(item["warnings"])
            if water_sp_point is not None and water_sp_point > 0.0:
                entry["stopping_power_over_geant4dna_water"] = sp_point / water_sp_point
            if icru_point is not None and icru_point > 0.0:
                entry[icru_ratio_key] = sp_point / icru_point
            if water_imfp_point is not None and water_imfp_point > 0.0:
                entry["imfp_over_geant4dna_water"] = imfp_point / water_imfp_point
            material_key = str(item["ice_type"])
            if material_counts.get(material_key, 0) > 1:
                material_key = (
                    f"{material_key}_{entry.get('table_semantics', 'reference')}_"
                    f"{entry.get('charge_scaling', 'reference')}"
                )
            row["materials"][material_key] = entry
        rows.append(row)
    return rows


def _write_json_output(
    json_path: Path,
    energy_grid: np.ndarray,
    series: list[dict],
    units: str,
    projectile_key: str,
    projectile_axis_label: str,
    stopping_cutoff: str,
    include_kshell: bool,
    include_water: bool,
    barkas_zeff: bool,
    include_bloch_stopping: bool,
    cross_section_set: str,
    cross_section_set_requested: str,
    stopping_source: str = "cross_sections",
    simulation_root: str | None = None,
) -> None:
    is_simulation_source = stopping_source == "simulation"
    icru = None
    icru_curve = _load_icru_stopping_power(projectile_key)
    if icru_curve is not None:
        icru_energy, icru_mass_sp = icru_curve
        icru_y = _icru_mass_stopping_to_units(units, icru_mass_sp)
        valid = (
            np.isfinite(icru_energy)
            & np.isfinite(icru_y)
            & (icru_energy >= float(np.min(energy_grid)))
            & (icru_energy <= float(np.max(energy_grid)))
            & (icru_y > 0.0)
        )
        icru = {
            "label": _icru_label(projectile_key),
            "energy_eV": _json_array(icru_energy[valid]),
            "mass_stopping_power_MeV_cm2_g": _json_array(icru_mass_sp[valid]),
            "stopping_power_selected_units": _json_array(icru_y[valid]),
        }

    payload = {
        "metadata": {
            "projectile": projectile_key,
            "projectile_axis_label": projectile_axis_label,
            "units": units,
            "stopping_cutoff": stopping_cutoff,
            "include_kshell": bool(include_kshell),
            "include_water": bool(include_water),
            "barkas_zeff": bool(barkas_zeff),
            "barkas_zeff_formula": (
                "not_applicable"
                if is_simulation_source
                else "Zeff = Z * (1 - exp(-125 * beta * Z^(-2/3)))"
            ),
            "include_bloch_stopping": bool(include_bloch_stopping),
            "bloch_formula": (
                (
                    "Delta_L = psi(1) - Re psi(1+i eta) = "
                    "-sum eta^2/[n*(n^2+eta^2)]"
                )
                if include_bloch_stopping
                else "not_applied"
            ),
            "bloch_stopping_cross_section": (
                "S_Bloch = 4*pi*r_e^2*m_e*c^2*Z_H2O*(q^2/beta^2)*Delta_L"
                if include_bloch_stopping
                else "not_applied"
            ),
            "bloch_applied_to": (
                "simulation_derived_stopping_power_only"
                if is_simulation_source and include_bloch_stopping
                else "stopping_power_only"
                if include_bloch_stopping
                else "not_applied"
            ),
            "bloch_does_not_modify": ["DCS", "TCS", "IMFP", "CDF", "Geant4 sampling"],
            "bloch_charge_mode": (
                "none"
                if not include_bloch_stopping
                else "bare_charge"
                if is_simulation_source
                else "effective_charge"
                if barkas_zeff
                else "bare_charge"
            ),
            "cross_section_set": "none" if is_simulation_source else str(cross_section_set),
            "cross_section_set_requested": (
                "not_applicable" if is_simulation_source else str(cross_section_set_requested)
            ),
            "stopping_source": str(stopping_source),
            "simulation_root": str(simulation_root) if simulation_root else None,
            "simulation_barkas_dcs": (
                series[0].get("simulation_barkas_dcs") if is_simulation_source else None
            ),
            "simulation_charge_exchange": (
                series[0].get("simulation_charge_exchange") if is_simulation_source else None
            ),
            "barkas_dcs": (str(cross_section_set) == "both" and not is_simulation_source),
            "barkas_dcs_table_semantics": (
                "not_applicable"
                if is_simulation_source
                else "born_plus_barkas_corrected_total"
            ),
            "energy_grid_count": int(np.asarray(energy_grid).size),
        },
        "energy_eV": _json_array(energy_grid),
        "series": [_series_to_json(item, energy_grid, units) for item in series],
        "icru90_water": icru,
        "ratios_at_1_3_10_MeV": _ratios_at_energies(energy_grid, series, units, projectile_key),
    }
    json_path.parent.mkdir(parents=True, exist_ok=True)
    with open(json_path, "w") as handle:
        json.dump(payload, handle, indent=2)
    print(f"Saved JSON data to: {json_path}")


def _config_csv(value: object) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, (list, tuple)):
        return ",".join(str(item) for item in value)
    return str(value)


def _config_bool(value: object, default: bool = False) -> bool:
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() not in {"0", "false", "no", "off"}


def _cli_bool_value(value: object) -> bool:
    if isinstance(value, bool):
        return value
    text = str(value).strip().lower()
    if text in {"1", "true", "yes", "on"}:
        return True
    if text in {"0", "false", "no", "off"}:
        return False
    raise argparse.ArgumentTypeError(f"Expected true/false value, got {value!r}.")


def _normalize_cross_section_set(value: str) -> str:
    mode = str(value).strip().lower()
    return mode


def _config_optional_bool(config: dict[str, object], *keys: str) -> bool | None:
    for key in keys:
        if key in config:
            return _config_bool(config.get(key), False)
    return None


def _simulation_run_flags(root_arg: str | Path) -> dict[str, bool | None]:
    """Read Barkas-DCS and charge-exchange settings recorded in ROOT config."""
    requested = {"barkas_dcs", "charge_exchange"}
    raw_values: dict[str, set[str]] = {key: set() for key in requested}
    for path in resolve_root_paths(root_arg):
        with uproot.open(path) as handle:
            if "config" not in handle:
                continue
            config = handle["config"]
            if "key" not in config.keys() or "value" not in config.keys():
                continue
            arrays = config.arrays(["key", "value"], library="np")
            for key, value in zip(arrays["key"], arrays["value"], strict=False):
                key_text = key.decode() if isinstance(key, bytes) else str(key)
                if key_text not in requested:
                    continue
                value_text = value.decode() if isinstance(value, bytes) else str(value)
                raw_values[key_text].add(value_text.strip().lower())

    result: dict[str, bool | None] = {}
    for key in sorted(requested):
        values = raw_values[key]
        if not values:
            print(
                f"WARNING: ROOT config does not record {key}; "
                "the simulation filename will mark it as unknown."
            )
            result[key] = None
            continue
        try:
            normalized = {_cli_bool_value(value) for value in values}
        except argparse.ArgumentTypeError as exc:
            raise RuntimeError(
                f"ROOT config has an invalid {key} value: {sorted(values)}"
            ) from exc
        if len(normalized) != 1:
            raise RuntimeError(
                f"ROOT inputs mix incompatible {key} settings: {sorted(values)}"
            )
        result[key] = normalized.pop()
    return result


def _simulation_flag_tag(value: bool | None) -> str:
    if value is None:
        return "unknown"
    return "1" if value else "0"


def _simulation_physics_filename_tag(series: dict, include_bloch_stopping: bool) -> str:
    tag = (
        "simulation_root_"
        f"Barkas-{_simulation_flag_tag(series.get('simulation_barkas_dcs'))}_"
        f"CE-{_simulation_flag_tag(series.get('simulation_charge_exchange'))}"
    )
    if include_bloch_stopping:
        tag += "_blochSP"
    return tag


def _build_simulation_series(
    root_arg: str | Path,
    projectile_key: str,
    ice_type: str,
    emin_eV: float,
    emax_eV: float,
    nbins: int,
    rho_ice: float | None,
    rebuild_cache: bool = False,
) -> dict:
    """Build a projectile plot series from ROOT step energy loss, not DCS moments."""
    if projectile_key not in ROOT_ION_CONFIGS:
        supported = ", ".join(sorted(ROOT_ION_CONFIGS))
        raise ValueError(
            f"ROOT-derived projectile stopping is not configured for {projectile_key!r}; "
            f"supported ROOT particle keys are: {supported}."
        )
    root_text = str(root_arg)
    root_path = Path(root_text).expanduser()
    if not root_path.is_absolute():
        root_path = PROJECT_ROOT / root_path
    root_text = str(root_path)
    _validate_simulation_projectile(root_text, projectile_key)
    simulation_flags = _simulation_run_flags(root_text)

    density = float(rho_ice) if rho_ice is not None else float(ICE_DENSITY_BY_TYPE[ice_type])
    n_cm3 = N_CM3_WATER * (density / WATER_DENSITY_G_CM3)
    step_size = "100 MB"
    cache = _simulation_cache_default_path(
        root_text,
        projectile_key,
        ice_type,
        float(emin_eV),
        float(emax_eV),
        int(nbins),
    )
    if cache.exists() and not rebuild_cache:
        data, cache_meta = _load_simulation_cache(
            cache,
            projectile_key,
            ice_type,
            float(emin_eV),
            float(emax_eV),
            int(nbins),
        )
        print(f"Loaded ROOT simulation cache: {cache}")
        root_text = str(cache_meta.get("root", root_text))
    else:
        if cache.exists() and rebuild_cache:
            print(f"Rebuilding ROOT simulation cache: {cache}")
        else:
            print(f"Building ROOT simulation cache: {cache}")
        data = _compute_simulation_observables_streaming(
            root_text,
            projectile_key,
            float(emin_eV),
            float(emax_eV),
            int(nbins),
            n_cm3,
            density,
            step_size,
        )
        _write_simulation_cache(
            cache,
            data,
            {
                "root": root_text,
                "projectile": projectile_key,
                "ice_type": ice_type,
                "emin_eV": float(emin_eV),
                "emax_eV": float(emax_eV),
                "nbins": int(nbins),
                "density_g_cm3": density,
                "n_h2o_cm3": n_cm3,
                "step_size": str(step_size),
                "simulation_reducer_version": SIMULATION_REDUCER_VERSION,
                "transport_particle_flags": list(
                    ROOT_ION_CONFIGS[projectile_key].get(
                        "flags", (ROOT_ION_CONFIGS[projectile_key]["flag"],)
                    )
                ),
                "simulation_barkas_dcs": simulation_flags["barkas_dcs"],
                "simulation_charge_exchange": simulation_flags["charge_exchange"],
            },
        )
        print(f"Wrote ROOT simulation cache: {cache}")

    energy = np.asarray(data["energy_eV"], dtype=float)
    dedx_total = np.asarray(data["stopping_power_eV_per_nm"], dtype=float)
    imfp_total = np.asarray(data["inverse_mfp_nm_inv"], dtype=float)
    valid = np.isfinite(energy) & (energy > 0.0) & (
        (np.isfinite(dedx_total) & (dedx_total > 0.0))
        | (np.isfinite(imfp_total) & (imfp_total > 0.0))
    )
    if not np.any(valid):
        raise RuntimeError(f"No finite ROOT-derived stopping/IMFP bins found in {root_text}.")

    zeros = np.zeros_like(energy, dtype=float)
    nan_values = np.full_like(energy, np.nan, dtype=float)
    return {
        "label": f"{ice_type.capitalize()}: simulation",
        "ice_type": ice_type,
        "energy_eV": energy,
        "density_g_cm3": density,
        "source_model": f"ROOT simulation: {root_text}",
        "simulation_cache": str(cache),
        "stopping_source": "simulation_root",
        "simulation_barkas_dcs": simulation_flags["barkas_dcs"],
        "simulation_charge_exchange": simulation_flags["charge_exchange"],
        "cross_section_tables": "none",
        "table_semantics": "simulation_energy_loss_per_path_length",
        "charge_scaling": "simulation_transport",
        "barkas_difference_used": False,
        "include_bloch_stopping": False,
        "bloch_charge_mode": "none",
        "emin": float(np.min(energy[valid])),
        "emax": float(np.max(energy[valid])),
        "dedx_exc": nan_values,
        "dedx_ion": nan_values,
        "dedx_dcs_total": nan_values,
        "dedx_bloch": zeros,
        "dedx_stopping_total": dedx_total,
        "dedx_total": dedx_total,
        "imfp_exc": nan_values,
        "imfp_ion": nan_values,
        "imfp_total": imfp_total,
    }


def _apply_bloch_to_simulation_series(
    series: dict,
    projectile_mass_au: float,
    projectile_charge: float,
) -> dict:
    """Add the stopping-only Bloch term to a ROOT-derived stopping series.

    Existing simulation caches do not retain path length by transported charge
    state.  Consequently this post-processing correction uses the configured
    bare projectile charge, matching the bare-charge cross-section plot path,
    and does not modify the simulated IMFP or event history.
    """
    out = dict(series)
    energy = np.asarray(out["energy_eV"], dtype=float)
    simulation_dedx = np.asarray(out["dedx_total"], dtype=float)
    density = float(out["density_g_cm3"])
    n_cm3 = N_CM3_WATER * (density / WATER_DENSITY_G_CM3)
    interaction_charge = np.full_like(energy, float(projectile_charge), dtype=float)
    bloch_eloss_xs = _bloch_eloss_xs_ev_cm2(
        energy,
        projectile_mass_au,
        interaction_charge,
    )
    bloch_dedx = _to_dedx_ev_nm(bloch_eloss_xs, n_cm3)
    corrected_dedx = simulation_dedx + bloch_dedx

    with np.errstate(divide="ignore", invalid="ignore"):
        bloch_fraction = np.divide(
            bloch_dedx,
            simulation_dedx,
            out=np.full_like(bloch_dedx, np.nan, dtype=float),
            where=np.isfinite(simulation_dedx) & (simulation_dedx != 0.0),
        )

    warnings = list(out.get("warnings", []))
    nonpositive = np.count_nonzero(np.isfinite(corrected_dedx) & (corrected_dedx <= 0.0))
    if nonpositive:
        warnings.append(
            "Bloch-corrected simulation stopping power is non-positive at some energies; "
            "those values are invalid for log plotting."
        )
    too_large = np.count_nonzero(np.isfinite(bloch_fraction) & (np.abs(bloch_fraction) > 1.0))
    if too_large:
        warnings.append(
            "Bloch correction exceeds the simulation-derived stopping magnitude; "
            "the corrected-Bethe expansion may be outside its valid range."
        )
    for warning in warnings:
        print(f"WARNING: {warning}")

    finite_fraction = bloch_fraction[np.isfinite(bloch_fraction)]
    finite_bloch = bloch_dedx[np.isfinite(bloch_dedx)]
    out.update(
        {
            "label": _append_bloch_label(str(out["label"]), True),
            "include_bloch_stopping": True,
            "bloch_charge_mode": "bare_charge",
            "projectile_charge_bare": float(projectile_charge),
            "bloch_interaction_charge_min": float(projectile_charge),
            "bloch_interaction_charge_max": float(projectile_charge),
            "bloch_min_ev_nm": float(np.nanmin(finite_bloch)) if finite_bloch.size else 0.0,
            "bloch_max_ev_nm": float(np.nanmax(finite_bloch)) if finite_bloch.size else 0.0,
            "bloch_min_fraction_of_dcs": (
                float(np.nanmin(finite_fraction)) if finite_fraction.size else None
            ),
            "bloch_max_fraction_of_dcs": (
                float(np.nanmax(finite_fraction)) if finite_fraction.size else None
            ),
            "warnings": warnings,
            "dedx_simulation_total": simulation_dedx,
            "dedx_bloch": bloch_dedx,
            "bloch_eloss_xs_ev_cm2": bloch_eloss_xs,
            "dedx_stopping_total": corrected_dedx,
            "dedx_total": corrected_dedx,
        }
    )
    return out


def _validate_simulation_projectile(root_arg: str | Path, projectile_key: str) -> None:
    """Reject a ROOT/source-projectile mismatch without silently changing datasets."""
    paths = resolve_root_paths(root_arg)
    source_particles: set[str] = set()
    for path in paths:
        with uproot.open(path) as handle:
            if "config" not in handle:
                continue
            config = handle["config"]
            if "key" not in config.keys() or "value" not in config.keys():
                continue
            arrays = config.arrays(["key", "value"], library="np")
            for key, value in zip(arrays["key"], arrays["value"], strict=False):
                key_text = key.decode() if isinstance(key, bytes) else str(key)
                if key_text != "source_particle":
                    continue
                value_text = value.decode() if isinstance(value, bytes) else str(value)
                source_particles.add(value_text.strip().lower())

    if source_particles and projectile_key not in source_particles:
        found = ", ".join(sorted(source_particles))
        raise RuntimeError(
            f"ROOT source particle is {found}, but projectile={projectile_key!r}. "
            f"Set projectile={found!r} or provide a {projectile_key} ROOT file."
        )


def _compute_simulation_observables_streaming(
    root_arg: str | Path,
    particle_key: str,
    emin_eV: float,
    emax_eV: float,
    nbins: int,
    n_h2o_cm3: float,
    density_g_cm3: float,
    step_size: str | int = "100 MB",
) -> dict[str, np.ndarray]:
    """Compute ROOT-derived stopping/IMFP in one streaming pass over step trees."""
    if nbins < 2:
        raise ValueError("Simulation stopping requires nbins >= 2.")
    if emin_eV <= 0.0 or emax_eV <= emin_eV:
        raise ValueError("Simulation stopping requires 0 < emin < emax.")
    cfg = ROOT_ION_CONFIGS[particle_key]
    particle_flags = tuple(int(flag) for flag in cfg.get("flags", (cfg["flag"],)))
    paths = resolve_root_paths(root_arg)
    if not paths:
        raise FileNotFoundError(root_arg)

    required = [
        "flagParticle",
        "flagProcess",
        "kineticEnergy",
        "kineticEnergyDifference",
        "stepLength",
        "vibCrossSection",
    ]
    with uproot.open(paths[0]) as handle:
        if "step" not in handle:
            raise RuntimeError(f"Tree 'step' not found in {paths[0]}.")
        missing = [name for name in required if name not in handle["step"].keys()]
    if missing:
        raise RuntimeError(
            "ROOT step tree is missing full diagnostic branches. "
            "Run the proton macro with /dna/test/setLogMode full. "
            f"Missing: {', '.join(missing)}"
        )

    edges = np.logspace(np.log10(float(emin_eV)), np.log10(float(emax_eV)), int(nbins) + 1)
    centers = np.sqrt(edges[:-1] * edges[1:])
    path_nm = np.zeros(nbins, dtype=float)
    energy_loss_eV = np.zeros(nbins, dtype=float)
    n_inelastic = np.zeros(nbins, dtype=float)
    sigma_exc_sum = np.zeros(nbins, dtype=float)
    sigma_ion_sum = np.zeros(nbins, dtype=float)
    sigma_exc_count = np.zeros(nbins, dtype=float)
    sigma_ion_count = np.zeros(nbins, dtype=float)

    tree_specs = [f"{path}:step" for path in paths]
    chunks = 0
    selected_steps = 0
    available_emin = np.inf
    available_emax = -np.inf
    for chunk in uproot.iterate(tree_specs, required, library="np", step_size=step_size):
        chunks += 1
        flag_particle = np.asarray(chunk["flagParticle"], dtype=int)
        flag_process = np.asarray(chunk["flagProcess"], dtype=int)
        energy = np.asarray(chunk["kineticEnergy"], dtype=float)
        dE = np.asarray(chunk["kineticEnergyDifference"], dtype=float)
        step_nm = np.asarray(chunk["stepLength"], dtype=float)
        macro_xs_cm_inv = np.asarray(chunk["vibCrossSection"], dtype=float)

        particle_family = (
            np.isin(flag_particle, particle_flags)
            & np.isfinite(energy)
            & np.isfinite(dE)
            & np.isfinite(step_nm)
            & np.isfinite(macro_xs_cm_inv)
            & (energy > 0.0)
            & (step_nm > 0.0)
        )
        if np.any(particle_family):
            family_energy = energy[particle_family]
            available_emin = min(available_emin, float(np.min(family_energy)))
            available_emax = max(available_emax, float(np.max(family_energy)))

        ion = (
            particle_family
            & (energy >= float(emin_eV))
            & (energy <= float(emax_eV))
        )
        if not np.any(ion):
            continue

        e = energy[ion]
        bins = np.digitize(e, edges) - 1
        in_range = (bins >= 0) & (bins < nbins)
        if not np.any(in_range):
            continue

        bins = bins[in_range]
        dE_in = np.maximum(dE[ion][in_range], 0.0)
        step_in = step_nm[ion][in_range]
        proc_in = flag_process[ion][in_range]
        macro_in = macro_xs_cm_inv[ion][in_range]
        selected_steps += int(bins.size)

        np.add.at(path_nm, bins, step_in)
        np.add.at(energy_loss_eV, bins, dE_in)

        is_exc = np.isin(proc_in, list(cfg["excitation"]))
        is_ion = np.isin(proc_in, list(cfg["ionisation"]))
        inelastic = is_exc | is_ion
        if np.any(inelastic):
            np.add.at(n_inelastic, bins[inelastic], 1.0)

        micro_in = np.divide(
            macro_in,
            n_h2o_cm3,
            out=np.full_like(macro_in, np.nan, dtype=float),
            where=n_h2o_cm3 > 0.0,
        )
        valid_micro = np.isfinite(micro_in) & (micro_in >= 0.0)
        if np.any(is_exc & valid_micro):
            idx = is_exc & valid_micro
            np.add.at(sigma_exc_sum, bins[idx], micro_in[idx])
            np.add.at(sigma_exc_count, bins[idx], 1.0)
        if np.any(is_ion & valid_micro):
            idx = is_ion & valid_micro
            np.add.at(sigma_ion_sum, bins[idx], micro_in[idx])
            np.add.at(sigma_ion_count, bins[idx], 1.0)

    if selected_steps == 0:
        if np.isfinite(available_emin) and np.isfinite(available_emax):
            raise RuntimeError(
                f"The ROOT file contains {particle_key} charge-state steps only from "
                f"{available_emin:.6g} to {available_emax:.6g} eV, outside the requested "
                f"range {emin_eV:.6g} to {emax_eV:.6g} eV."
            )
        raise RuntimeError(
            f"No {particle_key} charge-state steps in the requested energy range "
            f"{emin_eV:.6g} to {emax_eV:.6g} eV across {len(paths)} ROOT file(s)."
        )

    stopping_eV_per_nm = np.divide(
        energy_loss_eV,
        path_nm,
        out=np.full(nbins, np.nan, dtype=float),
        where=path_nm > 0.0,
    )
    inverse_mfp_nm_inv = np.divide(
        n_inelastic,
        path_nm,
        out=np.full(nbins, np.nan, dtype=float),
        where=path_nm > 0.0,
    )
    imfp_nm = np.divide(
        1.0,
        inverse_mfp_nm_inv,
        out=np.full(nbins, np.nan, dtype=float),
        where=inverse_mfp_nm_inv > 0.0,
    )
    sigma_exc = np.divide(
        sigma_exc_sum,
        sigma_exc_count,
        out=np.full(nbins, np.nan, dtype=float),
        where=sigma_exc_count > 0.0,
    )
    sigma_ion = np.divide(
        sigma_ion_sum,
        sigma_ion_count,
        out=np.full(nbins, np.nan, dtype=float),
        where=sigma_ion_count > 0.0,
    )
    sigma_total = np.nansum(np.vstack([sigma_exc, sigma_ion]), axis=0)
    sigma_total[~np.isfinite(sigma_exc) & ~np.isfinite(sigma_ion)] = np.nan

    print(
        "Streamed ROOT simulation stopping from "
        f"{len(paths)} file(s), {chunks} chunk(s), {selected_steps} selected step(s)."
    )
    return {
        "energy_eV": centers,
        "path_length_nm": path_nm,
        "n_inelastic": n_inelastic,
        "stopping_power_eV_per_nm": stopping_eV_per_nm,
        "stopping_power_eV_per_A": stopping_eV_per_nm * EV_NM_TO_EV_ANG,
        "mass_stopping_power_MeV_cm2_g": (stopping_eV_per_nm * EV_NM_TO_MEV_CM) / density_g_cm3,
        "inverse_mfp_nm_inv": inverse_mfp_nm_inv,
        "imfp_nm": imfp_nm,
        "sigma_excitation_cm2": sigma_exc,
        "sigma_ionisation_cm2": sigma_ion,
        "sigma_total_cm2": sigma_total,
    }


def _simulation_cache_default_path(
    root_arg: str | Path,
    projectile_key: str,
    ice_type: str,
    emin_eV: float,
    emax_eV: float,
    nbins: int,
) -> Path:
    root_stem = Path(str(root_arg)).stem or "root"
    tag = (
        f"{projectile_key}_{ice_type}_"
        f"{emin_eV:.6g}_{emax_eV:.6g}_{int(nbins)}bins_{root_stem}"
    )
    tag = tag.replace("+", "p").replace(".", "p")
    return CROSS_SECTION_PLOTS_DIR / "simulation_cache" / f"simulation_observables_{tag}.npz"


def _write_simulation_cache(path: Path, data: dict[str, np.ndarray], metadata: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {key: np.asarray(value, dtype=float) for key, value in data.items()}
    payload["metadata_json"] = np.asarray(json.dumps(metadata, indent=2))
    np.savez_compressed(path, **payload)


def _load_simulation_cache(
    path: Path,
    projectile_key: str,
    ice_type: str,
    emin_eV: float,
    emax_eV: float,
    nbins: int,
) -> tuple[dict[str, np.ndarray], dict[str, Any]]:
    if not path.exists():
        raise FileNotFoundError(path)
    with np.load(path, allow_pickle=False) as cached:
        if "metadata_json" not in cached:
            raise RuntimeError(f"Simulation cache has no metadata_json field: {path}")
        metadata = json.loads(str(cached["metadata_json"].item()))
        expected = {
            "projectile": str(projectile_key),
            "ice_type": str(ice_type),
            "nbins": int(nbins),
            "simulation_reducer_version": SIMULATION_REDUCER_VERSION,
        }
        for key, value in expected.items():
            if metadata.get(key) != value:
                raise RuntimeError(
                    f"Simulation cache metadata mismatch for {key}: "
                    f"cache={metadata.get(key)!r}, requested={value!r}. "
                    f"Use rebuild_simulation_cache=True to overwrite {path}."
                )
        for key, value in (("emin_eV", float(emin_eV)), ("emax_eV", float(emax_eV))):
            cached_value = float(metadata.get(key, np.nan))
            if not np.isclose(cached_value, value, rtol=1e-12, atol=1e-9):
                raise RuntimeError(
                    f"Simulation cache metadata mismatch for {key}: "
                    f"cache={cached_value:.12g}, requested={value:.12g}. "
                    f"Use rebuild_simulation_cache=True to overwrite {path}."
                )
        data = {
            key: np.asarray(cached[key], dtype=float)
            for key in (
                "energy_eV",
                "path_length_nm",
                "n_inelastic",
                "stopping_power_eV_per_nm",
                "stopping_power_eV_per_A",
                "mass_stopping_power_MeV_cm2_g",
                "inverse_mfp_nm_inv",
                "imfp_nm",
                "sigma_excitation_cm2",
                "sigma_ionisation_cm2",
                "sigma_total_cm2",
            )
            if key in cached
        }
    required = {"energy_eV", "stopping_power_eV_per_nm", "inverse_mfp_nm_inv"}
    missing = sorted(required - set(data))
    if missing:
        raise RuntimeError(f"Simulation cache is missing required arrays {missing}: {path}")
    return data, metadata


def _required_table_sets(cross_section_mode: str, barkas_zeff: bool) -> tuple[str, ...]:
    if cross_section_mode == "bare":
        return ("bare",)
    if cross_section_mode == "both":
        return ("bare", "barkas_dcs")
    raise ValueError(f"Unsupported cross-section set: {cross_section_mode!r}")


def _series_requests(cross_section_mode: str, barkas_zeff: bool) -> list[tuple[str, bool]]:
    if cross_section_mode == "bare":
        if barkas_zeff:
            return [("bare", True)]
        return [("bare", False)]
    if cross_section_mode == "both":
        if barkas_zeff:
            return [("barkas_dcs", True)]
        return [("barkas_dcs", False)]
    raise ValueError(f"Unsupported cross-section set: {cross_section_mode!r}")


def _physics_filename_tag(
    cross_section_mode: str,
    barkas_zeff: bool,
    include_bloch_stopping: bool,
    include_kshell: bool,
    stopping_cutoff: str,
) -> str:
    table_tag = "born_barkas" if cross_section_mode == "both" else "born"
    charge_tag = "zeff" if barkas_zeff else "bareZ"
    bloch_tag = "_blochSP" if include_bloch_stopping else ""
    kshell_tag = "kshell" if include_kshell else "no_kshell"
    cutoff_tag = "" if stopping_cutoff == "none" else f"_{stopping_cutoff}"
    return f"{table_tag}_{charge_tag}{bloch_tag}_{kshell_tag}{cutoff_tag}"


def _print_water_icru_comparison(
    energy_grid: np.ndarray,
    water_series: dict | None,
    projectile_key: str,
    units: str,
) -> None:
    if water_series is None:
        return
    icru_curve = _load_icru_stopping_power(projectile_key)
    if icru_curve is None:
        return
    icru_energy, icru_mass_sp = icru_curve
    icru_y = _icru_mass_stopping_to_units(units, icru_mass_sp)
    target_e = 1.0e6
    if not (float(np.min(energy_grid)) <= target_e <= float(np.max(energy_grid))):
        target_e = float(np.sqrt(float(np.min(energy_grid)) * float(np.max(energy_grid))))
    water_y = _interp_loglog(energy_grid, water_series["dedx_total"], np.asarray([target_e]))[0]
    if units != "ev_nm":
        water_y = _units_and_label(units, WATER_DENSITY_G_CM3, np.asarray([water_y]))[0][0]
    icru_at_e = _interp_loglog(icru_energy, icru_y, np.asarray([target_e]))[0]
    if water_y > 0.0 and icru_at_e > 0.0:
        ratio = water_y / icru_at_e
        print(
            "Geant4-DNA water vs ICRU at "
            f"{target_e / 1.0e6:.6g} MeV: {water_y:.6g} vs {icru_at_e:.6g} "
            f"({ratio:.4g}x)"
        )


def main(config: dict[str, object] | None = None) -> None:
    config = {} if config is None else config
    barkas_dcs_default = _config_optional_bool(config, "barkas_dcs", "Barkas_DCS")
    simulation_stopping_default = _config_optional_bool(
        config,
        "simulation_stopping",
        "Simulation_SP",
    )
    stopping_source_default = str(
        config.get(
            "stopping_source",
            "simulation" if simulation_stopping_default is True else "cross_sections",
        )
    )
    cross_section_set_default = (
        "both"
        if barkas_dcs_default is True
        else "bare"
        if barkas_dcs_default is False
        else str(config.get("cross_section_set", "bare"))
    )
    parser = argparse.ArgumentParser(
        description="Compute projectile stopping power and IMFP from generated DCS tables."
    )
    parser.add_argument(
        "--projectile",
        default=str(config.get("projectile", "proton")),
        help="proton, alpha, carbon, or oxygen",
    )
    parser.add_argument(
        "--emin",
        type=float,
        default=float(config.get("emin", 1.0)),
        help="Minimum energy (eV)",
    )
    parser.add_argument(
        "--emax",
        type=float,
        default=float(config.get("emax", 1.0e8)),
        help="Maximum energy (eV)",
    )
    parser.add_argument(
        "--nbins",
        type=int,
        default=int(config.get("nbins", 500)),
        help="Number of log bins",
    )
    parser.add_argument(
        "--units",
        default=str(config.get("units", "ev_ang")),
        choices=("ev_ang", "ev_nm", "mev_cm", "mev_cm2_g"),
        help="Output units for stopping power.",
    )
    parser.add_argument(
        "--ice-types",
        default=_config_csv(config.get("ice_types", ("amorphous", "hexagonal"))),
        help="Comma-separated ice types to plot (amorphous,hexagonal).",
    )
    parser.add_argument(
        "--rho-ice",
        type=float,
        default=config.get("rho_ice", None),
        help="Override ice density (g/cm^3).",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=config.get("out", None),
        help="Output plot path.",
    )
    parser.add_argument(
        "--json-out",
        type=Path,
        default=config.get("json_out", None),
        help="Output JSON path. Defaults to the plot path with .json suffix.",
    )
    parser.add_argument(
        "--stopping-cutoff",
        default=str(config.get("stopping_cutoff", "none")),
        choices=("none", "wmax_nonrel"),
        help=(
            "Optional stopping-power-only energy-transfer cutoff. "
            "Use wmax_nonrel to test the 2009 heavy-projectile convention; "
            "IMFP/total cross sections are unchanged."
        ),
    )
    parser.add_argument(
        "--stopping-source",
        default=stopping_source_default,
        choices=("cross_sections", "simulation"),
        help=(
            "Source for plotted ice projectile stopping/IMFP: "
            "cross_sections uses generated DCS/TCS tables; simulation uses ROOT step energy loss."
        ),
    )
    parser.add_argument(
        "--simulation-stopping",
        "--Simulation_SP",
        dest="simulation_stopping",
        action=argparse.BooleanOptionalAction,
        default=simulation_stopping_default,
        help="Use ROOT simulation energy loss/path length instead of DCS tables when a ROOT file is available.",
    )
    parser.add_argument(
        "--simulation-root",
        type=Path,
        default=config.get("simulation_root", "dna.root"),
        help="ROOT file or split ROOT glob used when --stopping-source simulation is active.",
    )
    parser.add_argument(
        "--simulation-ice-type",
        default=config.get("simulation_ice_type", None),
        help="Ice type label for the ROOT simulation series; defaults to the first requested ice type.",
    )
    parser.add_argument(
        "--rebuild-simulation-cache",
        dest="rebuild_simulation_cache",
        action=argparse.BooleanOptionalAction,
        default=_config_bool(config.get("rebuild_simulation_cache", False), False),
        help="Force rebuilding the simulation cache from ROOT even if the cache exists.",
    )
    parser.add_argument(
        "--include-water",
        action=argparse.BooleanOptionalAction,
        default=_config_bool(config.get("include_water", True), True),
        help="Overlay Geant4-DNA water stopping/IMFP where native water tables are available.",
    )
    parser.add_argument(
        "--include-kshell",
        action=argparse.BooleanOptionalAction,
        default=_config_bool(config.get("include_kshell", True), True),
        help="Include the last ionisation-table channel as the O K-shell contribution.",
    )
    parser.add_argument(
        "--barkas-zeff",
        "--Barkas_Zeff",
        dest="barkas_zeff",
        action=argparse.BooleanOptionalAction,
        default=_config_bool(config.get("barkas_zeff", config.get("Barkas_Zeff", False)), False),
        help=(
            "Overlay Barkas effective-charge scaling, using "
            "Zeff = Z * (1 - exp(-125 * beta * Z^(-2/3)))."
        ),
    )
    parser.add_argument(
        "--include-bloch-stopping",
        "--bloch-sp",
        "--Bloch_SP",
        dest="include_bloch_stopping",
        nargs="?",
        const=True,
        type=_cli_bool_value,
        default=_config_bool(
            config.get("include_bloch_stopping", config.get("Bloch_SP", False)),
            False,
        ),
        help=(
            "Add the Bloch correction to stopping power only. "
            "DCS/TCS/IMFP/CDF/Geant4 sampling are unchanged."
        ),
    )
    parser.add_argument(
        "--no-include-bloch-stopping",
        "--no-bloch-sp",
        "--no-Bloch_SP",
        dest="include_bloch_stopping",
        action="store_false",
        default=argparse.SUPPRESS,
        help=argparse.SUPPRESS,
    )
    parser.add_argument(
        "--cross-section-set",
        default=cross_section_set_default,
        choices=("bare", "both"),
        help=(
            "Backwards-compatible table selector: bare = Born-only; "
            "both = Born + Barkas corrected total. Prefer --barkas-dcs."
        ),
    )
    parser.add_argument(
        "--barkas-dcs",
        "--Barkas_DCS",
        dest="barkas_dcs",
        nargs="?",
        const=True,
        type=_cli_bool_value,
        default=barkas_dcs_default,
        help="Use Born + Barkas corrected total DCS tables when true; use Born-only tables when false.",
    )
    parser.add_argument(
        "--no-barkas-dcs",
        "--no-Barkas_DCS",
        dest="barkas_dcs",
        action="store_false",
        default=argparse.SUPPRESS,
        help=argparse.SUPPRESS,
    )
    args = parser.parse_args()

    if args.emin <= 0.0 or args.emax <= 0.0 or args.emin >= args.emax:
        raise ValueError("Invalid energy range.")
    if args.barkas_dcs is None:
        cross_section_set_requested = str(args.cross_section_set)
        cross_section_mode = _normalize_cross_section_set(args.cross_section_set)
    else:
        cross_section_set_requested = f"Barkas_DCS={bool(args.barkas_dcs)}"
        cross_section_mode = "both" if bool(args.barkas_dcs) else "bare"
    projectile_key, projectile = _projectile_config(args.projectile)
    projectile_token = str(projectile["file_token"])
    projectile_label = str(projectile["label"])
    projectile_mass_au = float(projectile["mass_au"])
    projectile_charge = float(projectile["charge"])
    projectile_axis_label = PROJECTILE_AXIS_LABELS.get(projectile_key, projectile_key.capitalize())
    ice_types = [v.strip().lower() for v in args.ice_types.split(",") if v.strip()]
    ice_types = [v for v in ice_types if v in ICE_DENSITY_BY_TYPE]
    if not ice_types:
        raise ValueError("No valid ice types specified.")
    series = []
    water_series = None
    simulation_root_used = None
    use_simulation_source = str(args.stopping_source) == "simulation"
    if args.simulation_stopping is not None:
        use_simulation_source = bool(args.simulation_stopping)

    if use_simulation_source:
        sim_ice_type = str(args.simulation_ice_type or ice_types[0]).strip().lower()
        if sim_ice_type not in ICE_DENSITY_BY_TYPE:
            raise ValueError(
                f"Invalid simulation_ice_type={sim_ice_type!r}; "
                f"choose one of {', '.join(ICE_DENSITY_BY_TYPE)}."
            )
        try:
            sim_series = _build_simulation_series(
                args.simulation_root,
                projectile_key,
                sim_ice_type,
                float(args.emin),
                float(args.emax),
                int(args.nbins),
                args.rho_ice,
                bool(args.rebuild_simulation_cache),
            )
            if args.include_bloch_stopping:
                sim_series = _apply_bloch_to_simulation_series(
                    sim_series,
                    projectile_mass_au,
                    projectile_charge,
                )
            series.append(sim_series)
            simulation_root_used = str(args.simulation_root)
            energy = np.asarray(sim_series["energy_eV"], dtype=float)
            print(
                "Using ROOT simulation-derived stopping/IMFP from "
                f"{simulation_root_used} for {sim_ice_type} ice."
            )
        except Exception as exc:
            raise RuntimeError(
                "stopping_source='simulation' was requested, but the ROOT simulation "
                "could not be loaded or did not contain usable proton/ion full-log steps. "
                "No cross-section-table fallback was used. "
                f"simulation_root={args.simulation_root!s}; reason: {exc}"
            ) from exc

    if not series:
        required_table_sets = _required_table_sets(cross_section_mode, args.barkas_zeff)
        series_requests = _series_requests(cross_section_mode, args.barkas_zeff)

        coverage = {}
        for ice_type in ice_types:
            ranges = [
                _plot_energy_range(projectile_token, ice_type, cross_section_set)
                for cross_section_set in required_table_sets
            ]
            coverage[ice_type] = (
                max(bounds[0] for bounds in ranges),
                min(bounds[1] for bounds in ranges),
            )
        domain_emin = max(bounds[0] for bounds in coverage.values())
        domain_emax = min(bounds[1] for bounds in coverage.values())
        plot_emin = max(float(args.emin), domain_emin)
        plot_emax = min(float(args.emax), domain_emax)
        if plot_emin >= plot_emax:
            raise ValueError(
                "Requested energy range does not overlap the generated projectile "
                f"cross-section domain ({domain_emin:.6g} to {domain_emax:.6g} eV)."
            )
        if plot_emin != args.emin or plot_emax != args.emax:
            print(
                "Using projectile generated-energy domain "
                f"{plot_emin:.6g} to {plot_emax:.6g} eV "
                "(from the available table files)."
            )

        energy = np.logspace(np.log10(plot_emin), np.log10(plot_emax), args.nbins)
        for ice_type in ice_types:
            for series_set, use_zeff in series_requests:
                series.append(
                    _build_series(
                        projectile_token,
                        projectile_label,
                        projectile_mass_au,
                        projectile_charge,
                        ice_type,
                        energy,
                        args.rho_ice,
                        args.stopping_cutoff,
                        args.include_kshell,
                        use_zeff,
                        args.include_bloch_stopping,
                        series_set,
                    )
                )

    actual_stopping_source = "simulation" if simulation_root_used else "cross_sections"
    if actual_stopping_source == "simulation" and (
        args.barkas_zeff
        or cross_section_mode != "bare"
    ):
        print(
            "Simulation stopping source selected: ignoring Barkas_Zeff, Barkas_DCS, "
            "and cross-section table selectors in the plotter."
        )
    if actual_stopping_source == "simulation" and args.include_bloch_stopping:
        print(
            "Applied the bare-charge Bloch stopping correction to the ROOT-derived "
            "stopping power; simulation IMFP is unchanged."
        )
    if args.include_water and actual_stopping_source == "cross_sections":
        water_series = _build_water_series(
            projectile_key,
            projectile_mass_au,
            energy,
            args.stopping_cutoff,
            args.include_kshell,
        )
        if water_series is not None:
            series.append(water_series)
        else:
            print(f"No Geant4-DNA water Born table overlay is available for {projectile_key}.")
    elif args.include_water and actual_stopping_source == "simulation":
        print("Skipping Geant4-DNA water table overlay because stopping_source=simulation.")

    out_path = args.out
    if out_path is None:
        if actual_stopping_source == "simulation":
            ice_suffix = str(series[0].get("ice_type", "_".join(ice_types)))
            physics_tag = _simulation_physics_filename_tag(
                series[0],
                args.include_bloch_stopping,
            )
        else:
            ice_suffix = "_".join(ice_types)
            physics_tag = _physics_filename_tag(
                cross_section_mode,
                args.barkas_zeff,
                args.include_bloch_stopping,
                args.include_kshell,
                args.stopping_cutoff,
            )
        out_path = (
            CROSS_SECTION_PLOTS_DIR
            / (
                f"stopping_power_imfp_{projectile_key}_{ice_suffix}_ice_"
                f"{physics_tag}.png"
            )
        )

    _plot(
        energy_grid=energy,
        series=series,
        units=args.units,
        projectile_key=projectile_key,
        projectile_axis_label=projectile_axis_label,
        out_path=out_path,
    )
    json_path = args.json_out if args.json_out is not None else out_path.with_suffix(".json")
    _write_json_output(
        json_path=json_path,
        energy_grid=energy,
        series=series,
        units=args.units,
        projectile_key=projectile_key,
        projectile_axis_label=projectile_axis_label,
        stopping_cutoff=args.stopping_cutoff,
        include_kshell=args.include_kshell,
        include_water=args.include_water,
        barkas_zeff=args.barkas_zeff if actual_stopping_source == "cross_sections" else False,
        include_bloch_stopping=args.include_bloch_stopping,
        cross_section_set=cross_section_mode,
        cross_section_set_requested=cross_section_set_requested,
        stopping_source=actual_stopping_source,
        simulation_root=simulation_root_used,
    )
    _print_water_icru_comparison(energy, water_series, projectile_key, args.units)


if __name__ == "__main__":
    RUN_CONFIG = {
        "projectile": "alpha",
        "ice_types": ("amorphous", "hexagonal"),
        "emin": 1.1e5,
        "emax": 1.0e8,
        "nbins": 500,
        "stopping_cutoff": "wmax_nonrel",
        "include_water": True,
        "include_kshell": True,
        "Barkas_Zeff": True,
        "Barkas_DCS": True,
        "Bloch_SP": True,
        # Choose "cross_sections" or "simulation".
        "stopping_source": "simulation",
        # If stopping_source == "simulation", use this ROOT file when it exists.
        "simulation_root": "dna.root",
        "simulation_ice_type": "amorphous",
        # False: read cache if present, build it if missing. True: rebuild from ROOT.
        "rebuild_simulation_cache": True,
    }

    main(RUN_CONFIG)
