#!/usr/bin/env python3
"""
Compute stopping power and inverse mean free path from projectile DCS tables.

This is the projectile analogue of plot_stopping_power_xs.py, but omits the
W-value panel. It expects DCS files generated by generate_ice_cross_sections_ion.py,
for example sigmadiff_excitation_proton_hexagonal_ice_emfietzoglou_kyriakou.dat.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.ticker import LogFormatterMathtext, LogLocator, NullFormatter

PHYSICS_ICE_DIR = Path(__file__).resolve().parents[1] / "physics_ice"
if str(PHYSICS_ICE_DIR) not in sys.path:
    sys.path.insert(0, str(PHYSICS_ICE_DIR))

from constants import (  # noqa: E402
    CROSS_SECTIONS_DIR,
    CUSTOM_DATA_ROOT_GEANT4,
    CUSTOM_DATA_ROOT_PROJECT,
    EMFIETZOGLOU_SCALE_1E16,
    FONT_COURIER,
    FONTSIZE_24,
    ICE_AMORPHOUS_DENSITY_G_CM3,
    ICE_HEXAGONAL_DENSITY_G_CM3,
    N,
    OUTPUT_DIR,
    PROJECTILE_LIBRARY,
    RC_BASE_ELASTIC,
    rcparams_with_fontsize,
)

plt.rcParams["font.family"] = FONT_COURIER
plt.rcParams["mathtext.rm"] = FONT_COURIER
plt.rcParams["mathtext.fontset"] = "custom"
plt.rcParams.update(rcparams_with_fontsize(RC_BASE_ELASTIC, FONTSIZE_24))

CM_PER_NM = 1.0e7
EV_NM_TO_MEV_CM = 10.0
EV_NM_TO_EV_ANG = 0.1
WATER_DENSITY_G_CM3 = 1.0
N_CM3_WATER = N / 1.0e6
GEANT4_DNA_SCALE_CM2 = EMFIETZOGLOU_SCALE_1E16 * 1.0e-16
WATER_EXCITATION_ENERGIES_EV = np.array([8.22, 10.00, 11.24, 12.61, 13.77], dtype=float)
ICE_DENSITY_BY_TYPE = {
    "amorphous": ICE_AMORPHOUS_DENSITY_G_CM3,
    "hexagonal": ICE_HEXAGONAL_DENSITY_G_CM3,
}
PROJECTILE_AXIS_LABELS = {
    "proton": "Proton",
    "alpha": "Alpha",
    "carbon": "Carbon",
}
ICRU_DATA_DIR = Path(__file__).resolve().parent / "data"
ICRU_WATER_DENSITY_G_CM3 = 0.998
ICRU_STOPPING_POWER_FILES = {
    "proton": ICRU_DATA_DIR / "icru90_stopping_power_liquid_water_proton.csv",
    "alpha": ICRU_DATA_DIR / "icru90_stopping_power_liquid_water_alpha.csv",
    "carbon": ICRU_DATA_DIR / "icru90_stopping_power_liquid_water_carbon.csv",
}


def _projectile_config(key: str) -> tuple[str, dict]:
    lookup = str(key).strip().lower()
    for name, cfg in PROJECTILE_LIBRARY.items():
        aliases = cfg.get("aliases", ())
        if lookup == name or lookup in aliases:
            return name, cfg
    supported = ", ".join(PROJECTILE_LIBRARY)
    raise ValueError(f"Unsupported projectile {key!r}; choose one of: {supported}")


def _ensure_exists(path: Path) -> None:
    if not path.exists():
        raise FileNotFoundError(f"Missing required data file: {path}")


def _projectile_paths(projectile_token: str, ice_type: str) -> dict[str, Path]:
    ice_label = f"{ice_type}_ice"
    return {
        "exc_dcs": CROSS_SECTIONS_DIR / (
            f"sigmadiff_excitation_{projectile_token}_{ice_label}_emfietzoglou_kyriakou.dat"
        ),
        "ion_dcs": CROSS_SECTIONS_DIR / (
            f"sigmadiff_ionisation_{projectile_token}_{ice_label}_emfietzoglou_kyriakou.dat"
        ),
        "exc_total": CROSS_SECTIONS_DIR / (
            f"sigma_excitation_{projectile_token}_{ice_label}_emfietzoglou_kyriakou.dat"
        ),
        "ion_total": CROSS_SECTIONS_DIR / (
            f"sigma_ionisation_{projectile_token}_{ice_label}_emfietzoglou_kyriakou.dat"
        ),
    }


def _find_geant4_dna_file(filename: str) -> Path | None:
    for root in (CUSTOM_DATA_ROOT_GEANT4, CUSTOM_DATA_ROOT_PROJECT):
        dna_dir = root / "G4EMLOW8.6.1" / "dna"
        path = dna_dir / filename
        if path.exists():
            return path
        if root.exists():
            for subdir in sorted(root.glob("G4EMLOW*/dna")):
                path = subdir / filename
                if path.exists():
                    return path
    return None


def _water_born_paths(projectile_key: str) -> dict[str, Path] | None:
    if projectile_key != "proton":
        return None
    names = {
        "exc_total": "sigma_excitation_p_born.dat",
        "ion_dcs": "sigmadiff_ionisation_p_born.dat",
        "ion_total": "sigma_ionisation_p_born.dat",
    }
    paths: dict[str, Path] = {}
    for key, name in names.items():
        path = _find_geant4_dna_file(name)
        if path is None:
            return None
        paths[key] = path
    return paths


def _first_column_bounds(path: Path) -> tuple[float, float]:
    _ensure_exists(path)
    values = np.loadtxt(path, dtype=float, usecols=[0])
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values) & (values > 0.0)]
    if values.size == 0:
        raise ValueError(f"No positive incident-energy values in {path}")
    return float(np.min(values)), float(np.max(values))


def _available_energy_range(projectile_token: str, ice_type: str) -> tuple[float, float]:
    ranges = [_first_column_bounds(path) for path in _projectile_paths(projectile_token, ice_type).values()]
    emin = max(item[0] for item in ranges)
    emax = min(item[1] for item in ranges)
    if emin >= emax:
        raise ValueError(
            f"No common projectile cross-section/DCS energy range for {projectile_token}, {ice_type} ice."
        )
    return emin, emax


def _generator_tlist_range(projectile_token: str, ice_type: str) -> tuple[float, float] | None:
    cache_path = OUTPUT_DIR / f"cross_section_corrections_pwba_{projectile_token}_{ice_type}_ice.npz"
    if not cache_path.exists():
        return None
    data = np.load(cache_path, allow_pickle=True)
    if "T_eV" not in data:
        return None
    values = np.asarray(data["T_eV"], dtype=float)
    values = values[np.isfinite(values) & (values > 0.0)]
    if values.size == 0:
        return None
    return float(np.min(values)), float(np.max(values))


def _plot_energy_range(projectile_token: str, ice_type: str) -> tuple[float, float]:
    tlist_range = _generator_tlist_range(projectile_token, ice_type)
    if tlist_range is not None:
        return tlist_range
    return _available_energy_range(projectile_token, ice_type)


def _simpson_nonuniform(x: np.ndarray, y: np.ndarray) -> float:
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    mask = np.isfinite(x) & np.isfinite(y)
    x = x[mask]
    y = y[mask]
    if x.size < 2:
        return 0.0
    order = np.argsort(x)
    x = x[order]
    y = y[order]
    unique_x, inv = np.unique(x, return_inverse=True)
    if unique_x.size != x.size:
        y_sum = np.zeros_like(unique_x)
        counts = np.zeros_like(unique_x)
        for i, idx in enumerate(inv):
            y_sum[idx] += y[i]
            counts[idx] += 1.0
        x = unique_x
        y = y_sum / np.where(counts == 0.0, 1.0, counts)
    if x.size < 2:
        return 0.0
    if x.size == 2:
        return float(np.trapezoid(y, x))

    total = 0.0
    end = x.size if x.size % 2 == 1 else x.size - 1
    for i in range(0, end - 2, 2):
        x0, x1, x2 = x[i], x[i + 1], x[i + 2]
        y0, y1, y2 = y[i], y[i + 1], y[i + 2]
        h0 = x1 - x0
        h1 = x2 - x1
        if h0 <= 0.0 or h1 <= 0.0:
            continue
        w0 = 2.0 - h1 / h0
        w1 = ((h0 + h1) ** 2) / (h0 * h1)
        w2 = 2.0 - h0 / h1
        total += (h0 + h1) * (w0 * y0 + w1 * y1 + w2 * y2) / 6.0
    if x.size % 2 == 0:
        total += float(np.trapezoid(y[-2:], x[-2:]))
    return float(total)


def _interp_loglog(x: np.ndarray, y: np.ndarray, x_new: np.ndarray) -> np.ndarray:
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    x_new = np.asarray(x_new, dtype=float)
    order = np.argsort(x)
    x = x[order]
    y = y[order]
    positive = (x > 0.0) & (y > 0.0)
    out = np.zeros_like(x_new)
    if np.count_nonzero(positive) < 2:
        return out
    xp = x[positive]
    yp = y[positive]
    mask = (x_new >= xp[0]) & (x_new <= xp[-1])
    out[mask] = 10.0 ** np.interp(
        np.log10(x_new[mask]),
        np.log10(xp),
        np.log10(yp),
    )
    out[~np.isfinite(out)] = 0.0
    return out


def _projectile_wmax_nonrel_eV(tau_eV: float, projectile_mass_au: float) -> float:
    return 4.0 * float(tau_eV) / float(projectile_mass_au)


def _units_and_label(units: str, density: float, dedx: np.ndarray) -> tuple[np.ndarray, str]:
    if units == "ev_ang":
        return dedx * EV_NM_TO_EV_ANG, r"Stopping Power (eV/$\AA$)"
    if units == "mev_cm":
        return dedx * EV_NM_TO_MEV_CM, "Stopping Power (MeV/cm)"
    if units == "mev_cm2_g":
        return (dedx * EV_NM_TO_MEV_CM) / density, "Mass Stopping Power (MeV cm^2/g)"
    return dedx, "Stopping Power (eV/nm)"


def _icru_mass_stopping_to_units(units: str, mass_sp: np.ndarray) -> np.ndarray:
    linear_mev_cm = np.asarray(mass_sp, dtype=float) * ICRU_WATER_DENSITY_G_CM3
    if units == "ev_ang":
        return linear_mev_cm * 0.01
    if units == "mev_cm":
        return linear_mev_cm
    if units == "mev_cm2_g":
        return np.asarray(mass_sp, dtype=float)
    return linear_mev_cm / EV_NM_TO_MEV_CM


def _load_icru_stopping_power(projectile_key: str) -> tuple[np.ndarray, np.ndarray] | None:
    path = ICRU_STOPPING_POWER_FILES.get(projectile_key)
    if path is None or not path.exists():
        return None
    data = np.loadtxt(path, delimiter=",", comments="#", dtype=float)
    data = np.atleast_2d(data)
    energy_eV = data[:, 0] * 1.0e6
    mass_sp = data[:, 1]
    valid = np.isfinite(energy_eV) & np.isfinite(mass_sp) & (energy_eV > 0.0) & (mass_sp > 0.0)
    return energy_eV[valid], mass_sp[valid]


def _load_total_sigma_table(path: Path) -> tuple[np.ndarray, np.ndarray]:
    _ensure_exists(path)
    data = np.loadtxt(path, dtype=float)
    data = np.atleast_2d(data)
    energy = data[:, 0]
    sigma = np.sum(data[:, 1:], axis=1) * GEANT4_DNA_SCALE_CM2
    valid = np.isfinite(energy) & np.isfinite(sigma) & (energy > 0.0)
    return energy[valid], sigma[valid]


def _load_component_sigma_table(path: Path) -> tuple[np.ndarray, np.ndarray]:
    _ensure_exists(path)
    data = np.loadtxt(path, dtype=float)
    data = np.atleast_2d(data)
    energy = data[:, 0]
    sigma_components = data[:, 1:] * GEANT4_DNA_SCALE_CM2
    valid = np.isfinite(energy) & (energy > 0.0) & np.all(np.isfinite(sigma_components), axis=1)
    return energy[valid], sigma_components[valid, :]


def _energy_loss_xs_with_cutoff(
    omega: np.ndarray,
    sigma: np.ndarray,
    cutoff_eV: float | None,
) -> float:
    order = np.argsort(omega)
    omega = np.asarray(omega, dtype=float)[order]
    sigma = np.asarray(sigma, dtype=float)[order]

    if cutoff_eV is None:
        return _simpson_nonuniform(omega, omega * sigma)

    cutoff = float(cutoff_eV)
    if cutoff <= float(np.min(omega)):
        return 0.0

    keep = omega <= cutoff
    x = omega[keep]
    y = sigma[keep]
    if cutoff < float(np.max(omega)) and np.any(omega < cutoff) and np.any(omega > cutoff):
        y_cut = float(np.interp(cutoff, omega, sigma))
        if x.size == 0 or not np.isclose(float(x[-1]), cutoff):
            x = np.append(x, cutoff)
            y = np.append(y, y_cut)
    if x.size < 2:
        return 0.0
    return _simpson_nonuniform(x, x * y)


def _dcs_moments_table(
    path: Path,
    projectile_mass_au: float,
    stopping_cutoff: str,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return incident energy, sigma_total, and energy-loss cross-section."""
    _ensure_exists(path)
    scale_cm2 = GEANT4_DNA_SCALE_CM2
    energies: list[float] = []
    sigma_xs: list[float] = []
    eloss_xs: list[float] = []

    current_e: float | None = None
    transfer_vals: list[float] = []
    sigma_vals: list[list[float]] = []
    n_channels: int | None = None

    def flush() -> None:
        if current_e is None or len(transfer_vals) < 2 or n_channels is None:
            return
        omega = np.asarray(transfer_vals, dtype=float)
        sigma = np.asarray(sigma_vals, dtype=float) * scale_cm2
        cutoff_eV = None
        if stopping_cutoff == "wmax_nonrel":
            cutoff_eV = min(float(current_e), _projectile_wmax_nonrel_eV(float(current_e), projectile_mass_au))
        sigma_sum = 0.0
        eloss_sum = 0.0
        for j in range(n_channels):
            s = sigma[j]
            sigma_sum += _simpson_nonuniform(omega, s)
            eloss_sum += _energy_loss_xs_with_cutoff(omega, s, cutoff_eV)
        energies.append(float(current_e))
        sigma_xs.append(float(sigma_sum))
        eloss_xs.append(float(eloss_sum))

    with open(path, "r") as handle:
        for line in handle:
            if not line.strip():
                continue
            parts = line.split()
            if len(parts) < 3:
                continue
            incident_e = float(parts[0])
            transfer = float(parts[1])
            if n_channels is None:
                n_channels = len(parts) - 2
                sigma_vals = [[] for _ in range(n_channels)]
            if len(parts) < 2 + n_channels:
                continue
            if current_e is None:
                current_e = incident_e
            if incident_e != current_e:
                flush()
                current_e = incident_e
                transfer_vals = []
                sigma_vals = [[] for _ in range(n_channels)]
            transfer_vals.append(transfer)
            for j, value in enumerate(parts[2 : 2 + n_channels]):
                sigma_vals[j].append(float(value))
    flush()

    return (
        np.asarray(energies, dtype=float),
        np.asarray(sigma_xs, dtype=float),
        np.asarray(eloss_xs, dtype=float),
    )


def _to_dedx_ev_nm(eloss_xs: np.ndarray, n_cm3: float) -> np.ndarray:
    return (np.asarray(eloss_xs, dtype=float) * n_cm3) / CM_PER_NM


def _to_inverse_mfp_nm(sigma_xs: np.ndarray, n_cm3: float) -> np.ndarray:
    return (np.asarray(sigma_xs, dtype=float) * n_cm3) / CM_PER_NM


def _build_series(
    projectile_token: str,
    projectile_label: str,
    projectile_mass_au: float,
    ice_type: str,
    energy_grid: np.ndarray,
    rho_ice: float | None,
    stopping_cutoff: str,
) -> dict:
    paths = _projectile_paths(projectile_token, ice_type)
    exc_energy, _, exc_eloss = _dcs_moments_table(paths["exc_dcs"], projectile_mass_au, stopping_cutoff)
    ion_energy, _, ion_eloss = _dcs_moments_table(paths["ion_dcs"], projectile_mass_au, stopping_cutoff)
    exc_sigma_energy, exc_sigma = _load_total_sigma_table(paths["exc_total"])
    ion_sigma_energy, ion_sigma = _load_total_sigma_table(paths["ion_total"])

    phase_density = ICE_DENSITY_BY_TYPE[ice_type]
    density = float(rho_ice) if rho_ice is not None else float(phase_density)
    n_cm3 = N_CM3_WATER * (density / WATER_DENSITY_G_CM3)

    exc_dedx = _to_dedx_ev_nm(_interp_loglog(exc_energy, exc_eloss, energy_grid), n_cm3)
    ion_dedx = _to_dedx_ev_nm(_interp_loglog(ion_energy, ion_eloss, energy_grid), n_cm3)
    exc_imfp = _to_inverse_mfp_nm(_interp_loglog(exc_sigma_energy, exc_sigma, energy_grid), n_cm3)
    ion_imfp = _to_inverse_mfp_nm(_interp_loglog(ion_sigma_energy, ion_sigma, energy_grid), n_cm3)
    emin = max(
        float(np.min(exc_energy)),
        float(np.min(ion_energy)),
        float(np.min(exc_sigma_energy)),
        float(np.min(ion_sigma_energy)),
    )
    emax = min(
        float(np.max(exc_energy)),
        float(np.max(ion_energy)),
        float(np.max(exc_sigma_energy)),
        float(np.max(ion_sigma_energy)),
    )

    return {
        "label": f"{ice_type.capitalize()} ice",
        "ice_type": ice_type,
        "density_g_cm3": density,
        "emin": emin,
        "emax": emax,
        "dedx_exc": exc_dedx,
        "dedx_ion": ion_dedx,
        "dedx_total": exc_dedx + ion_dedx,
        "imfp_exc": exc_imfp,
        "imfp_ion": ion_imfp,
        "imfp_total": exc_imfp + ion_imfp,
    }


def _build_water_series(
    projectile_key: str,
    projectile_mass_au: float,
    energy_grid: np.ndarray,
    stopping_cutoff: str,
) -> dict | None:
    paths = _water_born_paths(projectile_key)
    if paths is None:
        return None

    exc_energy, exc_components = _load_component_sigma_table(paths["exc_total"])
    exc_n = min(exc_components.shape[1], WATER_EXCITATION_ENERGIES_EV.size)
    exc_components = exc_components[:, :exc_n]
    exc_levels = WATER_EXCITATION_ENERGIES_EV[:exc_n]
    exc_sigma = np.sum(exc_components, axis=1)
    exc_eloss = np.sum(exc_components * exc_levels[None, :], axis=1)

    ion_energy, ion_sigma, ion_eloss = _dcs_moments_table(
        paths["ion_dcs"],
        projectile_mass_au,
        stopping_cutoff,
    )

    exc_dedx = _to_dedx_ev_nm(_interp_loglog(exc_energy, exc_eloss, energy_grid), N_CM3_WATER)
    ion_dedx = _to_dedx_ev_nm(_interp_loglog(ion_energy, ion_eloss, energy_grid), N_CM3_WATER)
    exc_imfp = _to_inverse_mfp_nm(_interp_loglog(exc_energy, exc_sigma, energy_grid), N_CM3_WATER)
    ion_imfp = _to_inverse_mfp_nm(_interp_loglog(ion_energy, ion_sigma, energy_grid), N_CM3_WATER)

    return {
        "label": "Geant4-DNA water",
        "ice_type": "water",
        "density_g_cm3": WATER_DENSITY_G_CM3,
        "emin": max(float(np.min(exc_energy)), float(np.min(ion_energy))),
        "emax": min(float(np.max(exc_energy)), float(np.max(ion_energy))),
        "dedx_exc": exc_dedx,
        "dedx_ion": ion_dedx,
        "dedx_total": exc_dedx + ion_dedx,
        "imfp_exc": exc_imfp,
        "imfp_ion": ion_imfp,
        "imfp_total": exc_imfp + ion_imfp,
    }


def _plot(
    energy_grid: np.ndarray,
    series: list[dict],
    units: str,
    projectile_key: str,
    projectile_axis_label: str,
    out_path: Path,
) -> None:
    fig = plt.figure(figsize=(10, 11.6))
    gs = fig.add_gridspec(
        3,
        1,
        height_ratios=[3.0, 2.0, 1.2],
        hspace=0.42,
    )
    ax_sp = fig.add_subplot(gs[0, 0])
    ax_imfp = fig.add_subplot(gs[1, 0], sharex=ax_sp)
    ax_legend = fig.add_subplot(gs[2, 0])
    ax_legend.axis("off")
    ax_sp.tick_params(labelbottom=False)

    styles = {
        "amorphous": {"color": "SlateGray", "ls": "-"},
        "hexagonal": {"color": "0.55", "ls": "--"},
        "water": {"color": "#0072B2", "ls": "-."},
    }
    xmins = []
    xmaxs = []
    for item in series:
        density = float(item["density_g_cm3"])
        y_sp, ylabel = _units_and_label(units, density, item["dedx_total"])
        y_imfp = item["imfp_total"]
        valid_sp = np.isfinite(y_sp) & (y_sp > 0.0)
        valid_imfp = np.isfinite(y_imfp) & (y_imfp > 0.0)
        emin = item.get("emin")
        emax = item.get("emax")
        if emin is not None:
            valid_sp &= energy_grid >= float(emin)
            valid_imfp &= energy_grid >= float(emin)
        if emax is not None:
            valid_sp &= energy_grid <= float(emax)
            valid_imfp &= energy_grid <= float(emax)
        valid_any = valid_sp | valid_imfp
        if np.any(valid_any):
            xmins.append(float(np.min(energy_grid[valid_any])))
            xmaxs.append(float(np.max(energy_grid[valid_any])))
        style = styles.get(item["ice_type"], {"color": "0.5", "ls": "-"})
        ax_sp.loglog(
            energy_grid[valid_sp],
            y_sp[valid_sp],
            color=style["color"],
            ls=style["ls"],
            linewidth=3,
            label=item["label"],
        )
        ax_imfp.loglog(
            energy_grid[valid_imfp],
            y_imfp[valid_imfp],
            color=style["color"],
            ls=style["ls"],
            linewidth=3,
            label=item["label"],
        )

    icru_curve = _load_icru_stopping_power(projectile_key)
    if icru_curve is not None:
        icru_energy, icru_mass_sp = icru_curve
        icru_y = _icru_mass_stopping_to_units(units, icru_mass_sp)
        valid_icru = (
            np.isfinite(icru_energy)
            & np.isfinite(icru_y)
            & (icru_energy >= float(np.min(energy_grid)))
            & (icru_energy <= float(np.max(energy_grid)))
            & (icru_y > 0.0)
        )
        if np.any(valid_icru):
            ax_sp.loglog(
                icru_energy[valid_icru],
                icru_y[valid_icru],
                color="black",
                ls=":",
                linewidth=3,
                label="ICRU 90 water",
                zorder=4,
            )

    ax_sp.set_ylabel(ylabel)
    ax_imfp.set_ylabel(r"Inverse MFP (nm$^{-1}$)")
    ax_imfp.set_xlabel(f"{projectile_axis_label} energy ($T$; eV)")
    ax_imfp.set_xlim(float(np.min(energy_grid)), float(np.max(energy_grid)))
    for ax in (ax_sp, ax_imfp):
        ax.xaxis.set_major_locator(LogLocator(base=10.0, subs=(1.0,), numticks=50))
        ax.xaxis.set_major_formatter(LogFormatterMathtext(base=10.0))
        ax.xaxis.set_minor_locator(
            LogLocator(base=10.0, subs=np.arange(2, 10) * 0.1, numticks=100)
        )
        ax.xaxis.set_minor_formatter(NullFormatter())
        ax.yaxis.set_major_locator(LogLocator(base=10.0, subs=(1.0,), numticks=50))
        ax.yaxis.set_major_formatter(LogFormatterMathtext(base=10.0))

    handles, labels = ax_sp.get_legend_handles_labels()
    if handles:
        ax_legend.legend(
            handles,
            labels,
            loc="center",
            bbox_to_anchor=(0.0, 0.0, 1.0, 1.0),
            mode="expand",
            ncol=1,
            frameon=False,
            columnspacing=1.2,
            handlelength=2.4,
            handletextpad=0.6,
            borderaxespad=0.0,
        )

    fig.subplots_adjust(left=0.30, right=0.98, top=0.97, bottom=0.06)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, bbox_inches="tight", pad_inches=0.35)
    fig.show()
    print(f"Saved plot to: {out_path}")


def _config_csv(value: object) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, (list, tuple)):
        return ",".join(str(item) for item in value)
    return str(value)


def _config_bool(value: object, default: bool = False) -> bool:
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() not in {"0", "false", "no", "off"}


def _print_water_icru_comparison(
    energy_grid: np.ndarray,
    water_series: dict | None,
    projectile_key: str,
    units: str,
) -> None:
    if water_series is None:
        return
    icru_curve = _load_icru_stopping_power(projectile_key)
    if icru_curve is None:
        return
    icru_energy, icru_mass_sp = icru_curve
    icru_y = _icru_mass_stopping_to_units(units, icru_mass_sp)
    target_e = 1.0e6
    if not (float(np.min(energy_grid)) <= target_e <= float(np.max(energy_grid))):
        target_e = float(np.sqrt(float(np.min(energy_grid)) * float(np.max(energy_grid))))
    water_y = _interp_loglog(energy_grid, water_series["dedx_total"], np.asarray([target_e]))[0]
    if units != "ev_nm":
        water_y = _units_and_label(units, WATER_DENSITY_G_CM3, np.asarray([water_y]))[0][0]
    icru_at_e = _interp_loglog(icru_energy, icru_y, np.asarray([target_e]))[0]
    if water_y > 0.0 and icru_at_e > 0.0:
        ratio = water_y / icru_at_e
        print(
            "Geant4-DNA water vs ICRU at "
            f"{target_e / 1.0e6:.6g} MeV: {water_y:.6g} vs {icru_at_e:.6g} "
            f"({ratio:.4g}x)"
        )


def main(config: dict[str, object] | None = None) -> None:
    config = {} if config is None else config
    parser = argparse.ArgumentParser(
        description="Compute projectile stopping power and IMFP from generated DCS tables."
    )
    parser.add_argument(
        "--projectile",
        default=str(config.get("projectile", "proton")),
        help="proton, alpha, or carbon",
    )
    parser.add_argument(
        "--emin",
        type=float,
        default=float(config.get("emin", 1.0)),
        help="Minimum energy (eV)",
    )
    parser.add_argument(
        "--emax",
        type=float,
        default=float(config.get("emax", 1.0e8)),
        help="Maximum energy (eV)",
    )
    parser.add_argument(
        "--nbins",
        type=int,
        default=int(config.get("nbins", 500)),
        help="Number of log bins",
    )
    parser.add_argument(
        "--units",
        default=str(config.get("units", "ev_ang")),
        choices=("ev_ang", "ev_nm", "mev_cm", "mev_cm2_g"),
        help="Output units for stopping power.",
    )
    parser.add_argument(
        "--ice-types",
        default=_config_csv(config.get("ice_types", ("amorphous", "hexagonal"))),
        help="Comma-separated ice types to plot (amorphous,hexagonal).",
    )
    parser.add_argument(
        "--rho-ice",
        type=float,
        default=config.get("rho_ice", None),
        help="Override ice density (g/cm^3).",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=config.get("out", None),
        help="Output plot path.",
    )
    parser.add_argument(
        "--stopping-cutoff",
        default=str(config.get("stopping_cutoff", "none")),
        choices=("none", "wmax_nonrel"),
        help=(
            "Optional stopping-power-only energy-transfer cutoff. "
            "Use wmax_nonrel to test the 2009 heavy-projectile convention; "
            "IMFP/total cross sections are unchanged."
        ),
    )
    parser.add_argument(
        "--include-water",
        action=argparse.BooleanOptionalAction,
        default=_config_bool(config.get("include_water", True), True),
        help="Overlay Geant4-DNA water stopping/IMFP where native water tables are available.",
    )
    args = parser.parse_args()

    if args.emin <= 0.0 or args.emax <= 0.0 or args.emin >= args.emax:
        raise ValueError("Invalid energy range.")
    projectile_key, projectile = _projectile_config(args.projectile)
    projectile_token = str(projectile["file_token"])
    projectile_label = str(projectile["label"])
    projectile_mass_au = float(projectile["mass_au"])
    projectile_axis_label = PROJECTILE_AXIS_LABELS.get(projectile_key, projectile_key.capitalize())
    ice_types = [v.strip().lower() for v in args.ice_types.split(",") if v.strip()]
    ice_types = [v for v in ice_types if v in ICE_DENSITY_BY_TYPE]
    if not ice_types:
        raise ValueError("No valid ice types specified.")

    coverage = {
        ice_type: _plot_energy_range(projectile_token, ice_type)
        for ice_type in ice_types
    }
    domain_emin = max(bounds[0] for bounds in coverage.values())
    domain_emax = min(bounds[1] for bounds in coverage.values())
    plot_emin = max(float(args.emin), domain_emin)
    plot_emax = min(float(args.emax), domain_emax)
    if plot_emin >= plot_emax:
        raise ValueError(
            "Requested energy range does not overlap the generated projectile "
            f"cross-section domain ({domain_emin:.6g} to {domain_emax:.6g} eV)."
        )
    if plot_emin != args.emin or plot_emax != args.emax:
        print(
            "Using projectile generated-energy domain "
            f"{plot_emin:.6g} to {plot_emax:.6g} eV "
            "(from the generator T_list cache when available)."
        )

    energy = np.logspace(np.log10(plot_emin), np.log10(plot_emax), args.nbins)
    series = [
        _build_series(
            projectile_token,
            projectile_label,
            projectile_mass_au,
            ice_type,
            energy,
            args.rho_ice,
            args.stopping_cutoff,
        )
        for ice_type in ice_types
    ]
    water_series = None
    if args.include_water:
        water_series = _build_water_series(
            projectile_key,
            projectile_mass_au,
            energy,
            args.stopping_cutoff,
        )
        if water_series is not None:
            series.append(water_series)
        else:
            print(f"No Geant4-DNA water Born table overlay is available for {projectile_key}.")

    out_path = args.out
    if out_path is None:
        ice_suffix = "_".join(ice_types)
        out_path = OUTPUT_DIR / f"stopping_power_imfp_{projectile_key}_{ice_suffix}_ice.png"

    _plot(
        energy_grid=energy,
        series=series,
        units=args.units,
        projectile_key=projectile_key,
        projectile_axis_label=projectile_axis_label,
        out_path=out_path,
    )
    _print_water_icru_comparison(energy, water_series, projectile_key, args.units)


if __name__ == "__main__":
    RUN_CONFIG = {
        "projectile": "proton",
        "ice_types": ("amorphous", "hexagonal"),
        "stopping_cutoff": "wmax_nonrel",
        "include_water": True,
    }

    main(RUN_CONFIG)
