"""Render and parse fixed-charge all-electron CP2K calculations."""

from __future__ import annotations

import math
import re
from typing import Any

import numpy as np

from .config import CP2KSettings


COMPLEX_ROLE = "complex_cdft"
PROJECTILE_COUNTERPOISE_ROLE = "projectile_counterpoise"
WATER_COUNTERPOISE_ROLE = "water_counterpoise"
ROLES = (COMPLEX_ROLE, PROJECTILE_COUNTERPOISE_ROLE, WATER_COUNTERPOISE_ROLE)


def _coordinate_kinds(role: str) -> tuple[str, ...]:
    if role == COMPLEX_ROLE:
        return ("P", "O_W", "H_W", "H_W")
    if role == PROJECTILE_COUNTERPOISE_ROLE:
        return ("P", "O_G", "H_G", "H_G")
    if role == WATER_COUNTERPOISE_ROLE:
        return ("P_G", "O_W", "H_W", "H_W")
    raise ValueError(f"Unsupported CP2K task role {role!r}.")


def _kind_section(label: str, element: str, settings: CP2KSettings) -> str:
    ghost = label.endswith("_G")
    ghost_line = "\n      GHOST TRUE" if ghost else ""
    basis_set = (
        settings.projectile_basis_set
        if label in {"P", "P_G"}
        else settings.water_basis_set
    )
    return f"""    &KIND {label}
      ELEMENT {element}
      BASIS_SET {basis_set}
      POTENTIAL {settings.potential}
      LEBEDEV_GRID 110
      RADIAL_GRID 80{ghost_line}
    &END KIND"""


def _cdft_section(target_electrons: int, settings: CP2KSettings) -> str:
    return f"""
      &CDFT
        TYPE_OF_CONSTRAINT BECKE
        ATOMIC_CHARGES TRUE
        STRENGTH 0.0
        TARGET {target_electrons:d}
        &ATOM_GROUP
          ATOMS 1
          COEFF 1
          CONSTRAINT_TYPE CHARGE
        &END ATOM_GROUP
        &DUMMY_ATOMS
          ATOMS 2..4
        &END DUMMY_ATOMS
        &OUTER_SCF ON
          TYPE CDFT_CONSTRAINT
          EPS_SCF {settings.cdft_eps:.12g}
          MAX_SCF {settings.cdft_max:d}
          EXTRAPOLATION_ORDER 2
          OPTIMIZER NEWTON_LS
          STEP_SIZE -1.0
          &CDFT_OPT ON
            MAX_LS 5
            CONTINUE_LS
            FACTOR_LS 0.5
            JACOBIAN_STEP 1.0E-2
            JACOBIAN_FREQ 1 1
            JACOBIAN_TYPE FD1
            JACOBIAN_RESTART FALSE
          &END CDFT_OPT
        &END OUTER_SCF
        &BECKE_CONSTRAINT
          ADJUST_SIZE FALSE
          IN_MEMORY TRUE
          CAVITY_CONFINE FALSE
        &END BECKE_CONSTRAINT
        &PROGRAM_RUN_INFO ON
          &EACH
            QS_SCF 1
          &END EACH
          COMMON_ITERATION_LEVELS 2
          ADD_LAST NUMERIC
          FILENAME ./cdft
        &END PROGRAM_RUN_INFO
      &END CDFT"""


def render_cp2k_input(task: dict[str, Any], settings: CP2KSettings) -> str:
    """Render one complete, nonperiodic GAPW input without hidden defaults."""

    role = str(task["role"])
    if role not in ROLES:
        raise ValueError(f"Unsupported CP2K task role {role!r}.")
    coordinates = task["coordinates_angstrom"]
    if len(coordinates) != 4:
        raise ValueError("The molecular pilot requires projectile + O + H + H.")

    if role == WATER_COUNTERPOISE_ROLE:
        charge = 0
        multiplicity = 1
    else:
        charge = int(task["charge"])
        multiplicity = int(task["multiplicity"])

    raw = np.asarray([[row[1], row[2], row[3]] for row in coordinates], dtype=float)
    if raw.shape != (4, 3) or not np.all(np.isfinite(raw)):
        raise ValueError("Invalid scan coordinates.")
    centered = raw - 0.5 * (raw.min(axis=0) + raw.max(axis=0))
    centered += 0.5 * settings.cell_angstrom
    margin = np.minimum(centered.min(axis=0), settings.cell_angstrom - centered.max(axis=0))
    if np.any(margin <= 5.0):
        raise ValueError(
            "The molecular density would have less than 5 A of cell margin; "
            "increase the nonperiodic cell."
        )

    labels = _coordinate_kinds(role)
    coordinate_lines = []
    kinds: dict[str, str] = {}
    for label, source, xyz in zip(labels, coordinates, centered, strict=True):
        element = str(source[0])
        kinds[label] = element
        coordinate_lines.append(
            f"      {label:<4s} {xyz[0]: .12f} {xyz[1]: .12f} {xyz[2]: .12f}"
        )
    kind_sections = "\n".join(
        _kind_section(label, element, settings) for label, element in kinds.items()
    )
    cdft = (
        _cdft_section(int(task["electrons_on_projectile"]), settings)
        if role == COMPLEX_ROLE
        else ""
    )

    project = re.sub(r"[^A-Za-z0-9_-]", "_", str(task["task_id"]))[:100]
    if not project:
        raise ValueError("Task ID produced an empty CP2K project name.")
    return f"""# Generated by soft_dft; pilot data remain validation_pending.
&GLOBAL
  PROJECT {project}
  RUN_TYPE ENERGY_FORCE
  PRINT_LEVEL MEDIUM
&END GLOBAL

&FORCE_EVAL
  METHOD QUICKSTEP
  &DFT
    BASIS_SET_FILE_NAME {settings.basis_file}
    CHARGE {charge:d}
    MULTIPLICITY {multiplicity:d}
    UKS TRUE
    &QS
      METHOD {settings.method}
      EPS_DEFAULT 1.0E-12{cdft}
    &END QS
    &MGRID
      CUTOFF {settings.mgrid_cutoff_ry:.12g}
      REL_CUTOFF {settings.mgrid_rel_cutoff_ry:.12g}
      NGRIDS 5
    &END MGRID
    &POISSON
      PERIODIC NONE
      POISSON_SOLVER WAVELET
    &END POISSON
    &SCF
      SCF_GUESS ATOMIC
      EPS_SCF {settings.scf_eps:.12g}
      MAX_SCF {settings.scf_max:d}
      &OT ON
        MINIMIZER DIIS
        PRECONDITIONER FULL_ALL
        ALGORITHM IRAC
      &END OT
      &OUTER_SCF ON
        EPS_SCF {settings.scf_eps:.12g}
        MAX_SCF 10
      &END OUTER_SCF
    &END SCF
    &XC
      &XC_FUNCTIONAL {settings.xc_functional}
      &END XC_FUNCTIONAL
    &END XC
    &PRINT
      &MULLIKEN ON
      &END MULLIKEN
      &LOWDIN ON
      &END LOWDIN
    &END PRINT
  &END DFT
  &SUBSYS
    &CELL
      ABC {settings.cell_angstrom:.12g} {settings.cell_angstrom:.12g} {settings.cell_angstrom:.12g}
      PERIODIC NONE
    &END CELL
    &COORD
{chr(10).join(coordinate_lines)}
    &END COORD
{kind_sections}
  &END SUBSYS
  &PRINT
    &FORCES ON
      FILENAME ./forces
    &END FORCES
  &END PRINT
&END FORCE_EVAL
"""


_FLOAT = r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[EeDd][-+]?\d+)?"
_ENERGY_RE = re.compile(
    rf"^[ \t]*ENERGY\|[^\r\n]*?\benergy\b[^\r\n]*?({_FLOAT})[ \t]*$",
    re.IGNORECASE | re.MULTILINE,
)
_VERSION_RE = re.compile(
    r"CP2K\|\s+version string:\s*(.+?)\s*$", re.IGNORECASE | re.MULTILINE
)


def _last_float(pattern: str, text: str) -> float | None:
    matches = re.findall(pattern, text, flags=re.IGNORECASE)
    if not matches:
        return None
    return float(str(matches[-1]).replace("D", "E").replace("d", "e"))


def parse_cp2k_output(text: str, *, require_cdft: bool) -> dict[str, Any]:
    """Extract only values needed for restart and scientific acceptance."""

    energy_matches = _ENERGY_RE.findall(text)
    energy = (
        float(energy_matches[-1].replace("D", "E").replace("d", "e"))
        if energy_matches
        else None
    )
    version_matches = _VERSION_RE.findall(text)
    result: dict[str, Any] = {
        "energy_hartree": energy,
        "cp2k_version": (
            version_matches[-1].strip() if version_matches else None
        ),
        "scf_converged": "SCF run converged" in text,
        "program_ended": "PROGRAM ENDED AT" in text,
    }
    if require_cdft:
        result.update(
            {
                "cdft_converged": "CDFT SCF loop converged" in text,
                "cdft_target_electrons": _last_float(
                    rf"Target value of constraint\s*:\s*({_FLOAT})", text
                ),
                "cdft_current_electrons": _last_float(
                    rf"Current value of constraint\s*:\s*({_FLOAT})", text
                ),
                "cdft_deviation_electrons": _last_float(
                    rf"Deviation from target\s*:\s*({_FLOAT})", text
                ),
            }
        )
    else:
        result["cdft_converged"] = None
    result["valid_completion"] = bool(
        energy is not None
        and math.isfinite(energy)
        and result["scf_converged"]
        and result["program_ended"]
        and (not require_cdft or result["cdft_converged"])
    )
    return result
